### ISSUE TITLE
Date objects are converted to strings

### ISSUE THREAD

**Issue by toniengelhardt** [prazdevs/pinia-plugin-persistedstate#10]
In the following scenario the `Date()` object is converted to a `string` after page refresh:

```js
state: () => {
  items: []
}

actions: {
  addItem(data) {
    const newItem = data
    newItem.createdDt = new Date()
    this.items.push(newItem)
  }
}
```

When I add the item and retrieve it immediately, it is a `Date` object. However, after refreshing the page, when the store is restored from local storage `items[0].createdDt` is a `string`.

**Comment by prazdevs** [comment]
I guess this is coming from the way the data is serialized before being stored. As it is transformed with a `JSON.stringify`/`JSON.parse`, any 'non JS data type' is kept as string. Idk how to tackle this issue without breaking things other than using the hooks from #12 to reformat data.

**Comment by toniengelhardt** [comment]
I think one option would be to store the datatype of every item together with the value in local storage and then convert back on hydration, but that would certainly be a huge effort, especially for items with nested dicts, etc. 

I guess for now it's fine, I just switched to storing all dates as strings. But maybe a short note in the README would be great mentioning this problem, it took me while to find out what was wrong.

**Comment by prazdevs** [comment]
I'll add a line in the "limitations" part of the readme, specifying that serialization loses non primitive types such as Date. Workaround can also be the use of the freshly implemented hooks! :)

Seems like a wont-fix with a workaround to me, if you're fine with it.

**Comment by prazdevs** [comment]
[aa52a70](https://github.com/prazdevs/pinia-plugin-persistedstate/commit/a708d8af9655e8e35359cf4976a16b74dc4e9231) should close this. Thanks for the contribution!
