### ISSUE TITLE
[nuxt] calling store.$hydrate uses old values

### ISSUE THREAD

**Issue by stephenjason89** [prazdevs/pinia-plugin-persistedstate#100]
### Describe the bug
Note: this bug is only during SSR

After calling store.$hydrate()
Store was hydrated with old values and not the new ones.

<img width="634" alt="image" src="https://user-images.githubusercontent.com/3810177/183139373-74d7a4b1-f1fc-48d7-bfe7-5201533884e7.png">

As you can see,
1. I updated the auth store with auth.refresh()
2. I console.log the tokenExpiration before and after auth.refresh()
3. I called auth.$hydrate() to update the store

See the error: 
Clearly after method auth.refresh() was called, a new tokenExpiration is logged.

But after calling the $hydrate, it still uses the old one.
<img width="1721" alt="image" src="https://user-images.githubusercontent.com/3810177/183139460-548c5858-b813-436b-89b2-a3a25d1c23a5.png">

This was logged from my pinia plugin createPersistedState
<img width="383" alt="image" src="https://user-images.githubusercontent.com/3810177/183140295-845eca7d-9fbf-467f-894b-d75ff1746159.png">

I was changing the state like this & setItem is not being called automatically in SSR so i had to do $hydrate
<img width="451" alt="image" src="https://user-images.githubusercontent.com/3810177/183141596-2bdf83e8-defb-4dd0-94e7-4f8332b31fe4.png">

However, setting the store like this, seems to work fine in SSR and setItem is being called with correct values
<img width="465" alt="image" src="https://user-images.githubusercontent.com/3810177/183141737-3cfc31f8-9f53-4ce8-8617-2907e079d3f8.png">

### Reproduction

Install @pinia/nuxt 0.3.1 together with pinia 2.0.17

### System Info

```Shell
System:
    OS: macOS 12.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 29.00 GB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.7.0 - /usr/local/bin/node
    Yarn: 3.2.1 - /usr/local/bin/yarn
    npm: 8.15.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 104.0.5112.79
    Firefox: 103.0
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by prazdevs** [comment]
v3 is now release with available nuxt module as well! docs are also deployed 🚀 
closing this for now, if still having issues, feel free to reopen and i will investigate
