### ISSUE TITLE
[nuxt] "Hydration text content mismatch" in client side with nuxt 3

### ISSUE THREAD

**Issue by DonSalvador** [prazdevs/pinia-plugin-persistedstate#105]
### Describe the bug

When using the plugin on the client side with Nuxt 3, a mismatch in hydration appears.

### Reproduction

https://stackblitz.com/edit/nuxt-starter-9mvexw?file=composables/authStore.ts

### System Info

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (4) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.10 - /bin/yarn
    npm: 7.17.0 - /bin/npm
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by prazdevs** [comment]
Ok i got time to try it and it is indeed weird, does it cause any problem besides the warning ?

**Comment by DonSalvador** [comment]
No warning.  I ended up using <client-only> which I think is appropriate since the data will only be available on the client.

**Comment by prazdevs** [comment]
v3 is now release with available nuxt module as well! docs are also deployed 🚀 
closing this for now, if still having issues, feel free to reopen
