### ISSUE TITLE
[core] can not restore when i use `reactive` api

### ISSUE THREAD

**Issue by Hioolong** [prazdevs/pinia-plugin-persistedstate#108]
### store code

```
import { defineStore } from "pinia";
import { computed, ref, reactive } from "vue";

export type Item = {
  id: number;
  content: string;
};

let id = 0;
const generateId = () => id++;

export const useTodoStore = defineStore(
  "todo",
  () => {
    const inputVal = ref("");
    const todos = reactive<Item[]>([]);
    const todosNum = computed(() => todos.length);

    function addTodo() {
      todos.push({
        id: generateId(),
        content: inputVal.value,
      });
      inputVal.value = "";
    }

    function remove(item: Item) {
      const index = todos.indexOf(item);
      todos.splice(index, 1);
    }

    return {
      inputVal,
      todos,
      todosNum,
      addTodo,
      remove,
    };
  },
  {
    persist: true,
  }
);

```

### use `reactive` api

it can not render the result event localstorage has value

![image](https://user-images.githubusercontent.com/33807468/185081457-b64783b9-860a-403c-82c0-68764a103e15.png)

![image](https://user-images.githubusercontent.com/33807468/185081421-ffbd447e-ae00-446c-9c5c-c4c66eb8820e.png)

### use `ref` api

it can render correctly when i use `ref`

![image](https://user-images.githubusercontent.com/33807468/185081814-24237d62-734e-4757-af77-1cf108558c9a.png)

![image](https://user-images.githubusercontent.com/33807468/185081421-ffbd447e-ae00-446c-9c5c-c4c66eb8820e.png)

### Reproduction

https://github.com/Hioolong/vue-todo

### System Info

```Shell
System:
    OS: macOS 12.0.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.34 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.0 - ~/.nvm/versions/node/v14.18.0/bin/node
    Yarn: 1.22.15 - ~/.nvm/versions/node/v14.18.0/bin/yarn
    npm: 8.5.4 - ~/.nvm/versions/node/v14.18.0/bin/npm
    Watchman: 2021.10.04.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 104.0.5112.79
    Safari: 15.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by prazdevs** [comment]
There is a workaround in #120 ; i will investigate whenever i get time on why the serialization process kills persistence in the case of `reactive` objects :)
