### ISSUE TITLE
References are getting lost

### ISSUE THREAD

**Issue by toniengelhardt** [prazdevs/pinia-plugin-persistedstate#11]
I'm not sure if there is a fix for this and maybe it is a very specific case, but I have the following problem.

I create an object and add it to a list and a dictionary at the same time like so:

```js
state: () => {
  itemList: [],
  itemDict: {},
}

actions: {
  addItem(data: {id: number, ...}) {
    const newItem = data
    newItem.createdDt = new Date()
    this.itemList.push(newItem)
    this.itemDict[data.id] = newItem
  }
}
```

Now, an item that is in the list and in the dict has the same reference, aka. 

```js
itemList[0] === itemDict[itemList[0].id] -> true
```

and they are reactive, meaning that if I update the item in either the list or the dict it will also update in the other.

After refreshing the page and restoring the store from local storage the objects are not the same anymore, aka. 

```js
itemList[0] === itemDict[itemList[0].id] -> false
```

Therefore reactivity between them is getting lost.

I assume a side effect of this is also that the data is getting duplicated, consuming double the storage.

A workout around for this specific problem would be hook that is called after restoring the state. That way I could exclude either the list or the dict from being persisted and recreated it upon restoration, something like this:

A workout around for this specific problem would be a hook that is called after restoring the state. That way I could exclude either the list or the dict from being persisted and recreate it upon restoration, something like this:

```js
import { defineStore } from 'pinia'

export const useStore = defineStore('main', {
  state: () => {
    return {
      itemList: [],
      itemDict: {},
    }
  },
  persist: {
    paths: [
      'itemList',
    ],
    afterRestore: ({ state }) => {
      state.itemDict = state.itemList.reduce((dict, item) => {
        dict[item.id] = item
        return dict
      } , {})
    }
  }
})
```

**Comment by toniengelhardt** [comment]
@prazdevs I made a pull request for this (https://github.com/prazdevs/pinia-plugin-persistedstate/pull/12) implementing the above example and also a `beforeRestore` hook.

I tested it in my project and it works perfectly to restore reactivity ✌🏽

**Comment by prazdevs** [comment]
Aight, I looked into it, sounds good to me.
Since data is serialized to be persisted in local storage (or any StorageLike), we indeed lose references when we recreate them. 
The hook solution sounds like a good idea to work around this problem, as well as extending the API with an interesting feature.

I'll merge it and eventually change couple things in the tests to isolate them more and add to the docs. 

Really appreciate the contribution! I'll release a new version ASAP so you can use it in your projects.

**Comment by toniengelhardt** [comment]
Awesome thanks 🙏🏽
