### ISSUE TITLE
Before restore hook async?

### ISSUE THREAD

**Issue by chasegiunta** [prazdevs/pinia-plugin-persistedstate#111]
### Clear and concise description of the problem

As a developer using this plugin it would be nice to be able to run async functions in the `beforeRestore` hook so that we have access to certain data before running the deserializer.

### Suggested solution

Not sure if it's possible, but ensuring the `beforeRestore` function is completed before moving on the deserializer function would be extremely helpful.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by prazdevs** [comment]
Hi :) for now everything in the plugin is fully synchronous. There are ideas to support async storages, but as for hooks, nothing planned yet. 

Maybe once we get async storages (if we ever do), async hooks would be easy to add on top.

**Comment by chasegiunta** [comment]
Appreciate the quick response. In the meantime, I'm running the async calls in the deserializer itself. Not ideal, but a stop-gap for now 🙃

**Comment by prazdevs** [comment]
Closing this for now, for the same reasons explained in #17
