### ISSUE TITLE
[core] Circular references

### ISSUE THREAD

**Issue by tanghaojie** [prazdevs/pinia-plugin-persistedstate#112]
### Clear and concise description of the problem

Is there any way custom circular references persist ?

### Suggested solution

custom serialization , or exclude circular key

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by prazdevs** [comment]
Hi, the reason circular references arent managed is mostly due to serialization being handled by JSON.stringify/JSON.parse and it doesnt work with circular references. There is probably a workaround using either a custom serializer or the hooks to restore the references ?

**Comment by prazdevs** [comment]
Marking this as stale, feel free to reopen with more info if the issue is still existing!
