### ISSUE TITLE
[core] Maximum call stack size exceeded

### ISSUE THREAD

**Issue by starleaf1** [prazdevs/pinia-plugin-persistedstate#114]
### Describe the bug

Defining an action which assigns a value to the state causes Maximum call stack size exceeded error

### Reproduction

1. Create a store with any number of state{s}, persist it using sessionStorage.
2. Define an action that assigns a value to a state (i.e. `this.myState = someValue`).
3. Use the action as a method in a component using `mapActions`
4. Serve the app, load the component.

### System Info

```Shell
System:
    OS: Linux 5.10 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i5-12400F
    Memory: 8.45 GB / 12.36 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by prazdevs** [comment]
Hi can you provide a proper reproduction repo or a stackblitz app ? :)
