### ISSUE TITLE
[core] Support array matching path definitions

### ISSUE THREAD

**Issue by floriankapaun** [prazdevs/pinia-plugin-persistedstate#116]
### Clear and concise description of the problem

I want to persist only specific properties of my store. The current [`paths`-option](https://prazdevs.github.io/pinia-plugin-persistedstate/guide/config.html#paths) is not sufficient in my case though, since it doesn't allow me to match all children of an array.

Currently I could only persist specific indices, but I can't know i.e. how many cart items a users cart may hold.

Example:

```js
import { defineStore } from 'pinia'

export const useStore = defineStore('cart', {
  state: () => ({
    cartItems: [
      {
        sku: '123',
        name: 'Chair',
        quantity: 4,
        details: {} // I don't want the details to be persisted, to keep my cookie small
      },
      {
        sku: '987',
        name: 'Desk',
        quantity: 1,
        details: {} // I don't want the details to be persisted, to keep my cookie small
      },
    ],
    // ...
  }),
  persist: {
    paths: ['cartItems.0.sku', 'cartItems.0.name', 'cartItems.0.quantity'],
  },
})
```

### Suggested solution

To solve this we'd have to update the get and set methods in [`pick.ts`](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/fa5ebb52dfc0f05dc8c854be435994c1a33f69a0/src/core/pick.ts) but more importantly agree on some syntax we could use to specify a path logic of the proposed kind.

A few syntax ideas:
- `cartItems.[].quantity`
- `cartItems.[i].quantity`
- `cartItems.[...].quantity`

### Additional context

Can imagine creating a pull request once we agree on the need and a syntax.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by prazdevs** [comment]
close in #117
