### ISSUE TITLE
After initializing the state of the Store, reinitializing the state through code does not trigger caching

### ISSUE THREAD

**Issue by laterdays** [prazdevs/pinia-plugin-persistedstate#118]
### Describe the bug

After initializing the state of the Store, reinitializing the state through code does not trigger caching

### Reproduction

*

### System Info

```Shell
After initializing the state of the Store, reinitializing the state through code does not trigger caching
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [ ] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by laterdays** [comment]
```
export const useStore = defineStore('main', {
  state: () => ({
    someState: 'hello pinia',
  }),
  persist: {},
})
```

When I manually change sameState in my code to Hello Word, it will not be saved in the cache

**Comment by prazdevs** [comment]
Hi, please refer to the documentation for correct usage here: https://prazdevs.github.io/pinia-plugin-persistedstate/

Also, issues won't be looked into if no proper reproduction (repo, stackblitz...) is provided.

Feel free to reopen once you follow the validations. :)
