### ISSUE TITLE
In documentation's nuxt 3 example, add plugin order problem.

### ISSUE THREAD

**Issue by minkoonim** [prazdevs/pinia-plugin-persistedstate#124]
### Clear and concise description of the problem

I have two plugins here,
nuxtHook.ts - where I store all nuxt hooks
persistedState.ts - same as in document

within app:created hook, 
I put "configStore" there so if user locale is not set, 
use navigator default language,
and totally forgot about it

When I found out configStore's state is not persist,
I looked into all possible problems for hours excpet this one.
I feel so dumb now

nuxtHook plugin was loaded before persistedState,
so the configStore was initialized before persistplugin was of use.

### Suggested solution

I hope documentation states this problem,
so no poor others like me lose hair over this problem...

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by prazdevs** [comment]
Hi :) is this related to this ? https://v3.nuxtjs.org/guide/directory-structure/plugins/#using-composables-within-plugins

I can add a bit of info in the docs indeed :)

**Comment by minkoonim** [comment]
> 

It's that if you want to use "persisted store" with in any plugin,
you have to make sure that persistedState.ts plugin loads before that one.

so why not just make example's persistedstate.ts => aPersistedState.ts ..?
and explain what "a" is for? 

because newbies like me just copy and paste examples,
and when problem happens, got no clues why,
and just might blame your beautiful work

I haven's seen exact way to manually set order for plugins yet,
I think it loads in alphabetical order according to this
https://github.com/nuxt/framework/discussions/1260

**Comment by prazdevs** [comment]
Fair enough, I'll do it in the upcoming days!
Thanks for taking your time to come up with the issue and help others 🎉

**Comment by minkoonim** [comment]
> 

I thank you for your great work Thanks man
