### ISSUE TITLE
[core]  Add methods to manually update storage and hydrate store

### ISSUE THREAD

**Issue by saini-sahab** [prazdevs/pinia-plugin-persistedstate#133]
There is a need control for when the storage is updated to persist data and also when to hydrate the store. 

For me the use case arose when an operation in my app was updating the state multiple times but the data was required to be persisted only once the operation finished. Hence for performance reasons, storing the data on `$subscribe` was not good.

I intend to submit a PR for same and another one so as to have triggers for when the storage is updated.

### Suggested solution

Expose a method on the store to update storage for that persistence. If there are multiple persistences then you will need to pass the index of the same.

Also deprecate `$hydrate` and move it inside the `$persist` where both the methods can be exposed. Having them under a common key would help keep the context.

```ts
export interface PiniaCustomProperties {
  $persist: {
    /**
     * Manually updates storage with the persisted state
     */
    updateStorage: (persistanceIndex?: number) => void,

    /**
     * Rehydrates store from persisted state
     */
    hydrate: (opts?: { runHooks?: boolean }) => void
  }
}
```

I am not sure if deprecating the earlier method is advisable or not but can be helpful in future use cases

### Alternative

Instead of deprecating the older method we can just add another method `$persist` that would do the job of 'updateStorage' on the store instance.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by prazdevs** [comment]
After carefully reading the issue and what it would solve, I'm thinking it gets out of the scope of this plugin. 

The main prupose of this plugin is to provide a simple and out of the box "sync" between a pinia store and storage. Adding manual triggers and options kinda defeats this purpose, and should be considered a completely different plugin/solution. Also multiple persistences (array) is already an advanced usage, and it adds exponential complexity to consider this issue.

I hope you understand my concerns in this.

**Comment by saini-sahab** [comment]
I understand your concerns though let me add my reasons as well. This is a good plugin and quite useful for 90% of the use cases. That is the only gap this PR is trying to fill. 

Also this PR is not take away the simplicity of the library. Just adding some features for the opt-in complexity some projects will require.

**Comment by prazdevs** [comment]
This adds incredible complexity to the code, however, the issue should still be considered. I added a new `vnext` tag that will make me remember about it in the next major version, so I can break everything and implement different base mechanics.

**Comment by saini-sahab** [comment]
All right, will be looking forward to it. Though I do still think that we can structure this solution to make code more readable for easier maintenance than build it base up.

**Comment by prazdevs** [comment]
v3 has been released and now features a $persist and a $hydrate method. it's not as deep, but allows for manual triggers.
