### ISSUE TITLE
Persisting only one module / store in Nuxt3

### ISSUE THREAD

**Issue by igortrinidad** [prazdevs/pinia-plugin-persistedstate#138]
### Describe the bug

I have 2 stores ("settings" and "windows") store and the plugin doesn't persisting the "settings" one, i changed the key to "appSettings" and didn't solve the issue...

The windows store is persisting correctly, but the "settings" isn't... I tried to move the settings to windows and everything works fine...

When i inspect the cookies on navigator i can't find the "settings" module, just the "windows"...

plugins/pinia.ts
````
import { createNuxtPersistedState }  from 'pinia-plugin-persistedstate/nuxt'
import { useCookie } from '#app'

export default defineNuxtPlugin(nuxtApp => {
  nuxtApp.$pinia.use(createNuxtPersistedState(useCookie))
})
````

store/windows.ts
````
import { defineStore } from 'pinia'

export const useWindowsStore = defineStore('windows', {
  
  persist: true,
  
  state: () => ({
   ....
  }),
  
  ....

})
````

store/settings.ts
````
import { defineStore } from 'pinia'

export const useSettingsStore = defineStore('appSettings', {
  
  persist: true,
  
  state: () => ({
    ...
  }),
  
  ....

})
````

### Reproduction

https://github.com/igortrinidad/igortrindade-os

### System Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 4.02 GB / 7.72 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.17.1 - ~/.nvm/versions/node/v14.17.1/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v14.17.1/bin/yarn
    npm: 8.5.4 - ~/.nvm/versions/node/v14.17.1/bin/npm
```

```json
{
  "private": true,
  "scripts": {
    "serve": "nuxt dev",
    "dev:tailwind": "tailwind-config-viewer --open --port 3001",
    "build": "nuxt build",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "concurrently": "^7.5.0",
    "nuxt": "3.0.0-rc.13",
    "standard-version": "^9.5.0",
    "tailwind-config-viewer": "^1.6.2"
  },
  "dependencies": {
    "@igortrindade/lazyfy": "^1.4.0",
    "@nuxtjs/tailwindcss": "^6.1.2",
    "@pinia/nuxt": "^0.4.3",
    "@vercel/analytics": "^0.1.3",
    "logrocket": "^3.0.1",
    "pinia-plugin-persistedstate": "^2.3.0",
    "rrweb": "^2.0.0-alpha.3",
    "sass": "^1.55.0",
    "sass-loader": "^13.1.0",
    "tailwindcss": "^3.2.1"
  }
}

```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by prazdevs** [comment]
I cant access the repo you gave :/

**Comment by igortrinidad** [comment]
Sorry about that @prazdevs, tomorrow morning I'll create a new nuxt repo to you reproduce the error, but i found what is triggering the issue:

The issue only happens when i try to access the store inside a nuxt "plugin" folder so the store module won't be persisted and remains as default state on every page refresh...

That's why my "settings" store isn't persisting and the "windows" one was...

So if somebody stuck with this, the solution was access / handle the store in app.vue on root folder, instead of plugins/* folder...

**Comment by prazdevs** [comment]
You may want to pay attention to this particular note on using stores in plugin alongside persistence 
https://prazdevs.github.io/pinia-plugin-persistedstate/frameworks/nuxt-3.html#note-on-nuxt-plugins

**Comment by igortrinidad** [comment]
Thanks for the tip, i saw that yesterday but i'm using the cookie approach to save, so i believe that isn't client only... What i was doing is just running a script to set the darkMode default state only in client cause i need to access the window prefference, so that's why i created the "plugin/general.client.ts" file to run before the view being rendered, do you know?

**Comment by prazdevs** [comment]
v3 is now release with available nuxt module as well! docs are also deployed 🚀 
closing this for now, if still having issues, feel free to reopen

**Comment by igortrinidad** [comment]
Thanks, have a great weekend!
