### ISSUE TITLE
Cannot read properties of undefined (reading 'use')

### ISSUE THREAD

**Issue by andysay** [prazdevs/pinia-plugin-persistedstate#139]
### Describe the bug

Cannot read properties of undefined (reading 'use')

nuxt 3 released version ...

import { createNuxtPersistedState } from "pinia-plugin-persistedstate/nuxt";

export default defineNuxtPlugin((nuxtApp) => {
    nuxtApp.$pinia.use(createNuxtPersistedState(useCookie));
});

### Reproduction

-

### System Info

```Shell
-
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by prazdevs** [comment]
Hi, as said in some other issue, now that nuxt stable is released, i will start working on a proper way to intergrate the plugin with nuxt :)

**Comment by prazdevs** [comment]
in the meantime maybe try to use `nuxtApp.pinia.use(createNuxtPersistedState(useCookie));`

**Comment by Aybee5** [comment]
I am also getting this error, and this is also generating the issue

> in the meantime maybe try to use `nuxtApp.pinia.use(createNuxtPersistedState(useCookie));`

**Comment by MyWay** [comment]
Same here.

**Comment by andysay** [comment]
problems was fixed , remove from buildmodules "@pinia/nuxt" config and add to modules.

**Comment by Aybee5** [comment]
Do we need to bump the version to another version? if yes, which version please.

I am using v2.4.0 and it's complaining that `createNuxtPersistedState` is not a function or has the function name being updated?

![image](https://user-images.githubusercontent.com/42099896/202809270-ed88e49c-72f4-444e-9db1-6af80d7ff099.png)

**Comment by prazdevs** [comment]
v3 is now release with available nuxt module as well! docs are also deployed 🚀 
closing this for now, if still having issues, feel free to reopen

**Comment by pferreirafabricio** [comment]
Unfortunately, I'm getting this same error using this versions:

"@pinia/nuxt": "^0.4.11"
"@pinia-plugin-persistedstate/nuxt": "^1.1.1"
