### ISSUE TITLE
Type errors in v2.4.0

### ISSUE THREAD

**Issue by toniengelhardt** [prazdevs/pinia-plugin-persistedstate#140]
### Describe the bug

When upgrading to `v2.4.0` I get type errors in my stores for the following config:

```ts
export const store = defineStore('myStore', {
  // state, actions, etc.
  persist: {
    paths: [
      'someList',
    ],
    afterRestore: ({ store }) => {
      // do smth... 
    }
  }
})
```

No problems with v2.3.0...

![Screenshot 2022-11-17 at 12 13 33](https://user-images.githubusercontent.com/2703233/202443584-dedafd41-dca7-445f-a8ec-f06d86b57c52.png)

### Reproduction

see code snippet above...

### System Info

```Shell
System:
    OS: macOS 13.0.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 41.49 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.11.0 - ~/.nvm/versions/node/v16.11.0/bin/node
    Yarn: 1.22.11 - ~/.nvm/versions/node/v16.11.0/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.11.0/bin/npm
  Browsers:
    Brave Browser: 106.1.44.101
    Chrome: 107.0.5304.110
    Firefox: 106.0.1
    Safari: 16.1
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by prazdevs** [comment]
Tried to reproduce it without any issue. All the types are fine ? Maybe if you could provide a proper Stackblitz repo ?

Or maybe try to reinstall the dependencies completely ? (lockfile included)

**Comment by toniengelhardt** [comment]
@prazdevs will try to reproduce. 

One thing I noticed is, I'm using with Nuxt 3, the type errors only show up and disappear if I delete the `.nuxt` folder and restart the dev server to rebuild it after upgrading/downgrading `pinia-plugin-persistedstate` package.

**Comment by prazdevs** [comment]
the `.nuxt` is where most types are automatically generated by nuxt, so it can come from this.

I have in the plans to rework lots of stuff to completely externalize nuxt support and make a proper nuxt module when i have some time :)

**Comment by toniengelhardt** [comment]
@prazdevs that would be amazing!

**Comment by prazdevs** [comment]
v3 is now release with available nuxt module as well! docs are also deployed 🚀 
closing this for now, if still having issues, feel free to reopen
