### ISSUE TITLE
Setting new value isn't persistent

### ISSUE THREAD

**Issue by ArthurDanjou** [prazdevs/pinia-plugin-persistedstate#141]
### Describe the bug

I have created an auth store that contains my user object.

You can find the [user store](https://github.com/ArthurDanjou/artdanj-website-v2/blob/main/src/store/user.ts) and the [composable](https://github.com/ArthurDanjou/artdanj-website-v2/blob/main/src/composables/useSupabase.ts#L11) where I call the setUser method from the store.

I put debug in the store method to check if I receive well the User object that I want :
```
setUser 
Object { id: 1, createdAt: "2022-11-12T17:23:34.798Z", role: "USER", username: "Arthur Danjou", ... }```

But just after the [`user.value = newUser`](https://github.com/ArthurDanjou/artdanj-website-v2/blob/main/src/store/user.ts#L12), the debug returns an empty ref

### Reproduction

https://github.com/ArthurDanjou/artdanj-website-v2

### System Info

```Shell
System:
    OS: macOS 12.5.1
    CPU: (8) arm64 Apple M1
    Memory: 654.66 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.4.0 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.19.3 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 107.0.5304.110
    Firefox Developer Edition: 108.0
    Safari: 15.6.1
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by prazdevs** [comment]
Since you are using nuxt, i am currently preparing the lib for a big refactor and hopefully will provide a proper nuxt module instead of the hacky plugin.

**Comment by ArthurDanjou** [comment]
Thank's for your answer and your work, 
I will wait for it so.
