### ISSUE TITLE
Argument of type 'persist' is not assignable to parameter of type

### ISSUE THREAD

**Issue by GreatWriter** [prazdevs/pinia-plugin-persistedstate#143]
### Describe the bug

```
export const useUserStore = defineStore(
	'user',
	() => {
		const userInfo: UserInfo = reactive({
			fullName: '',
			userName: '',
			employeeNumber: '',
			permission: '',
		});

		const token = ref(''); //token

		return { userInfo, token };
	},
	{
		persist: [
			{ paths: ['userInfo'], key: CacheKey.USER_INFO, storage: localStorage },
			{ paths: ['token'], key: CacheKey.TOKEN, storage: localStorage },
		],
	}
);
```

"pinia-plugin-persistedstate": "^2.3.0"

![p](https://user-images.githubusercontent.com/57381087/202986169-2a7fb352-c8de-44bc-90f0-c458625af21f.png)

### Reproduction

see code snippet above...

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
    Memory: 7.87 GB / 31.82 GB
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\node_modules\.bin\yarn.CMD
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (107.0.1418.52)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by prazdevs** [comment]
Hi, with only this info, i can only ask you to make sure you installed the plugin into pinia (`pinia.use()`) otherwise i will need a proper reproduction repo/stackblitz. ty :)

**Comment by GreatWriter** [comment]
thanks. i made a stupid mistake
