### ISSUE TITLE
[core] automatically persist all stores

### ISSUE THREAD

**Issue by SnowingFox** [prazdevs/pinia-plugin-persistedstate#146]
### Clear and concise description of the problem

Now we must enable persist manully, but in some cases, there has many stores should be persisted, so why not add a option to enable persist automatically?

### Suggested solution

```ts
import plugin from 'pinia-plugin-persistedstate'

pinia.use(pluigin({ auto: { exclude: ['xxx'], include: ['yyy'] } })
```

this means we should exclude the store which id is `xxx` and include store which id is `yyy`

### Alternative

this is easy to do it by user, but if this plugin can support this, i think it will improve much DX.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by prazdevs** [comment]
Hi :) I made this feature a thing, with a slightly different API to make is as simple as possible.

Auto mode will enable automatic persistence of all stores automatically, and you need to explicitely exclude stores in their config.

The documentation in English is done, would you do the Chinese translation ?

**Comment by SnowingFox** [comment]
> Hi :) I made this feature a thing, with a slightly different API to make is as simple as possible.
> 
> Auto mode will enable automatic persistence of all stores automatically, and you need to explicitely exclude stores in their config.
> 
> The documentation in English is done, would you do the Chinese translation ?

yeah, i would like to do.

**Comment by cloudmoonocus** [comment]
yeah，I will translate right away





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "prazdevs/pinia-plugin-persistedstate"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月13日(星期一) 中午1:15
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [prazdevs/pinia-plugin-persistedstate] [core] automatically persist all stores (Issue #146)





  
Hi :) I made this feature a thing, with a slightly different API to make is as simple as possible.
 
Auto mode will enable automatic persistence of all stores automatically, and you need to explicitely exclude stores in their config.
 
The documentation in English is done, would you do the Chinese translation ?
  
yeah, i would like to do.
