### ISSUE TITLE
How to set options using composition pattern?

### ISSUE THREAD

**Issue by demiro** [prazdevs/pinia-plugin-persistedstate#149]
So I am using Pinia like this:

```
export const useAppStore = defineStore("app", () => {
  const darkMode = ref(false);
  const useUnit = ref("C");
  ...
  return {
    darkMode,
    useUnit
  }
})
```

How do I set the options (like persist) in this pattern? Some examples would be great!

**Comment by HopeBaron** [comment]
```js
const pinia = createPinia()
pinia.use(piniaPluginPersistedstate)
export const useStore = defineStore('systemStore', () => {
  const token = ref()
  return { token }
}, {
  persist: true
} 
) 
```
options is a separate parameter; I used it this way and it works great

**Comment by demiro** [comment]
Cheers, works like a charm!

**Comment by prazdevs** [comment]
Hi it is specified in the documentation, as the second example here https://prazdevs.github.io/pinia-plugin-persistedstate/guide/#usage

Closing this :)
