### ISSUE TITLE
Manual restore

### ISSUE THREAD

**Issue by hooray** [prazdevs/pinia-plugin-persistedstate#152]
### Clear and concise description of the problem

Store data is persisted depending on the user, like this:

```js
    persist: {
      paths: ['list'],
      storage: {
        getItem: (key) => {
          return localStorage.getItem(`${user_unique_id}_${key}`)
        },
        setItem: (key, value) => {
          return localStorage.setItem(`${user_unique_id}_${key}`, value)
        },
      },
    },
```

However, when restoring data, `user_unique_id` may not exist because the user may not be logged in, and then the restore will fail. Is it possible to provide an API that allows me to manually or defer restore data ?

### Suggested solution

I don't have a good idea yet.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by prazdevs** [comment]
👋 Hey :)

Technically, using $hydrate should work as explained here if that answers your need ? 

https://prazdevs.github.io/pinia-plugin-persistedstate/guide/advanced.html#forcing-the-rehydration

**Comment by prazdevs** [comment]
closing as stale, hopefully your problem is solved, feel free to reopen ✌️
