### ISSUE TITLE
Browser storage support

### ISSUE THREAD

**Issue by rendomnet** [prazdevs/pinia-plugin-persistedstate#155]
### Clear and concise description of the problem

https://developer.chrome.com/docs/extensions/reference/storage/
The Storage API provides an extension-specific way to persist user data and state.

Can this plugin work with browser storage?
On your front page it says "Compatible with everything that uses Pinia".

### Suggested solution

Support for browser.storage api

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by rendomnet** [comment]
@prazdevs it would be nice to have some solution for async store.

**Comment by prazdevs** [comment]
Its part of how Pinia stores and the `$subscribe` method works.
If you need async behaviour within pinia, you will have to use actions, and the plugin cannot cover that in a consistent way.
