### ISSUE TITLE
Combine Vue and Nuxt version in single package ?

### ISSUE THREAD

**Issue by mrleblanc101** [prazdevs/pinia-plugin-persistedstate#157]
### Clear and concise description of the problem

Why are they seperate packages ? `pinia-plugin-persistedstate` for vue and `@pinia-plugin-persistedstate/nuxt` for nuxt.
I got confused at first because I had followed the install instuction from the main doc, then I found the nuxt doc when looking how to initialise the package and how options worked inside nuxt.

### Suggested solution

They should be a single packages with 2 exports, no ? So `pinia-plugin-persistedstate` for vue and `pinia-plugin-persistedstate/nuxt` for nuxt.

### Alternative

Both packages could also be under `@pinia-plugin-persistedstate`.
So `@pinia-plugin-persistedstate` for vue and `@pinia-plugin-persistedstate/nuxt` for nuxt.

### Additional context

This is usually how most Nuxt packages work.
I can give many exemple.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by prazdevs** [comment]
If you use nuxt, you dont need the base plugin, and vice versa. Nuxt module will download the base plugin. But the base plugin doesnt need to download any nuxt-related dependency.

And this is EXACTLY how pinia itself is named (`pinia`/`@pinia/nuxt`), because it allows using the nuxt module just by adding it to the module array.

This won't be changed.

**Comment by mrleblanc101** [comment]
You are right, that seem to be how pinia also work.
Weird how they went away from the convention.

Here are 3 packages that work the other way.
I feel this is better as it create less confusion.
```
'portal-vue/nuxt'
'vue-toastification/nuxt'
'vue-sweetalert2/nuxt'
```

**Comment by prazdevs** [comment]
It involves downloading unneeded nuxt dependencies for plain vue users, or quasar users, which we try to avoid here. And keep framework specific tools seperated from the main tool.
Also the packages you specify are only nuxt2 compatible.

Nuxt3 modules can be built with specific tools (@nuxt/kit) that dont belong in vue-only apps. :)
