### ISSUE TITLE
Initial state not persisted on first render

### ISSUE THREAD

**Issue by mrleblanc101** [prazdevs/pinia-plugin-persistedstate#158]
### Describe the bug

Maybe this is intended, but I was trying to see if I had initialized the plugin correctly and I wasn't seeing anything in the DevTools `Application -> Storage -> Cookies` tab when using the demo store:
```
import { defineStore } from 'pinia'

export const useStore = defineStore('store', {
  state: () => {
    return {
      someState: 'hello pinia',
    }
  },
  persist: {
    storage: persistedState.cookies
  },
})
```

To see anything appear, I had to manually edit a value of my store.
I would expect the initial state to also be saved in the cookie, no ? 
At least this would prevent confusion even if it's not stricly necessary as the initial value is "saved" in the JS.

### Reproduction

Let me know, and I'll create one

### System Info

```Shell
System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 1.15 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Chrome Canary: 111.0.5495.0
    Firefox: 107.0.1
    Safari: 16.1
    Safari Technology Preview: 16.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by prazdevs** [comment]
Hi, this is sort of intended. this was also the default behaviour of `vuex-persistedstate`, as there is no real need to persist a state that is the same as the initial one. However if you need to force persistence, you can call `$persist` as documented here https://prazdevs.github.io/pinia-plugin-persistedstate/guide/advanced.html#forcing-the-persistence :)

**Comment by mrleblanc101** [comment]
Thanks, noob question again. Just trying out Nuxt 3 for the first time.
In Nuxt 2, I would run this in `nuxtServerInit` in the VueX action.
How would I do this in Nuxt 3 ? In my `app.vue` created ?

**Comment by prazdevs** [comment]
You can run that in your `app.vue`, `script setup` probably, which is pretty much like the `created` hook.
