### ISSUE TITLE
Paths with arrays don't seem to work as documented.

### ISSUE THREAD

**Issue by jejacks0n** [prazdevs/pinia-plugin-persistedstate#159]
### Describe the bug

The [example in the docs](https://prazdevs.github.io/pinia-plugin-persistedstate/guide/config.html#paths) clarifies how to use arrays in paths:

```javascript
import { defineStore } from 'pinia'

export const useStore = defineStore('store', {
  state: () => ({
    save: [
      { me: 'saved', ignored: 'ignored' },
      { me: 'saved-too', value: 'ignored-too' },
      { me: 'saved-as-well', test: 'ignored-as-well' },
    ],
  }),
  persist: {
    paths: ['save.[].me'],
  },
})
```

But this doesn't work, and I can't find a test that would indicate this _could_ work.

Is the documentation correct? I sort of expected to find a test in https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/packages/plugin/tests/pick.spec.ts, or in the specs that cover configuring paths in https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/packages/plugin/tests/plugin.spec.ts#L191

So when peeking at the source, there wasn't anything obvious either, but maybe it's supposed to be handled by `StateTree` in pinia? I didn't dig further, so maybe someone knows off hand if the docs are incorrect, or if the feature didn't make it into release.

Thanks for the useful library, and I'll help update docs if there's something that needs to be updated there.

### Reproduction

https://prazdevs.github.io/pinia-plugin-persistedstate/guide/config.html#paths

### System Info

```Shell
Versions:
  pinia: "^2.0.28",
  pinia-plugin-persistedstate: "^3.0.1",
System:
  OS: macOS 13.0.1
  CPU: (10) arm64 Apple M1 Max
  Memory: 212.31 MB / 32.00 GB
  Shell: 5.8.1 - /bin/zsh
Binaries:
  Node: 19.2.0 - ~/.asdf/installs/nodejs/19.2.0/bin/node
  npm: 9.2.0 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Chrome: 108.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by prazdevs** [comment]
This feature has been removed for several reasons in 3.x
It is documented here : https://prazdevs.github.io/pinia-plugin-persistedstate/guide/migrating.html#breaking-changes

If you really need to use this feature, you may want to use 2.x version.

**Comment by jejacks0n** [comment]
Nope, that's the answer I was looking for. I don't need it, but having it would allow me to reduce the size of the overall data in the package. Thank you!
