### ISSUE TITLE
forcing hydration from afterRestore hook

### ISSUE THREAD

**Issue by eltorio** [prazdevs/pinia-plugin-persistedstate#160]
HI,
Thanks for this plugin,
I try to force hydration base on a store value, so my main idea is to test my value in afterRestore hook
```ts
afterRestore: (ctx) => {
      const storeTimestamp = (ctx.store as any).storeTimestamp as number;
      if ( storeTimestamp + VAL > new Date().getTime() ){
        // force hydration
       ctx.store.$hydrate({ runHooks: false })
     }
}
```
I tried to use the useStore() there with same result
I do not have (yet) $hydrate in afterRestore hook elsewhere there is no problem I can use $hydrate

**Comment by prazdevs** [comment]
Hi could you please stick to the issue template, and provide all the infos/reproduction needed ? thanks.

**Comment by eltorio** [comment]
sure but I wasn't sure it was an issue rather than a misunderstand from myself

**Comment by eltorio** [comment]
sure
