### ISSUE TITLE
Declaring persist in composition API

### ISSUE THREAD

**Issue by c-lees** [prazdevs/pinia-plugin-persistedstate#163]
### Describe the bug

Hi - this may well not be a bug - apologies in advance!

I'm trying to use this great plugin with the composition API but I don't see how to specify the persist options in the composition API. Would it be possible to include an example in the guide documentation please?

### Reproduction

const persistOpts = {     key: 'current_user_profile',     storage: localStorage,     paths: ['profile', 'authToken', 'lastSuccessfulCheckAuthTokenSecs', 'lastProfileRefreshSecs']   } followed by including persist: persistOpts in the return() doesn't seem to work

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Memory: 6.49 GB / 15.92 GB
  Binaries:
    Node: 18.8.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.18.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 108.0.5359.125
    Edge: Spartan (44.22621.963.0), Chromium (108.0.1462.54)
    Internet Explorer: 11.0.22621.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by prazdevs** [comment]
Hi, I need a proper reproduction repo (stackblitz or a gh repo) to consider the issue.
However i also recommend referring to the documentation over at https://prazdevs.github.io/pinia-plugin-persistedstate/guide/#usage where an example with composition is given as well.

Closing this for now, if you still don't have it working, please provide a proper repo, and i'll look into it :)

**Comment by c-lees** [comment]
Thank you @prazdevs - the example sorted it for me - sorry I didn't manage to find that myself!
