### ISSUE TITLE
ERROR  Missing "./nuxt" export in "pinia-plugin-persistedstate" package

### ISSUE THREAD

**Issue by nathanchase** [prazdevs/pinia-plugin-persistedstate#166]
### Describe the bug

Using Nuxt 3 and "pinia-plugin-persistedstate": "^3.0.2", I get the error:
` ERROR  Missing "./nuxt" export in "pinia-plugin-persistedstate" package`

It works fine if I use `"pinia-plugin-persistedstate": "^2.4.0",`.

Did something change with the way this works with Nuxt 3?

See reproduction of the error: https://stackblitz.com/edit/github-mqufck?file=plugins%2Fpersistedstate.ts

### Reproduction

https://stackblitz.com/edit/github-mqufck?file=plugins%2Fpersistedstate.ts

### System Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
    Memory: 15.64 GB / 23.44 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by prazdevs** [comment]
Hi :) 
The plugin now has a full nuxt integration with a proper nuxt module!

https://prazdevs.github.io/pinia-plugin-persistedstate/frameworks/nuxt-3.html

You can find here how to use `@pinia-plugin-persistedstate/nuxt` package. :)

**Comment by nathanchase** [comment]
Thanks! I tried removing my plugin and using the new module, but then my whole app refuses to load. It puts it into a state of constantly restarting the server. Not sure why, as I can't reproduce the error in StackBlitz. Will have to do some major debugging to figure out what module it's conflicting with, or some other plugin, or code.

**Comment by prazdevs** [comment]
> Thanks! I tried removing my plugin and using the new module, but then my whole app refuses to load. It puts it into a state of constantly restarting the server. Not sure why, as I can't reproduce the error in StackBlitz. Will have to do some major debugging to figure out what module it's conflicting with, or some other plugin, or code.

Make you you only install the nuxt module, as it will install the plugin itself, maybe a clean node_modules install can help

**Comment by nathanchase** [comment]
> Make sure you only install the nuxt module, as it will install the plugin itself, maybe a clean node_modules install can help

Well, it took a reboot of my machine, and re-cloning my repo, and _**then**_ running pnpm install again and have it create a fresh lockfile - and now it works! Whew! Thanks for the suggestion.
