### ISSUE TITLE
[nuxt] Persistence/hydration won't happen if store is called in a Nuxt plugin

### ISSUE THREAD

**Issue by msoler75** [prazdevs/pinia-plugin-persistedstate#167]
### Describe the bug

When a Nuxt 3 plugin call the useStore at start, the persist fail. No message or warning is shown. 

This can cause loss of time, and headaches without knowing why it is not working and losing many hours of work  (as it happened to me).

It would be advisable (if possible) to recognize this type of situation and send a warning message to the user so that they do not initialize the store prematurely. 

```
// file /composables/failingstore.js:
import { defineStore } from "pinia";

export const useFailingStore = defineStore("failPersistStore", {
  state: () => {
    return {
      counter: 0,
    };
  },
  persist: true,
});

// file /plugins/anyplugin.js:
export default defineNuxtPlugin((nuxtApp) => {

   // using here will generate fail in persisting 
  const store = useFailingStore();

  const getCounter = () => {

    // using here will run ok
    // const store = useFailingStore();

    return store.counter;
  };

  return {
    provide: {
        getCounter,
    },
  };
});
```

Regardless, I really appreciate this pinia plugin. Thank you!

### Reproduction

https://github.com/msoler75/pinia-persist-fail-when-plugin

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 5.02 GB / 15.84 GB
  Binaries:
    Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 109.0.5414.75
    Edge: Spartan (44.19041.1266.0), Chromium (108.0.1462.76)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by prazdevs** [comment]
I started looking into it and it's really bizarre. it's very interesting, because just declaring `const store = useStore()` in a plugin, and nothing else, just makes it so the persistence plugin doesnt exist at all. I'll debug that when i get some more time to try to udnerstand

**Comment by prazdevs** [comment]
also, why are you declaring the plugin in the `nuxt.config.ts` ?
<img width="266" alt="image" src="https://user-images.githubusercontent.com/1631886/213897161-01ef348c-570e-43b3-8c22-ed94315d1667.png">

You shouldn't be adding them yourself, as the documentation suggests (https://nuxt.com/docs/guide/directory-structure/plugins).

When I remove it, the persistence and everything works perfectly fine 🤔

**Comment by msoler75** [comment]
Yes, the Nuxt 2 habit betrayed me. For me it was unpredictable that this effect would be generated. Thanks!

**Comment by prazdevs** [comment]
Closing as solved :)
