### ISSUE TITLE
I would like to provide the Chinese version of this plugin.

### ISSUE THREAD

**Issue by cloudmoonocus** [prazdevs/pinia-plugin-persistedstate#168]
### Clear and concise description of the problem

Translating document

### Suggested solution

I would like to provide the Chinese version of this plugin.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by prazdevs** [comment]
That'd be awesome to have a chinese translation since vitepress now has i18n support! Feel free to open a PR for this!

**Comment by prazdevs** [comment]
You can already draft a PR if you feel like it, I'd also like to add more language eventually, french most likely  :)

**Comment by cloudmoonocus** [comment]
> You can already draft a PR if you feel like it, I'd also like to add more language eventually, french most likely  :)

Ok, I have translated all of them. Today I will draft a PR after proofreading and revising each paragraph one by one.

**Comment by prazdevs** [comment]
resolved in #169 👍
