### ISSUE TITLE
Support async storage libraries like localforage

### ISSUE THREAD

**Issue by sukiejosh** [prazdevs/pinia-plugin-persistedstate#17]

**Comment by prazdevs** [comment]
Hi, I'll try to see what I can do for this :)

**Comment by prazdevs** [comment]
I don't think this can be considered for now. The plugin hooks onto pinia's `$subscribe` that watches mutations and not actions, so whatever we do should also be synchronous. If you're looking to integrate async operations withing the store, you can consider subscribing to actions (more [in the pinia docs](https://pinia.vuejs.org/core-concepts/actions.html#subscribing-to-actions)) and do so in a more "manual" way. 

I'll be closing this for now, feel free to reopen if you have a _proper_ solution to implement. Thanks!
