### ISSUE TITLE
nativescript support

### ISSUE THREAD

**Issue by u007** [prazdevs/pinia-plugin-persistedstate#170]
### Clear and concise description of the problem

nativescript does not support localStorage, 
therefore viable option is to use application-settings on nativescript

im not sure how to detect if current platform is nativescript, perhaps a option when initializing 
or https://github.com/EddyVerbruggen/nativescript-secure-storage

### Suggested solution

example of application-settings here

https://stackoverflow.com/questions/39463157/is-there-localstorage-in-nativescript

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by prazdevs** [comment]
Hi I am trying to understand, but I dont properly see the issue. You can use a custom storage 🤔 
Also this plugin is completely agnostic of the technology/framework you use with it (quasar, nuxt...)

Have you tried using a custom storage with the `storage` option ?

**Comment by u007** [comment]
thank you, i got it working with custom Storage,

```app.ts

import { StorageLike } from 'pinia-plugin-persistedstate';
import { SecureStorage } from '@nativescript/secure-storage';

// instantiate the plugin
let secureStorage = new SecureStorage();
secureStorage.isFirstRun().then((isFirst: boolean) => {
  console.log('isFirstRun', isFirst);
  // if isFirst is true, do whatever you like
});
export const NSPersistedStateStorage: StorageLike = {
  setItem(key, value) {
    console.log('setItem', key, value);
    return secureStorage
      .set({
        key,
        value,
      })
      .then((success: any) => console.log('Successfully set a value? ' + success));
  },
  getItem(key) {
    var value = secureStorage.getSync({
      key,
    });
    return value;
  },
};

// app codes here....

const pinia = createPinia();
const persistedPinia = createPersistedState({
  storage: NSPersistedStateStorage,
});
pinia.use(persistedPinia);
```
