### ISSUE TITLE
Set the validity period of data

### ISSUE THREAD

**Issue by aolsx** [prazdevs/pinia-plugin-persistedstate#171]
### Clear and concise description of the problem

Set the time limit for data storage. If it exceeds the time limit, execute a specific function to load the data of the server. It can save traffic and server resource consumption.

### Suggested solution

No response

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by prazdevs** [comment]
Hi, this issue has been talked about (kind of) in #21 and I think it is out of the scope of the plugin. Validity and data being stale is either a job for the storage you choose, or some function within the app itself to check validity.

Validity checks directly in the plugin would involve a lot of side effects and complexity when it can be handled by external tools.

I'd suggest looking into session storage or cookies or you could also create a custom storage that checks data staleness and returns null if it is.
