### ISSUE TITLE
Does not work.

### ISSUE THREAD

**Issue by uwejan** [prazdevs/pinia-plugin-persistedstate#173]
### Describe the bug

Just installed for my nuxt3 app, after following the instructions very carefully, and creating my store, it does not show up in the dev tools. Any idea?
```
export const useStore = defineStore("main", {
  state: () => {
    return {
      someState: "hello pinia",
    };
  },
  persist: true,
});
```
```
//nuxt.config.ts
  modules: ["@vueuse/nuxt", "@pinia/nuxt", "@pinia-plugin-persistedstate/nuxt"],
  pinia: {
    autoImports: ["defineStore", "definePiniaStore", "acceptHMRUpdate"],
    disableVuex: true,
  },
  alias: {
    pinia:
      process.env.NODE_ENV === "production"
        ? "/node_modules/pinia/dist/pinia.mjs"
        : "/node_modules/@pinia/nuxt/node_modules/pinia/dist/pinia.mjs",
  },
    piniaPersistedstate: {
    debug: true,
    storage: "localStorage",
  },

  ```
  
![Screenshot-20230205005345-711x161](https://user-images.githubusercontent.com/20250935/216791269-e6f2add2-2160-413f-9733-562c9f071b26.png)

### Reproduction

will do

### System Info

```Shell
chrom,firefox [latest]
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by 50l3r** [comment]
I have the same problem.

@pinia-plugin-persistedstate/nuxt: ^1.0.0
pinia-plugin-persistedstate: ^3.0.2

**Comment by prazdevs** [comment]
I cant consider looking into it without a proper reproduction.

**Comment by rmcmk** [comment]
Same problem, latest nuxt, not working correctly

**Comment by prazdevs** [comment]
I juste created a Nuxt project right now and it works fine 🤔 
https://github.com/prazdevs/pinia-bug-reprod-1

**Comment by Albermonte** [comment]
> I juste created a Nuxt project right now and it works fine 🤔 https://github.com/prazdevs/pinia-bug-reprod-1

I had the same problem, seems like persistence only works if the store is in the composables folder, but this is not explained in your documentation

**Comment by prazdevs** [comment]
I tried with a store in a `stores` folder, and it still works ? 
https://github.com/prazdevs/pinia-bug-reprod-1/tree/stores-folder

Since its not in `composables` or `utils` you need to explicitely import it but it does work 🤔

**Comment by uwejan** [comment]
I am not able to verify right now. Lets keep it open for some days, will report back. Thank you.

**Comment by fosterdouglas** [comment]
Has anyone happened to look into this? Using:

Nuxt 3.2.0
@pinia/nuxt 0.4.6
@pinia-plugin-persistedstate/nuxt 1.0.0
pinia-plugin-persistedstate 3.0.2

The issue (for me anyway) seems to be stemming from inside a persisted-state composable:

`  nuxtApp.vueApp.use(
    pinia.use(
      createPersistedState({
        storage: localStorage,
      })
    )
  )`

Getting various issues with that line depending on setup, but most commonly seeing 'Cannot set property $pinia of #<Object> which has only a getter.'

Let me know if anyone has any luck with this !

**Comment by prazdevs** [comment]
> I cant consider looking into it without a proper reproduction.

Again, a proper reproduction repo is essential for me (and anyone interested in helping) to look into the issue. 
For usage with nuxt you should refer to this part of the documentationt : https://prazdevs.github.io/pinia-plugin-persistedstate/frameworks/nuxt-3.html

Tried again this morning, with different storages and it worked with:
```json
  "devDependencies": {
    "@pinia-plugin-persistedstate/nuxt": "^1.0.0",
    "@pinia/nuxt": "^0.4.6",
    "nuxt": "^3.2.0",
    "pinia": "^2.0.30"
  }
```

**Comment by uwejan** [comment]
> > I cant consider looking into it without a proper reproduction.
> 
> Again, a proper reproduction repo is essential for me (and anyone interested in helping) to look into the issue. For usage with nuxt you should refer to this part of the documentationt : https://prazdevs.github.io/pinia-plugin-persistedstate/frameworks/nuxt-3.html
> 
> Tried again this morning, with different storages and it worked with:
> 
> ```json
>   "devDependencies": {
>     "@pinia-plugin-persistedstate/nuxt": "^1.0.0",
>     "@pinia/nuxt": "^0.4.6",
>     "nuxt": "^3.2.0",
>     "pinia": "^2.0.30"
>   }
> ```

All good. I think this can be closed.

**Comment by prazdevs** [comment]
Cool 👍  if anyone still experiences issues or doesn't understand something, feel free to open an issue :)

**Comment by prashantnirgun** [comment]
I faced a similar issue can any one help me I am using nuxt 3 
```
//stores/global.js
import { defineStore } from "pinia";
export const useGlobal = defineStore("global", {
  state: () => {
    return {
      user: null,
      token: null,
      isUserLoggedIn: false,
    };
  },
  persist: {
    storage: persistedState.localStorage,
  },
});
```
packages.json
```
"devDependencies": {
    "dotenv": "^16.0.3",
    "nuxt": "3.0.0"
  },
  "dependencies": {
    "@mdi/font": "^7.1.96",
    "@pinia-plugin-persistedstate/nuxt": "^1.0.0",
    "@pinia/nuxt": "^0.4.6",
    "@vee-validate/rules": "^4.7.3",
    "pinia": "^2.0.29",
    "sass": "^1.56.2",
    "vee-validate": "^4.7.3",
    "vuetify": "^3.1.2",
    "yup": "^0.32.11"
  }
```
nuxt.config.ts
```
modules: [
    "@pinia/nuxt", // needed
    "@pinia-plugin-persistedstate/nuxt",
  ],
```
Here are screen shoot of devtool, if you refresh the page this get pinia empty.

01 application pane [localstorage](https://postimg.cc/jWptqJ3n) 
02 Vue Devtool [Pinia](https://postimg.cc/LJfMCs8H)

**Comment by prazdevs** [comment]
hi @prashantnirgun i'll need a proper reproduction repo so i can look into it 👍

**Comment by Draccano** [comment]
I have Nuxt bridge setup and using plugin in old way did not work. So what worked for me was
```
import { createPinia } from 'pinia';
import piniaPluginPersistedstate from 'pinia-plugin-persistedstate';
import { defineNuxtPlugin } from '#app';

const pinia = createPinia();
pinia.use(piniaPluginPersistedstate);

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.$pinia.use(piniaPluginPersistedstate);
});
```
