### ISSUE TITLE
Make persistence possible with setup stores

### ISSUE THREAD

**Issue by gluebi** [prazdevs/pinia-plugin-persistedstate#174]
### Clear and concise description of the problem

There currently is no way to persist state when using setup stores like this: https://pinia.vuejs.org/core-concepts/#setup-stores

### Suggested solution

Make it possible to enable persistence like this:

```
export const useStore = defineStore('store', () => {
      ...
     return {
        persist: true
     }
}
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by prazdevs** [comment]
Hi :)

In the documentation there is some info on how you can enable persistence with setup-syntax stores :)
https://prazdevs.github.io/pinia-plugin-persistedstate/guide/#usage

Here's the code : 
```ts
import { defineStore } from 'pinia'

export const useStore = defineStore(
  'main',
  () => {
    const someState = ref('hello pinia')
    return { someState }
  },
  {
    persist: true,
  },
)
```

**Comment by gluebi** [comment]
That was fast, thank you so much!

**Comment by prazdevs** [comment]
No problem :)
