### ISSUE TITLE
pinia-plugin-persistedstate Does the product support encryption?

### ISSUE THREAD

**Issue by caihuattkl** [prazdevs/pinia-plugin-persistedstate#177]
### Clear and concise description of the problem

pinia-plugin-persistedstate Does the product support encryption?

### Suggested solution

pinia-plugin-persistedstate Does the product support encryption?

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by prazdevs** [comment]
Hi, encryption is let to the user to implement.

You can use any `storage` you want as long as they are synchronous, so you can use encypted storages.

**Comment by prazdevs** [comment]
I found an example here https://github.com/prazdevs/pinia-plugin-persistedstate/issues/60

Feel free to look into closed issues as there as some examples. Closing this for now. If it's not enough, feel free to reopen.
