### ISSUE TITLE
typescript 中如何处理解决这个报错呀

### ISSUE THREAD

**Issue by each1026** [prazdevs/pinia-plugin-persistedstate#178]
### Describe the bug

RT
![ error ](https://cdn.jsdelivr.net/gh/each1026/ImageSave@master/image-2023-03-14-AR6r3Z.png)

### Reproduction

rt

### System Info

```Shell
rt
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by prazdevs** [comment]
Hi :) I don't understand Chinese so it's kinda hard for me to read that. But I may have an idea, can you provide a proper reproduction repo so I can have a look and help ?

**Comment by slavco86** [comment]
I think the point being here is that it doesn't seem to be supported in Typescript projects.
I have the same issue.
Been upgrading my project from V2 to 
V3 and fighting TS at the moment

![Screenshot 2023-03-28 at 13 25 20](https://user-images.githubusercontent.com/25765449/228235432-3a931319-a38a-4d9c-97d2-0827363d83f1.png)

**Comment by andrey-hohlov** [comment]
I had this issue after upgrading to v3.
But only in VS Code. True type checking (`vue-tsc --noEmit` in my case) shows no errors.
Then I restart VS Code and errors gone.

**Comment by prazdevs** [comment]
Closing this as stale and some people seem to have it working too :)

**Comment by AuroraTea** [comment]
When utilizing this component in Nuxt3, the same issue arises.

```
No overload matches this call.
  Overload 1 of 3, '(id: "auth", options: Omit<DefineStoreOptions<"auth", {}, {}, {}>, "id">): StoreDefinition<"auth", {}, {}, {}>', gave the following error.
    Object literal may only specify known properties, and 'persist' does not exist in type 'Omit<DefineStoreOptions<"auth", {}, {}, {}>, "id">'.
  Overload 2 of 3, '(id: "auth", storeSetup: () => unknown, options?: DefineSetupStoreOptions<"auth", _UnwrapAll<Pick<unknown, never>>, Pick<unknown, never>, Pick<unknown, never>> | undefined): StoreDefinition<...>', gave the following error.
    Object literal may only specify known properties, and 'persist' does not exist in type '() => unknown'.ts(2769)
(property) persist: {
    storage: any;
}
```
