### ISSUE TITLE
how to merge many k-v in local storage?

### ISSUE THREAD

**Issue by yzj-again** [prazdevs/pinia-plugin-persistedstate#179]
### Describe the bug

In pinia's store, I have many warehouses, and I want to store them all in local storage. Local storage will have many key-values. How to merge these k-v?

from

![image](https://user-images.githubusercontent.com/28704447/225157829-280db364-a4b2-4ae0-b735-ce473388b0d7.png)

to 

![image](https://user-images.githubusercontent.com/28704447/225157917-160fba62-65ec-46a2-8a74-e57b6b0f47cc.png)

### Reproduction

null

### System Info

```Shell
"pinia": "^2.0.33",
"pinia-plugin-persistedstate": "^3.1.0",
"vue": "^3.2.13",
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by prazdevs** [comment]
Hi, the plugin follows pinia modularity by having one key-value per store.
It should be doable with a custom Storage maybe so you set keys yourself and merge things? But it could affect performance

**Comment by yzj-again** [comment]
yeah,i kown

**Comment by prazdevs** [comment]
That's all I can do from here 🤔 
Is there a reason why having multiple k-v is an issue ?

**Comment by prazdevs** [comment]
Closing as stale.
