### ISSUE TITLE
A problem with using this plugin outside of other files

### ISSUE THREAD

**Issue by Vvaraz** [prazdevs/pinia-plugin-persistedstate#183]
I tried to use store in the axios interceptor, but the console reported an error: "Did you forget to install pinia?"
```typescript
// request.ts
import {useUserInfoStore} from '@/store/user

const userInfo = useUserInfoStore()
axios.interceptors.request.use(config => {
                      ...
  if (userInfo .profile.token) {
    config.headers.Authorization = 'Bearer' + userserInfo.profile.token
  }
  return config
}, error => {
  return Promise.reject(error)
})
```
Then I rewrite according to the document according and manually provide pinia to the useStore() function.
[https://pinia.vuejs.org/core-concepts/outside-component-usage.html](url) 
The error disappears, but the functionality of this plugin has failed. I hope someone can help solve this problem. Thanks!
```typescript
// store/index.ts
import {createPinia} from "pinia";
import piniaPluginPersistedstate from "pinia-plugin-persistedstate";

const pinia = createPinia()
pinia.use(piniaPluginPersistedstate)
export { pinia }
```
```typescript
// main.ts
import pinia from '@/store'
     ...
createApp(App).use(pinia).mount('#app')
```
```typescript
// request.ts
import {useUserInfoStore} from '@/store/user
import {pinia} from '@/store'

const userInfo = useUserInfoStore(pinia)
axios.interceptors.request.use(config => {
                      ...
  if (userInfo .profile.token) {
    config.headers.Authorization = 'Bearer' + userserInfo.profile.token
  }
  return config
}, error => {
  return Promise.reject(error)
})
```
This issue is translated through Google. I'm sorry if the sentence is not smooth!

**Comment by prazdevs** [comment]
Hi, can you provide a complete repo so I can play with it and try to see what is wrong ?

**Comment by mxismean** [comment]
+1, I've encountered the same issue.
I tried using the pinia-plugin-persist plugin, but I also encountered this issue.

The issue occurs whenever the `useStore()` method is passed the `pinia` instance， `useStore(pinia) `,The persistence storage stops working. @prazdevs

**Comment by prazdevs** [comment]
As stated, I cannot work on that without a proper reproduction. 
If people bypass the issue template checks and don't provide a reproduction repo, I will most likely not look into the issue as I'm very busy.
