### ISSUE TITLE
Question: Allow user to specify whether to persist store

### ISSUE THREAD

**Issue by binabik** [prazdevs/pinia-plugin-persistedstate#185]
Hi,

I'd like my users to be able to toggle a switch/checkbox to optionally store the state. I've looked through the code and can't really see how to do that. 

My naive assumption was to do this:
```
xport const useStore = defineStore("main", {
  state: () => ({
    formData: {},
    persistStore: false,
  }),
  persist: this.persistStore
});
```

But it seems that I cannot access the state's `persistStore` variable in any form or fashion. 

Any suggestions? Thanks!

**Comment by prazdevs** [comment]
Hi, this is kind of intended, as persistence is called on instantiation, and state isnt available at the time.
If you really need that, you could add a combination of a custom Serializer and Storage so that it doesnt store anything given a special state.

**Comment by binabik** [comment]
it was a bit of work to get it working, but this is what i came up with:

`const switchableLocalStorage = {
  setItem(key, state) {
    var localState = JSON.parse(state);
    const localStoreData = JSON.parse(localStorage.getItem(key));
    if (localState.persistStore || (localStoreData && localStoreData.persistStore)) {
      return localStorage.setItem(key, JSON.stringify(localState));
    }
  },
  getItem(key) {
    if (localStorage.getItem(key) 
          && JSON.parse(localStorage.getItem(key)).persistStore) {
      return localStorage.getItem(key);
    }
  }
}`
