### ISSUE TITLE
Caching object array data will not work in production

### ISSUE THREAD

**Issue by XiaoBaiClassmate** [prazdevs/pinia-plugin-persistedstate#186]
### Describe the bug

state.visitedViews Manage vue-router routes

in production error:
```
index-cd0e0ab3.js:109 
        
       TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property '_' -> object with constructor 'Object'
    |     property 'vnode' -> object with constructor 'Object'
    |     ...
    |     property 'ref' -> object with constructor 'kq'
    --- property '_rawValue' closes the circle
    at Object.stringify [as serialize] (<anonymous>)
    at Fk (index-cd0e0ab3.js:109:38887)
    at a.$subscribe.detached (index-cd0e0ab3.js:109:39669)
    at index-cd0e0ab3.js:5:741
    at Array.forEach (<anonymous>)
    at Mf (index-cd0e0ab3.js:5:729)
    at Proxy.C (index-cd0e0ab3.js:5:1894)
    at Proxy.addVisitedView (index-cd0e0ab3.js:58:12144)
    at Proxy.<anonymous> (index-cd0e0ab3.js:5:2239)
    at d (index-cd0e0ab3.js:108:202154)
```

**Development environment is fine**

eg：
```
//view is vue-router route 
addVisitedView(view){
      let toArrys = cloneDeep(this.visitedViews);
      if (toArrys.some((v) => v.path === view.path)) return;
      if (toArrys.length >= tagsViewNum) {
        toArrys.pop();
        toArrys.push(
          Object.assign({}, view, {
            title: view.meta.title || "no-name",
          })
        );
      } else {
        toArrys.push(
          Object.assign({}, view, {
            title: view.meta.title || "no-name",
          })
        );
      }
      this.$patch((state: any) => {
        state.visitedViews = toArrys;
      });
}
```

### Reproduction

3.1.0

### System Info

```Shell
System:
    OS: Windows 10 10.0.17763
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Memory: 8.50 GB / 15.60 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    chrome Explorer: 111.0.5563.65
```

### Used Package Manager

pnpm

**Comment by prazdevs** [comment]
Hi, i will need more info on the probleme and a proper reproduction repository to help you with this issue :)

**Comment by XiaoBaiClassmate** [comment]
@prazdevs hi,Discover the cause of the problem:
1.state management The router instance (route from the component) is stored in the state, which has a circular reference
2.With a circular reference in the state, the plugin needs to execute JSON. stringify to convert the state data to a string and store it in the browser's local storage.

**Comment by XiaoBaiClassmate** [comment]
@prazdevs Hello, maybe what I described is not correct. In the production environment, I enabled debug of the plugin, and the above error message appeared, the plugin cannot cache the route instance.

**Comment by prazdevs** [comment]
I cannot really help without a proper reproduction but suppose things.

The problem lies in the fact that when serializing back what is stored (ucins JSON.parse), a circular reference is found (object referring to itself). This is what you may want to investigate, what causes this.

**Comment by XiaoBaiClassmate** [comment]
@prazdevs Thank you very much for your reply. I find the problem is that the data stored in the matched attribute of the vue-router route instance has a circular reference, and it can be saved normally after removing the matched attribute.

**Comment by prazdevs** [comment]
Did you manage to solve the problem now ? :)

**Comment by XiaoBaiClassmate** [comment]
@prazdevs Fix the problem.Removing match  attributes in route works just fine

**Comment by prazdevs** [comment]
Cool ! closing this for now. 🎉
