### ISSUE TITLE
store does not update

### ISSUE THREAD

**Issue by hamedg68** [prazdevs/pinia-plugin-persistedstate#188]
### Describe the bug

If in a store I want to update two items and do them in different ways for example first with **_patch_**  and the other directly with own state, the second state does not update, just first state updated. 

Infact I want to change part of the object in second state in the example but the first state changed and the second one does not change in local storage while the state itself changed in pinia!

### Reproduction

https://stackblitz.com/github/hamedg68/test-pinia-persist

### System Info

```Shell
Browser
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by prazdevs** [comment]
i'd guess this is kinda related to #52 and some mutations not making it on the first call 🤔

**Comment by prazdevs** [comment]
Closing this as duplicate for the sake of clarity and maintenance, also this is not _really_ a bug from the plugin itself, but depends a lot on pinia. thanks :)
