### ISSUE TITLE
Not persisting if store is used in plugin with Nuxt 3

### ISSUE THREAD

**Issue by ahmad-afiquddin** [prazdevs/pinia-plugin-persistedstate#190]
### Describe the bug

Trying to use store in a plugin but I found out that states do not persist when a store is used in a plugin with Nuxt 3. When removed from plugin, persist works. Followed nuxt 3 doc to use pinia in plugin [nuxt 3 doc](https://nuxt.com/docs/migration/configuration#vuex)

```
// store/test.ts

export const useTestStore = defineStore('test-store', {
  state: () => ({
    count: 0,
  }),
  actions: {
    addCount() {
      this.count++;
    },
  },
  persist: {
    storage: persistedState.localStorage,
  },
});
```

```
// plugin/store.ts
export default defineNuxtPlugin(({ $pinia }) => {
  return {
    provide: {
      store: useTestStore($pinia),
    },
  };
});
```

### Reproduction

https://stackblitz.com/edit/nuxt-starter-lvetcm?file=plugins%2Fstore.ts,nuxt.config.ts,pages%2Findex.vue,store%2Ftest.ts

### System Info

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by GaoNeng-wWw** [comment]
same

**Comment by prazdevs** [comment]
Hi, I looked into it, and you should **not** declare your plugin in the `nuxt.config.ts` as specified in the nuxt docs https://nuxt.com/docs/guide/directory-structure/plugins

Just remove it, and Nuxt will find it and the plugin will also work with persistence

**Comment by GaoNeng-wWw** [comment]
> 嗨，我研究了一下，您**不应该**按照 nuxt 文档中的规定声明您的插件 https://nuxt.com/docs/guide/directory-structure/plugins`nuxt.config.ts`
> 
> 只需删除它，Nuxt就会找到它，插件也可以持久化地工作

Problem solved, Thanks!

**Comment by GaoNeng-wWw** [comment]
> Hi, I looked into it, and you should **not** declare your plugin in the `nuxt.config.ts` as specified in the nuxt docs https://nuxt.com/docs/guide/directory-structure/plugins
> 
> Just remove it, and Nuxt will find it and the plugin will also work with persistence

[https://stackblitz.com/edit/nuxt-starter-5kqjqh?file=plugins%2Fstore.ts,nuxt.config.ts,pages%2Findex.vue,store%2Ftest.ts](https://stackblitz.com/edit/nuxt-starter-5kqjqh?file=plugins%2Fstore.ts,nuxt.config.ts,pages%2Findex.vue,store%2Ftest.ts)

look like it's solved❤

**Comment by prazdevs** [comment]
Nice ! Considering it closed ! 🎉

**Comment by jeanmatthieud** [comment]
I have the same issue with Nuxt2, do you have a workaround ?
