### ISSUE TITLE
[Nuxt 3 client] State loaded too slow ?

### ISSUE THREAD

**Issue by GreyXor** [prazdevs/pinia-plugin-persistedstate#191]
### Describe the bug

Hello,
this bug only happens with `nuxt generate`. I don't have this issue with `nuxt dev`.

The state is correctly loaded in pinia store. But the icon displayed is not the one that should be there

So if `rail` is true then the icon should be a flower and not the house.
I have this behavior with `nuxt dev` i'm loading the app and the values are all correct.
![image](https://user-images.githubusercontent.com/79602273/231104041-b1aaf024-f471-4dae-bf1a-9d95ec225bc0.png)
![image](https://user-images.githubusercontent.com/79602273/231104075-5ab473ec-2603-43ae-b748-af3dc05dcbe4.png)

But then, with `nuxt generate` I don't have the correct icon, the text is still correct tho.
![image](https://user-images.githubusercontent.com/79602273/231104216-f548bdb1-f003-4285-9e45-f7e53b3baad8.png)

### Reproduction

https://github.com/GreyXor/bugpiniapers

### System Info

```Shell
System:
    OS: Linux 6.3 Arch Linux
    CPU: (16) x64 AMD Ryzen 7 PRO 6850U with Radeon Graphics
    Memory: 21.80 GB / 30.13 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 18.15.0 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.19.2 - /usr/bin/npm
  Browsers:
    Firefox: 114.0a1 (2023-04-10) (64-bit)
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by munierujp** [comment]
I am facing a similar problem.

**Comment by prazdevs** [comment]
Hi, while the problem was a thing when the issue was created, I tried again today with all dependencies updated and it seems to be working fine with `generate` ! :)

Closing this for now. If you still have problems or questions, let me know and feel free to reopen!
