### ISSUE TITLE
Global Option Serializer 

### ISSUE THREAD

**Issue by floriankapaun** [prazdevs/pinia-plugin-persistedstate#192]
### Clear and concise description of the problem

Since v3.0.0 the [paths 'array syntax isn't supported anymore](https://github.com/prazdevs/pinia-plugin-persistedstate/releases/tag/v3.0.0) – which btw was a good choice considering the hilarious complexity of my implementation back then 😄.

I'm now using a custom [serializer](https://prazdevs.github.io/pinia-plugin-persistedstate/guide/config.html#serializer) to exclude specific properties before serializing my state.

While doing so I came up with a custom serializer that I'd like to apply globally.

### Suggested solution

```js 
// nuxt.config.ts
import { StateTree } from 'pinia';
import { stringify, parse } from 'zipson';

export default defineNuxtConfig({
  ⋮
  piniaPersistedstate: {
    serializer: {
      serialize: (state: StateTree): string => serialize(state),
      deserialize: (state: string): StateTree => parse(state)
    }
  }
});
```

### Alternative

Currently I'd be able to achieve this by creating a utility:

```js
// utils/pinia-serializer.ts
import { StateTree } from 'pinia';
import { stringify, parse } from 'zipson';

const serializer = {
  serialize: (state: StateTree): string => serialize(state),
  deserialize: (state: string): StateTree => parse(state)
};

export default serializer;
```

And then use this utility to specify the serialization for each of my stores:

```js
// stores/example.ts
import { defineStore } from 'pinia';
import serializer from '~~/utils/pinia-serializer';

export const useExampleStore = defineStore({
  ⋮
  persist: {
    serializer
  }
});
```

### Additional context

I'd be happy to try and work on a pr for this feature if you wish.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by prazdevs** [comment]
For the same reason as #195 Nuxt won't allow that. There is even a small line in the docs about that https://nuxt.com/docs/guide/going-further/runtime-config#serialization

Will have to find another way of making it work 🤔

**Comment by prazdevs** [comment]
merged all similar issues in the one quoted above :)
