### ISSUE TITLE
Weird Typescript issue

### ISSUE THREAD

**Issue by rudolfbyker** [prazdevs/pinia-plugin-persistedstate#193]
### Describe the bug

When I use `persist: { … }` AND I have a shorthand function in my store's return value, I get a typescript error. I can make it go away by doing any one of the following:

- use `whatever: () => { … }` instead of `whatever() { … }` (I'll do this for now)
- use `persist: true` instead of `persist: { … }` (But I need the advanced options)
- use `defineStore<"example", SS>` where I specify SS explicitly (Too tedious)

```ts
import { defineStore } from "pinia";
import { ref } from "vue";

const useExampleStore = defineStore(
  "example",
  () => {
    return {
      count: ref<number>(0),
      // The TS error goes away if I use `whatever: () => { … }` instead of `whatever() { … }`.
      // whatever: () => {
      //   console.log("whatever");
      // },
      whatever() {
        console.log("whatever");
      },
    };
  },
  {
    // The TS error goes away if I use `persist: true` instead of `persist: { … }`.
    // persist: true,
    persist: {
      afterRestore() {
        console.log("afterRestore");
      },
    },
  }
);

const foo = useExampleStore();

// TS2339: Property 'count' does not exist on type 'Store"example", _UnwrapAll  >, Pick , Pick >'.
console.log(foo.count);
```

To see the Typescript error, run:

```shell
yarn tsc --noEmit
```

Happy to close this if my usage is simply incorrect, but this looks buggy to me.

### Reproduction

https://github.com/rudolfbyker/repro-ts-pinia-plugin-persistedstate

### System Info

```Shell
System:
    OS: Linux 5.15 Linux Mint 21.1 (Vera)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1195G7 @ 2.90GHz
    Memory: 48.61 GB / 62.55 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.14.0 - ~/.nvm/versions/node/v18.14.0/bin/node
    Yarn: 3.4.1 - ~/.nvm/versions/node/v18.14.0/bin/yarn
    npm: 9.4.2 - ~/.nvm/versions/node/v18.14.0/bin/npm
  Browsers:
    Chromium: 111.0.5563.64
    Firefox: 112.0
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by prazdevs** [comment]
Mmmh this is probably some odd error with type resolution within pinia.
My recommendation would be to declare function in the plugin as arrow functions and it works :  
```ts
persist: {
  afterRestore:() => {
    console.log("afterRestore");
  },
},```
