### ISSUE TITLE
Can global key be configured in nuxt.config.ts

### ISSUE THREAD

**Issue by krissss** [prazdevs/pinia-plugin-persistedstate#195]
### Clear and concise description of the problem

`createPersistedState` support config global key，but current not exit in `nuxt.config.ts`

### Suggested solution

in `defineNuxtPlugin` add key ?

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by prazdevs** [comment]
Rn there's a slight issue in the way config is passed from `nuxt.config.ts` to runtime that won't allow passing functions to be executed at runtime (without `exec`) 🤔  May try to find a solution when i get some time

**Comment by prazdevs** [comment]
merged all similar issues in the one quoted above :)
