### ISSUE TITLE
Plugin is not storing data from store

### ISSUE THREAD

**Issue by cboelter** [prazdevs/pinia-plugin-persistedstate#196]
### Describe the bug

Hi,

I'm trying to use your plugin to store the data of my store persistent. I've follwed the steps from the documentation and read some tickets here in github. But it still will not persist my data after changing a few things in the store :-( Maybe you have some hints for me :-) For testing purpose I added a small snippet to my `main.ts`.

```typescript
const app = createApp(App);
const pinia = createPinia();
pinia.use(createPersistedState({auto: true}));

export const useUserStore = defineStore({
  id: 'user',
  state: () => { return { name: '' }},
})

const testStore = useUserStore(pinia);
testStore.name = 'TEST';

app.use(pinia);
```

After reloading the app nothing is stored to the localStorage. I hope thats okay that I have not created a separate reproduction for that small snippet.

### Reproduction

https://github.com/prazdevs/pinia-plugin-persistedstate/issues/196

### System Info

```Shell
App:
     
    "pinia": "^2.0.23",
    "pinia-plugin-persistedstate": "3.0.2",
    "vue": "^3.2.41",
    "vue-i18n": "^9.2.2",
    "vue-number-format": "^1.3.1"```
 System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 555.64 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.0 - /opt/homebrew/opt/node@16/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.3 - /opt/homebrew/opt/node@16/bin/npm
  Browsers:
    Chrome: 112.0.5615.137
    Firefox: 112.0.1
    Safari: 16.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by prazdevs** [comment]
🤔 that reproduction is kinda poor and not helping much, but just inverting the order of things, i can get it working:

```ts
import { createApp } from 'vue'
import { createPinia, defineStore } from 'pinia'
import { createPersistedState } from 'pinia-plugin-persistedstate'

import App from './App.vue'

const app = createApp(App)
const pinia = createPinia()
pinia.use(createPersistedState({ auto: true }))

export const useUserStore = defineStore({
  id: 'user',
  state: () => { return { name: '' }},
})

app.use(pinia)
app.mount('#app')

const testStore = useUserStore(pinia)
testStore.name = 'TEST'
```

**Comment by victor-ponamariov** [comment]
I have the same issue. First of all, I'm not sure if there any difference in installing the plugin using two different approaches:

```
import piniaPluginPersistedstate from 'pinia-plugin-persistedstate'
import { createPersistedState } from 'pinia-plugin-persistedstate'
```

In the docs, I saw the first option (piniaPluginPersistedstate). But after reading your answer, I tried the second option too.

That's how I set it up in main.ts:

```
import { createApp } from 'vue'
import { createPinia } from 'pinia'
import piniaPluginPersistedstate from 'pinia-plugin-persistedstate'

import App from './App.vue'
import router from './router'
import ui from './plugins/ui'

import './assets/app.css'

const app = createApp(App)

const pinia = createPinia()
pinia.use(piniaPluginPersistedstate)

app.use(createPinia())
app.use(router)
app.use(ui)

app.mount('#app')
```


This is my store:

```
import { ref, computed } from 'vue'
import { defineStore } from 'pinia'

import type User from '@/types/User'

export const useAuthStore = defineStore('auth',
  () => {
    const authenticated = ref(false)
    const currentUser = ref<User | null>(null)
    const currentRussianCompany = ref(null)
    const accessToken = ref(null)
    const module = ref('koin')

    const userRole = computed(() => currentUser.value ? currentUser.value.role.slug : null )

    return {
      authenticated,
      currentUser,
      currentRussianCompany,
      accessToken,
      module,
      userRole
    }
  },
  {
    persist: true
  }
)
```

And this is how I modify it:


```
export const login = async (credentials: Credentials) => {
  const response = await http.post('auth/login', credentials)

  authStore.authenticated = true
  authStore.currentUser = response.data.user
  authStore.accessToken = response.data.access_token
  authStore.currentRussianCompany = response.data.user.russian_company
  authStore.module = credentials.module

  return response.data
}
```

I can see that the store is being filled with the data, but there is nothing in localStorage/cookieStorage.

I use `^3.1.0` version.

**Comment by prazdevs** [comment]
@victor-ponamariov this is totally normal, you are passing the vue app a pinia without the plugin.

```ts
import { createApp } from 'vue'
import { createPinia } from 'pinia'
import piniaPluginPersistedstate from 'pinia-plugin-persistedstate'

import App from './App.vue'
import router from './router'
import ui from './plugins/ui'

import './assets/app.css'

const app = createApp(App)

const pinia = createPinia()
pinia.use(piniaPluginPersistedstate)

app.use(pinia) // CHANGE YOUR LINE FOR THIS
app.use(router)
app.use(ui)

app.mount('#app')
```

you need to pass vue (using `vue.use`) the pinia instance to which you added the plugin

**Comment by victor-ponamariov** [comment]
@prazdevs I so much appreciate your help. That's the moment when you don't notice obvious things and stuck with it for a long time.

Kudos to you!

**Comment by prazdevs** [comment]
happens to everyone 😄  glad to see it fixed!
