### ISSUE TITLE
How to use persist: true with Setup Store?

### ISSUE THREAD

**Issue by ASoldo** [prazdevs/pinia-plugin-persistedstate#197]
I am not sure how to use `persist: true` if we use Setup Store syntax
```ts
import { defineStore } from 'pinia'

export const useCounterStore = defineStore('counter', () => {
  const count = ref(0)
  const name = ref('Eduardo')
  const doubleCount = computed(() => count.value * 2)
  function increment() {
    count.value++
  }

  return { count, name, doubleCount, increment }
})
```
with options api it's like this:
```ts
import { defineStore } from 'pinia'

export const useCounterStore = defineStore('counter', {
  state: () => {
    return {
      count: 0,
    }
  },
  getters: {
    doubleCount(state) {
      return state.count * 2
    },
  },
  actions: {
    increment() {
      this.count++
    },
    $reset() {
      this.count = 0
    },
  },
  persist: true,
});

``` 
Not sure what to do, can you help me?

### Reproduction

Provided in the bug description.

### System Info

```Shell
System:
    OS: Linux 6.2 Arch Linux
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11700F @ 2.50GHz
    Memory: 4.17 GB / 15.49 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 19.9.0 - /usr/bin/node
    npm: 8.19.2 - /usr/bin/npm
  Browsers:
    Brave Browser: 111.1.49.132
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by prazdevs** [comment]
Hi :) there is an example in the documentation here https://prazdevs.github.io/pinia-plugin-persistedstate/guide/#usage

Here's what it looks like, it's a third option object: 
```ts
import { defineStore } from 'pinia'

export const useStore = defineStore(
  'main',
  () => {
    const someState = ref('hello pinia')
    return { someState }
  },
  {
    persist: true,
  },
)
```

**Comment by ASoldo** [comment]
Thank you! Works great now.
