### ISSUE TITLE
how to use in uniapp

### ISSUE THREAD

**Issue by Rain-Hsiang** [prazdevs/pinia-plugin-persistedstate#198]
### Clear and concise description of the problem

uniapp里可以么
how to use in uniapp

### Suggested solution

但是，pinia-plugin-unistorage的start太少了
[pinia-plugin-unistorage](https://github.com/dishait/pinia-plugin-unistorage)

### Alternative

[pinia-plugin-unistorage](https://github.com/dishait/pinia-plugin-unistorage)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by emeiziying** [comment]
`
import { createPersistedState } from 'pinia-plugin-persistedstate';
import { localStorage } from 'mp-storage';

const pinia = createPinia();
  pinia.use(
    createPersistedState({
      storage: localStorage,
    }),
  );

`

**Comment by prazdevs** [comment]
I don't really understand what the problem is here ? Do we have a solution ? (or multiple?)

**Comment by prazdevs** [comment]
closing as stale.
