### ISSUE TITLE
Why httpOnly true to store token with pinia-plugin-persistedstate not working?

### ISSUE THREAD

**Issue by rahul37865** [prazdevs/pinia-plugin-persistedstate#199]
I am implementing JWT Auth with Nuxt 3 (Only as Frontend), Pinia and Pinia-plugin-Persistedstate. I am storing access and refresh token on cookie. Everything works as long as i do not set `httpOnly:true` but once i set `httpOnly:true` It throws an error **_Cookie “auth” has been rejected because there is already an HTTP-Only cookie but script tried to store a new one._** Where "auth" is the name of Pinia Store i created. As error is stating that there is already an HTTP-Only cookie so i thought by default token cookies are `httpOnly:true` but when i check them its not i can see that its `httpOnly:false` and i can also access cookie via `document.cookie`. I am sharing my code sample.
**stores/auth.js**
```
import { defineStore } from 'pinia';
export const useAuthStore = defineStore(
  'auth',
  () => {
    const token = ref({}); // state
    function setToken(tk) {
      token.value = tk;
    }

    const isAuthenticated = ref(false); // state
    function setAuthenticated(aut) {
      isAuthenticated.value = aut;
    }

    // Resetting states
    function $reset() {
      token.value = {};
      isAuthenticated.value = false;
    }
    return { token, setToken, isAuthenticated, setAuthenticated, $reset };
  },

  {
    persist: {
      storage: persistedState.cookiesWithOptions({
        sameSite: 'strict',
        httpOnly: true,    // It works when i set it to false or remove this property
        secure: false,
      }),
    },
  }
);
```
**pages/index.vue**
```
<script setup>
const submitLoginForm = async () => {
  const formData = {
    username: 'kminchelle',
    password: '0lelplR',
  };
  const options = {
    method: 'POST',
    body: formData,
    headers: {
      'Content-Type': 'application/json',
    },
  };
  const { data, pending, error } = await useAsyncData(() =>
    $fetch('http://localhost:8000/api/auth/login', options)
  );
  if (data.value) {
    authStore.setToken(data.value);
    authStore.setAuthenticated(true);
    return navigateTo('/dashboard', { replace: true });
  }
};
</script>

<template>
  <h1>Login Page</h1>
  <button @click="submitLoginForm">Login</button>
</template>
```

**pages/dashboard.vue**
```
<template>
  <h1>Dashboard</h1>
</template>
```

**Comment by rahul37865** [comment]
After spending whole day to collect information regarding this issue I strongly believe this issue is not related to pinia-plugin-persistedstate. I am sorry to create this issue If possible please **delete** it. Thank You

**Comment by prazdevs** [comment]
I'd think it's more of a cookie related issue 🤔  i'll close it :) if there's something linked to the plugin feel free to reopen

**Comment by clopezpro** [comment]
> setAuthenticated

Hello, were you able to solve it? I am currently in the same situation, when I update the page I lose the data, when I use httponly=true
