### ISSUE TITLE
Simple setup store is not persisting

### ISSUE THREAD

**Issue by rudolfbyker** [prazdevs/pinia-plugin-persistedstate#204]
### Describe the bug

I used to have this working, but now nothing seems to persist, and I'm not sure what changed. I made a very simple reproduction using Vitest, to show that it does not persist. The reproduction uses the factory function with a custom storage instead of localstorage. I also tested in a browser, with localstorage, and with JSDom in Node. The Pinia store works, but it never writes anything to the persistent storage. I'm stumped.

### Reproduction

https://codesandbox.io/p/sandbox/charming-oskar-8u639v

### System Info

```Shell
On codesandbox.io, where I reproduced the problem:

  System:
    OS: Linux 5.15 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (2) x64 AMD EPYC
    Memory: 1013.48 MB / 2.01 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: 3.5.1 - /usr/local/bin/yarn
    npm: 8.15.0 - /usr/local/bin/npm
    Watchman: 20220528.183901.0 - /usr/local/bin/watchman

On my machine, where I see the same problem:

  System:
    OS: Linux 5.15 Linux Mint 21.1 (Vera)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1195G7 @ 2.90GHz
    Memory: 44.16 GB / 62.55 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.14.0 - ~/.nvm/versions/node/v18.14.0/bin/node
    Yarn: 3.4.1 - ~/.nvm/versions/node/v18.14.0/bin/yarn
    npm: 9.4.2 - ~/.nvm/versions/node/v18.14.0/bin/npm
  Browsers:
    Chromium: 113.0.5672.63
    Firefox: 113.0
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by rudolfbyker** [comment]
I get the same result when using the "options store syntax" vs. the "setup store syntax" (see https://prazdevs.github.io/pinia-plugin-persistedstate/guide/#usage ):

```ts
const useDemoStore = defineStore("demo", {
  state: () => {
    return {
      val: null as any,
    };
  },
  persist: true,
});
```

```ts
const useDemoStore = defineStore(
  "demo",
  () => {
    const val = ref<any>(null);
    return { val };
  },
  {
    persist: true,
  }
);
```

**Comment by rudolfbyker** [comment]
I just discovered this in the docs at https://pinia.vuejs.org/cookbook/testing.html

> If you have any store plugins, there is one important thing to know: plugins won't be used until pinia is installed in an App. This can be solved by creating an empty App or a fake one

That explains why it's not working in my reproduction, but I'm still seeing the same problem in my real app. I'll try to make another reproduction!

**Comment by darthf1** [comment]
Same issue here. I just installed v3.1.0 (also downgraded to v3.0.2  and v3.0.1) and nothing seems to happen at all. 

My code is quite straight forward:

```ts
import { createPinia, setActivePinia } from 'pinia'
import piniaPluginPersistedstate from 'pinia-plugin-persistedstate'

const pinia = createPinia()
pinia.use(piniaPluginPersistedstate)
setActivePinia(pinia)
```

```ts
import { acceptHMRUpdate, defineStore } from 'pinia'
import { ref } from 'vue'

const store = defineStore(
  'store',
  () => {
    ....

    return {}
  },
  {
    persist: true,
  },
)

if (import.meta.hot) {
  import.meta.hot.accept(acceptHMRUpdate(store, import.meta.hot))
}

export default store
```

Through vue-devtools I can inspect the store and see the values being set. But on inspecting the localStorage it remains empty.

**Comment by rudolfbyker** [comment]
I solved my problem. In my real app, I was relying on this plugin to be active before calling `app.use(pinia)`. But as stated in the docs:

> plugins won't be used until pinia is installed in an App

… we should not expect plugins to be active before calling `app.use(pinia)`!

**Comment by darthf1** [comment]
@rudolfbyker can you show me which lines you have changed to resolve your issue? Im not sure I understand.

**Comment by rudolfbyker** [comment]
Change this:

```js
import { createPinia, setActivePinia } from 'pinia'
import piniaPluginPersistedstate from 'pinia-plugin-persistedstate'

const pinia = createPinia()
pinia.use(piniaPluginPersistedstate)
setActivePinia(pinia)
```

… to this:

```js
import { createPinia, setActivePinia } from 'pinia'
import piniaPluginPersistedstate from 'pinia-plugin-persistedstate'
import { createApp } from 'vue';

const pinia = createPinia()
pinia.use(piniaPluginPersistedstate)

const app = createApp();
app.use(pinia);
```

… and don't do anything that relies on the plugin before calling `app.use(pinia)`;
