### ISSUE TITLE
console log a error if cookie exceed 4096 bytes

### ISSUE THREAD

**Issue by dethdkn** [prazdevs/pinia-plugin-persistedstate#205]
### Clear and concise description of the problem

Hey, i just wasted my entire day trying to figure it out why this wasnt working with my nuxt 3 app, then i just realized, it wasnt persisting because my pinia was larget than 4096 bytes.
Im not that good with cookies as you see 😭

### Suggested solution

I'm just suggesting a way to know if this happens, like a console.log or a throw error if the cookie is larger than 4096 bytes, so others like me doesnt waste time on this 😂.
Thanks Sacha!

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by prazdevs** [comment]
Hi, I do appreciate the idea, and i thought of it when splitting cookies was a thing considered in some issues here. But the thing is it boils down to [`cookie-es`](https://github.com/unjs/cookie-es) to react maybe ?
Also I cannot have an automatic size calculator in the plugin because of the potential performance issue it could bring.
However, maybe a custom `Storage` could do it ? 🤔

**Comment by prazdevs** [comment]
I'll close this as an issue on the project as it is a probleme of storage. A custom implementation of localStorage (or any synchronous storage) with check in devmode or something like that would work. However this is out of scope with the plugin itself :)

**Comment by andrevferreiraa** [comment]
Just wanted to say that this just saved me from creating a "This plugin is not working" issue. Wish I saw it sooner.

**Comment by mrleblanc101** [comment]
Yup, just faced the same issue.
It would be nice to use [object-sizeof](https://www.npmjs.com/package/object-sizeof) or something similar to check the size in dev mode only when `debug: true` is set in the config.
