### ISSUE TITLE
Exceeding localStorage limit does not throw QUOATA_EXCEEDED error by default

### ISSUE THREAD

**Issue by jl-unitedlocating** [prazdevs/pinia-plugin-persistedstate#207]
### Clear and concise description of the problem

Similar to issue https://github.com/prazdevs/pinia-plugin-persistedstate/issues/205 I spent a longer that I should have thinking I wasn't enabling or using the plugin correctly before realizing that I was attempting to store more than 5 MB in localStorage.

### Suggested solution

I think the default behavior if `debug: false` should be to `throw` the error and let the user decide how they want to handle it, particularly for QUOTA_EXCEEDED_ERR or other errors that are outside of the scope of pinia-plugin-persistedstate (so that the user knows that their issue is not being caused by the plugin). 

### Alternative

Simply throw all errors that are caught.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by prazdevs** [comment]
I think this has been brought before, this isnt a problem/issue from the plugin itself but more with storage.
Maybe using a custom storage that checks the size on `setItem` ?

**Comment by prazdevs** [comment]
unrelated to the plugin, this is a storage issue.
