### ISSUE TITLE
Pinia setup-store syntax

### ISSUE THREAD

**Issue by floZx** [prazdevs/pinia-plugin-persistedstate#212]
### Clear and concise description of the problem

I use this Pinia documentation to make my store: https://pinia.vuejs.org/core-concepts/#setup-stores
but I don't understand how to use 
`persist: {
    storage: persistedState.localStorage,
  },`
with setup-store syntax.

### Suggested solution

Add documentation to noob like me.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by floZx** [comment]
Yes but I don't understand how to put persist: true with my store write like this:
```
export const useCounterStore = defineStore('counter', () => {
  const count = ref(0)
  const name = ref('Eduardo')
  const doubleCount = computed(() => count.value * 2)
  function increment() {
    count.value++
  }

  return { count, name, doubleCount, increment }
})
```
The syntax seem to be different.

**Comment by prazdevs** [comment]
options are passed as a third parameter

```ts
export const useCounterStore = defineStore(
  'counter', () => {
    const count = ref(0)
    const name = ref('Eduardo')
    const doubleCount = computed(() => count.value * 2)
    function increment() {
     count.value++
    }

    return { count, name, doubleCount, increment }
  },
  {
    persist: true,
  },
)
```

**Comment by floZx** [comment]
Many thanks @prazdevs !

**Comment by avxkim** [comment]
I'm using:
- "@pinia/nuxt": "^0.4.11"
- "pinia-plugin-persistedstate": "^3.1.0",
With nuxt 2.16, setup-store syntax kinda doesn't work for me:

```
export const useDictionaryStore = defineStore('dictionary', () => {
  // ... rest of the code

  return {
    // ... rest of the code
  }
},
{ persist: true }
)
```

**Comment by rttmax** [comment]
Options { persist: true } as third param doesn't work for me.

**Comment by mrleblanc101** [comment]
Ahhhh, so sorry. 
I have not noticed the "tabs" in the code block.
![Screenshot 2023-10-03 at 2 46 25 PM](https://github.com/prazdevs/pinia-plugin-persistedstate/assets/17392251/62e40aec-9ace-427c-8705-c94815489b7a)

**Comment by Himanshu21git** [comment]
> Options { persist: true } as third param doesn't work for me.

@rttmax Did you find any fix for it?
