### ISSUE TITLE
Conditional cookie maxAge?

### ISSUE THREAD

**Issue by jayb0b** [prazdevs/pinia-plugin-persistedstate#213]
### Clear and concise description of the problem

There are situations where a system might want to give the user an option to "stay signed in" . 

This is possible with something like:

```
    storage: persistedState.cookiesWithOptions({
      maxAge: 365 * 24 * 60 * 60 
    }),
```

But what if they don't want to stay signed in?

### Suggested solution

I'd like to conditionally remove the maxAge and use a session cookie. Is that possible at the moment? If not, is it something that could be added in the future?

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by prazdevs** [comment]
Atm, options are passed at store initialisation, and cookies used are coming from Nuxt's `useCookie` composable, so I don't think it's possible, not really a considered option, atm. Maybe that could be implemented in a store using UseCookie and setup syntax 🤔
