### ISSUE TITLE
当store中包含复杂数据类型的时候持久化存储失效

### ISSUE THREAD

**Issue by jaques-tino** [prazdevs/pinia-plugin-persistedstate#216]
### Describe the bug

```typescript
import router from '@/router'
import { login } from '@/api/users'
import { children } from '@/router/routes'
import { UsersState } from '../types/users'
import { useRequest } from '@/hooks/request'
import { Message } from '@arco-design/web-vue'
import { LoginOptions, UsersOptions } from '@/api/type'

export const useStore = defineStore('users', {
  persist: {
    paths: ['access_token', 'enabledProduct', 'menus']
  },
  state: (): UsersState => ({
    access_token: '',
    enabledProduct: true,
    menus: []
  }),
  actions: {
    isLogin() {
      return !!this.access_token
    },
    setToken(token: string) {
      this.access_token = token
    },
    async setEnabledProduct() {
      
    },
    async login(options: LoginOptions) {
      const { success, data } = useRequest(() => login(options))

      watchEffect(() => {
        if (success.value) {
          const { user, hasAccount } = data.value as { user: UsersOptions, hasAccount: boolean }
          if (hasAccount) {
            this.access_token = user.token
            // 设置菜单
            this.menus = JSON.parse(JSON.stringify(children))
            // 跳转到主页
            router.push('/')
            return
          }
          Message.error('该用户不存在或者用户信息有误！')
        }
      })
    }
  }
})
```

### Reproduction

none

### System Info

```Shell
System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M1
    Memory: 120.47 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.6.0 - ~/.nvm/versions/node/v18.6.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.6.0/bin/yarn
    npm: 8.13.2 - ~/.nvm/versions/node/v18.6.0/bin/npm
    pnpm: 8.6.2 - ~/.nvm/versions/node/v18.6.0/bin/pnpm
  Browsers:
    Chrome: 114.0.5735.198
    Edge: 114.0.1823.67
    Safari: 16.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Songhaohan520** [comment]
I have also encountered this issue. Some complex data can be stored locally successfully, but for some store files, they cannot be saved, and no error is reported.

**Comment by Songhaohan520** [comment]
When attempting to store the files of certain stores by using methods like $persist(), an error occurs

**Comment by Songhaohan520** [comment]
Can't I export and use it like this before router? Why is storage ineffective when using it like this
`export const useAppStoreWithOut = () => {
  return useAppStore(store)
}`

**Comment by prazdevs** [comment]
Could you provide a complete repo/stackblitz to reproduce the issue ? tyvm

**Comment by kirklin** [comment]
> Could you provide a complete repo/stackblitz to reproduce the issue ? tyvm
我遇到了一个类似的问题，
https://github.com/kirklin/celeris-web/blob/master/apps/admin/src/store/modules/design/index.ts
这种情况下。我的Store实例上好像没有$persist这个方法。导致持久化不能生效

**Comment by prazdevs** [comment]
Closing as stale
