### ISSUE TITLE
Expiration of export usage before routing

### ISSUE THREAD

**Issue by Songhaohan520** [prazdevs/pinia-plugin-persistedstate#217]
### Describe the bug

Can't I export and use it like this before router? Why is storage ineffective when using it like this
`export const useAppStoreWithOut = () => { return useAppStore(store) }`

### Reproduction

-

### System Info

```Shell
vue 3.3.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by prazdevs** [comment]
Can you provide a proper reproduction repo ?

**Comment by Songhaohan520** [comment]
`import { defineStore } from 'pinia'
import { store } from '@/store'

interface lockInfo {
  isLock?: boolean
  password?: string
}

interface LockState {
  lockInfo: lockInfo
}

export const useLockStore = defineStore('lock', {
  state: (): LockState => {
    return {
      lockInfo: {
      
      }
    }
  },
  getters: {
    getLockInfo(): lockInfo {
      return this.lockInfo
    }
  },
  actions: {
    setLockInfo(lockInfo: lockInfo) {
      this.lockInfo = lockInfo
    },
    resetLockInfo() {
      this.lockInfo = {}
    },
    unLock(password: string) {
      if (this.lockInfo?.password === password) {
        this.resetLockInfo()
        return true
      } else {
        return false
      }
    }
  },
  persist: true
})

export const useLockStoreWithOut = () => {
  return useLockStore(store)
}
`

**Comment by Songhaohan520** [comment]
> 你能提供一个适当的复制回购吗？

When using methods like useLockStore at the bottom to load and use before routing, the persistence feature is disabled. What could be the reason for this?
`import { defineStore } from 'pinia'
import { store } from '@/store'

interface lockInfo {
  isLock?: boolean
  password?: string
}

interface LockState {
  lockInfo: lockInfo
}

export const useLockStore = defineStore('lock', {
  state: (): LockState => {
    return {
      lockInfo: {}
    }
  },
  getters: {
    getLockInfo(): lockInfo {
      return this.lockInfo
    }
  },
  actions: {
    setLockInfo(lockInfo: lockInfo) {
      this.lockInfo = lockInfo
    },
    resetLockInfo() {
      this.lockInfo = {}
    },
    unLock(password: string) {
      if (this.lockInfo?.password === password) {
        this.resetLockInfo()
        return true
      } else {
        return false
      }
    }
  },
  persist: true
})

export const useLockStoreWithOut = () => {
  return useLockStore(store)
}
`

**Comment by prazdevs** [comment]
I'd say doing it the way you do defers the store creation and the persistence is already loaded, thus it wont hydrate your store ?

**Comment by Songhaohan520** [comment]
> I'd say doing it the way you do defers the store creation and the persistence is already loaded, thus it wont hydrate your store ? I have never seen stores being defined/used this way thinking

 Because the router needs to be created before it can be accessed, sometimes it is necessary to fetch data from the store before the router is loaded. However, when using the method of fetching the store in advance, the persistence functionality becomes ineffective.

**Comment by prazdevs** [comment]
I dont get what the router has to do here now 🤔 i need a full repo or stackblitz to understand the issue.

**Comment by MZ-Dlovely** [comment]
u can refer to the judgment method of [`pinia.use`](https://github.com/vuejs/pinia/blob/v2/packages/pinia/src/createPinia.ts#L40-L47)
before pinia installed, all plugins will be support to push in a list named [`toBeInstalled`](https://github.com/vuejs/pinia/blob/v2/packages/pinia/src/createPinia.ts#L19-L20) but `pinia._p`.
and then, they will push in `pinia._p` from `toBeInstalled` when [`pinia install`](https://github.com/vuejs/pinia/blob/v2/packages/pinia/src/createPinia.ts#L23-L37)
when some store is used before pinia installed, it may unable to enjoy plugins

```ts
export function createPinia(): Pinia {
  // ...
  let _p: Pinia['_p'] = []
  // plugins added before calling app.use(pinia)
  let toBeInstalled: PiniaPlugin[] = []
  // ...
  const pinia: Pinia = markRaw({
    install(app: App) {
      // this allows calling useStore() outside of a component setup after
      // installing pinia's plugin
      setActivePinia(pinia)
      if (!isVue2) {
        // ...
        toBeInstalled.forEach((plugin) => _p.push(plugin))
        toBeInstalled = []
      }
    },
    use(plugin) {
      if (!this._a && !isVue2) {
        toBeInstalled.push(plugin)
      } else {
        _p.push(plugin)
      }
      return this
    },
    // ...
  })
  // ...
}
```

**Comment by Songhaohan520** [comment]
> I dont get what the router has to do here now thinking i need a full repo or stackblitz to understand the issue.

The most direct way is that before the router is mounted, I made a call to a certain store to obtain its value, and then the persistence will fail. Will not store the store in Pinia into localStorage

**Comment by kirklin** [comment]
"I encountered a similar issue here:
https://github.com/kirklin/celeris-web/blob/master/apps/admin/src/store/modules/design/index.ts
In this case, it seems that the $persist method is not available on my Store instance, which is causing the persistence to not work correctly."

**Comment by prazdevs** [comment]
As stated earlier, plugins instantiation/run are deferred when the vue instance isnt available yet. Interacting with the store at this time will have the mutation happen before plugin is instantiated, causing the persistence to not happen.

This isn't really on the side of the plugin, and more of a pinia limitation :/
