### ISSUE TITLE
I can't customize the persist option

### ISSUE THREAD

**Issue by KBKUN024** [prazdevs/pinia-plugin-persistedstate#218]
### Describe the bug

I use this plugin in my Nuxt3 project,I found data is been stored in Cookies,not in localStorage,but documentation said default configration uses localStorage as storage,when I open devtools of browser,nothing found in localStorage.So I decide to customise the 'persist option' of defineStore,look the following image:
![image](https://github.com/prazdevs/pinia-plugin-persistedstate/assets/54589019/6a38f5c2-ebc7-4c99-abe6-8bd8daef9ddd)
Then Nuxt gives me a error:
![image](https://github.com/prazdevs/pinia-plugin-persistedstate/assets/54589019/63b893da-f0f8-4208-8860-768adc4afa42)
but in console,window can be output:
![image](https://github.com/prazdevs/pinia-plugin-persistedstate/assets/54589019/c589b18f-b929-4107-bce5-5fd4236a4a0b)
If I remove the first console.log,alse has a error,this time the error is localStorage is not defined:
![image](https://github.com/prazdevs/pinia-plugin-persistedstate/assets/54589019/c61c3899-1663-45d6-942c-630ee392f61e)
Then I add window before localStorage,go to another page,then go to this page which uses store,refresh page,this error is gone,and increment action can work,console.log within increment also can output.
But when I refresh the page after excute increment,this error appears again:
![image](https://github.com/prazdevs/pinia-plugin-persistedstate/assets/54589019/24b98c17-ec3b-4c94-a4c4-d1f11d9390e7)
I'm so confused,please help me!

### Reproduction

https://github.com/KBKUN024/Nuxt3-project

### System Info

```Shell
System:Window 10
Browser:Edge 114.0.1823.67
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by prazdevs** [comment]
Hi, there is documentation on how to use in Nuxt 3 specifically: https://prazdevs.github.io/pinia-plugin-persistedstate/frameworks/nuxt-3.html

You can choose  between Cookies, LocalStorage, SessionStorage using auto imported storages (`persistedState.localStorage` for instance)
Keep in mind that local storage is client only, and will create mismatches in SSR contexts.

**Comment by KBKUN024** [comment]
Thanks for you reply!My problem is resolved.



---Original---
From: ***@***.***&gt;
Date: Sat, Jul 8, 2023 18:48 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [prazdevs/pinia-plugin-persistedstate] I can't customize thepersist option (Issue #218)




 
Hi, there is documentation on how to use in Nuxt 3 specifically: https://prazdevs.github.io/pinia-plugin-persistedstate/frameworks/nuxt-3.html
 
You can choose  between Cookies, LocalStorage, SessionStorage using auto imported storages (persistedState.localStorage for instance)
 Keep in mind that local storage is client only, and will create mismatches in SSR contexts.

**Comment by kespaldon** [comment]
> Keep in mind that local storage is client only, and will create mismatches in SSR contexts.

so do i have to implement it this way?
```
persist: {
  storage: process.client ? persistedState.sessionStorage : null,
},
```

**Comment by prazdevs** [comment]
@kespaldon `persistedState.sessionStorage` and `persistedState.localStorage` are already implemented to handle SSR (they just ignore server side, and only act client side to avoid errors) :)
