### ISSUE TITLE
Pinia is not persisted in localstorage if another pinia store is declared in state

### ISSUE THREAD

**Issue by mellanyx** [prazdevs/pinia-plugin-persistedstate#219]
### Describe the bug

Pinia is not persisted in localstorage if another pinia store is declared in state.

If the other pinia storage is declared in the desired action, there is no problem.

![image](https://github.com/prazdevs/pinia-plugin-persistedstate/assets/47928999/70e4b86d-ea3a-4b21-a0ba-ac0513f900f9)
![image](https://github.com/prazdevs/pinia-plugin-persistedstate/assets/47928999/e6e6f128-adc1-449f-9f7a-2ec9ff61fc65)

The problem does not only manifest itself on my system configuration!

### Reproduction

-

### System Info

```Shell
System:
    OS: macOS 13.4
    CPU: (8) arm64 Apple M1
    Memory: 146.80 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 19.6.1 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.5.0 - /opt/homebrew/bin/npm
    pnpm: 7.27.1 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 114.0.5735.198
    Safari: 16.5
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by prazdevs** [comment]
Can you provide a proper repo/stackblitz to reproduce the issue. tyvm

**Comment by mellanyx** [comment]
Yes, I'll send the repository a little later. This problem occurs only when building a project (build)
