### ISSUE TITLE
[docs] Improve quickstart guide on the Nuxt module page

### ISSUE THREAD

**Issue by Me-Phew** [prazdevs/pinia-plugin-persistedstate#224]
### Clear and concise description of the problem

The current quickstart quide on [the plugin's Nuxt module page](https://nuxt.com/modules/pinia-plugin-persistedstate) tells you to conifgure it with Pinia like [here](https://prazdevs.github.io/pinia-plugin-persistedstate/guide/) which you can't realy do in Nuxt

### Suggested solution

Instead you need to follow [Nuxt 3 quickstart guide](https://prazdevs.github.io/pinia-plugin-persistedstate/frameworks/nuxt-3.html) to configure the Nuxt module and as such this quickstart guide should be featured on the module's page instead

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by prazdevs** [comment]
Hi, this is more related to the https://github.com/nuxt/modules repo, i'll issue a PR to change the broken link to the subpackage repo/readme

**Comment by prazdevs** [comment]
Closing this issue here, we just have to wait for nuxt-modules repo to merge the pr 🙏
