### ISSUE TITLE
store value are not preserved when there is an active iframe on screen

### ISSUE THREAD

**Issue by renkoha28** [prazdevs/pinia-plugin-persistedstate#226]
### Describe the bug

I am developing a project with vue 3 and laravel 10 frontend and backend separated, i'm using this plugin to persists data after page refresh which works in most pages except two of them where i'm using pspdfkit, a tool for working with pdf documents, this tool creates an iframe that allows user to make changes to the document, and i noticed that if i store value in a variable before calling the function that creates pspdfkit iframe that value get saved to the store and local storage for backup as it should, however if i try to save something after the iframe has been rendered the values will be saved into the store but not the local storage causing that any values reset to their default ones after refreshing the page, i solved the issue by creating a function that manually stores the data to local storage but i think that maybe the iframe interferes with the plugin backup functionality because i haven't had the same issue anywhere else

### Reproduction

can't provide access to this code

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
    Memory: 4.05 GB / 15.76 GB
  Binaries:
    Node: 18.6.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.7.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1992.0), Chromium (115.0.1901.183)
    Internet Explorer: 11.0.22621.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by MZ-Dlovely** [comment]
could you provide a complete repo/stackblitz to reproduce the issue?
