### ISSUE TITLE
At the time of request, the cookie carries the properties in storage

### ISSUE THREAD

**Issue by Abernethy-BY** [prazdevs/pinia-plugin-persistedstate#227]
### Describe the bug

On my website there is a set of cookies that looks like this

![image](https://github.com/prazdevs/pinia-plugin-persistedstate/assets/69035266/84c06665-4e5c-487d-a63a-e80a3a366ffb)

the cookie storage code
```
import { acceptHMRUpdate, defineStore } from 'pinia'

export const bearerStore = defineStore('token', () => {
  const token = ref<string>('')
  return { token }
}, {
  persist: { paths: ['token'], storage: persistedState.cookiesWithOptions({ sameSite: 'strict', path: 'token' }) },
})

if (import.meta.hot)
  import.meta.hot.accept(acceptHMRUpdate(bearerStore, import.meta.hot))
```

When I HTTP requested, the cookie I carried became like this
![image](https://github.com/prazdevs/pinia-plugin-persistedstate/assets/69035266/91d086f1-427d-4281-9015-40f14fd73817)

The result after decoding
![image](https://github.com/prazdevs/pinia-plugin-persistedstate/assets/69035266/7b6866cc-42e6-4705-9f11-67cb83458f4e)

I want the cookie I carry when I request it to be `token:***`

Excuse me, should I do this？

### Reproduction

https://stackblitz.com/github/HW-maintenance/HW_maintenance_web/tree/pinia-plugin-persistedstate_nuxt_issues

### System Info

```Shell
system:window
browsers:chrome
Dependent version:
{
    "@pinia-plugin-persistedstate/nuxt": "^1.1.1",
    "@pinia/nuxt": "^0.4.11",
    "nuxt": "^3.6.3",
    "pinia": "^2.1.4",
}
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by MZ-Dlovely** [comment]
pls resolve your cookie on http-server by yourself

**Comment by Abernethy-BY** [comment]
I think since cookies can be automatically carried, why not be more flexible and formatted?

If it supports configuring the cookie format, please advise how to configure it
If the configuration cookie format is not supported, I will submit a new pr
Thanks

**Comment by prazdevs** [comment]
Hi, the cookie will be serialized as follows:
<store-name>: {
	<store-prop1>: <value1>,
	<store-prop2>: <value2>
}

In your case, it takes the whole store called "token", and only persists its prop called "token" too.
It's not a special case for cookies, it will do the same with all storages.

One store = one storage/cookie. :)

**Comment by Abernethy-BY** [comment]
> 嗨，cookie 将按如下方式序列化：
> 
> ```
> <store-name>: {
> 	<store-prop1>: <value1>,
> 	<store-prop2>: <value2>
> }
> ```
> 
> 在您的情况下，它采用称为“令牌”的整个商店，并且也只保留其称为“令牌”的道具。这不是 cookie 的特例，它将对所有存储执行相同的操作。
> 
> 一个存储 = 一个存储/饼干。:)

Sorry, I don't know exactly where this side of the code should be written

**Comment by MZ-Dlovely** [comment]
if you presist your token as cookie by this plugin, you should parse the token out in server side.
like this:
```ts
export default defineEventHandle(async event => {
  const { token } = getCookie(event, 'token')
  console.log('token:', token)
})
```

**Comment by Abernethy-BY** [comment]
That's bad, I can only format my cookies on the client side, I don't have permission to modify serve
Is there any other solution? thanks

**Comment by prazdevs** [comment]
I think I understand but this plugin is not meant to parse external cookies and use them in storage.
It is meant to use cookies purely to convey the storage between client and server with SSR.

If you need to process cookies from outside, you should parse it before storing it.

I will close it for now if you have the info you need. Feel free to ask more question if i can be of any help :)
