### ISSUE TITLE
Different behaviour on ref's if using default config or not

### ISSUE THREAD

**Issue by hedefalk** [prazdevs/pinia-plugin-persistedstate#230]
I haven't nailed this down entirely yet as to why this happens - and maybe I'm missing something entirely obvious as a new user.  But here it goes.

I'm using nuxt and storeToRefs. When using this configuration on the store:

```
  persist: {
    storage: persistedState.localStorage,
  },
```

I get a non-functioning behaviour I don't entirely understand. Details will follow.

Just changing it to:

```
persist: true
```

makes it work as I expected which in itself is unexpected to me since I thought this would _be the exact same thing_ reading the docs.

I should definitely try to create a minimal example, but thought I should start here and ask if this was something known before I put down that work. 

Trying to explain in words first:

I have hierarchy of components with v-model binds from the store down a few levels ending with a native <textarea> in the end bound to .value. In the second config example, when I load the page, I can see the state loaded from localStorage being propagated down the refs into the value of the textarea just as expected and shown in dom.

In the first config case, I can also see the ref's being updated correctly all the way down to but not into the native textarea (looking with dev tools vue plugin), but there it ends. The textarea does not get the value correctly.

So it seems that the ref is reactivity is working differently. I can see my ref values updated in my components but not in the native textarea. There's also an api call inside a computed with a debouncedRef which does trigger fine in the default config, but not in the explicit.

Yeah, I should really try to make a minimal example repo, but there's some work there. I have a lot of mess of debouncing the ref's and api calls within computed props and stuff, but I have now switched between the two config variants at least 10 times and reliable make it work with the simple boolean one and not work with the other. 

I think there might be issues with my code that I should fix, but to me its also weird that the two config variants differs enough that one exposes "my bug" and the other doesn't - enough to merit a report. Maybe it's just my understanding that these two configs should be the same that's wrong…?

**Comment by prazdevs** [comment]
Hi :) 
The default storage (what is used when you just do `persist: true` is using Cookies. So that may be the source of your problemes since LocalStorage is client only. :)

**Comment by hedefalk** [comment]
> Hi :) The default storage (what is used when you just do `persist: true` is using Cookies. So that may be the source of your problemes since LocalStorage is client only. :)

Ah, that at least explains something. I read over here that localStorage was the default:
https://prazdevs.github.io/pinia-plugin-persistedstate/guide/config.html#storage

<img width="294" alt="image" src="https://github.com/prazdevs/pinia-plugin-persistedstate/assets/116520/3cf21af2-a105-400a-91ff-3e5aa5218048">

The default one works as it should though so I guess there could definitely be something related to nuxt's SSR and hydration timing that makes it behave differently. It still somewhat works though…

**Comment by prazdevs** [comment]
Yeah the default for the plugin is `localStorage`, but when used through Nuxt, it defaults to cookies to properly handle serverside rendering :)

**Comment by hedefalk** [comment]
> Yeah the default for the plugin is `localStorage`, but when used through Nuxt, it defaults to cookies to properly handle serverside rendering :)

gotcha! see it now ;) I'll close this one. I'll see if I can possibly reproduce the "weirdness" with localStorage and hydration in a minimal repro. Thanks! 🙏
