### ISSUE TITLE
pinia持久化存储失效了

### ISSUE THREAD

**Issue by zskssg** [prazdevs/pinia-plugin-persistedstate#231]
### Describe the bug

我在注册pinia实例时，将注册代码提到了一个文件中并抛出pinia对象。这样做的原因是方便我在ts文件中使用sotre。
`import { createPinia } from 'pinia'
import piniaPluginPersistedstate from 'pinia-plugin-persistedstate'

const pinia = createPinia()
pinia.use(piniaPluginPersistedstate)

export default pinia`

然后，在mian.ts中，app.use(pinia)。
这一切正常。
但我在ts文件使用store后，并在app.vue调用包含store的函数。
store的持久化存储将会失效。
![image](https://github.com/prazdevs/pinia-plugin-persistedstate/assets/50895817/3443b461-0f31-4b21-8ada-941f7fc5ebc4)
sotre实例
`import { defineStore } from 'pinia'

export const useStore = defineStore('main', {
  //  类似data
  state: () => {
    return {
      userInfo: localStorage.getItem('userInfo') ? JSON.parse(localStorage.getItem('userInfo') as string) : undefined,
      token: 'aaxswkjaoksjdohasdh' as string | undefined,
      num: 1,
    }
  },
  //  类似计算属性
  getters: {
    getNum2: (state) => state.num * 2
  },
  // 类似methods
  actions: {
    setUserInfo(info = null) {
      this.userInfo = info || undefined
      console.log(info);

      // localStorage.setItem('userInfo', JSON.stringify(info))
    }
  },
  persist: [
    {
      paths: ['num'],
      storage: sessionStorage,
      key: 'my_num'
    },
    {
      paths: ['token'],
      key: 'token',
      storage: localStorage
    },
    {
      paths: ['userInfo'],
      key: 'token',
      storage: localStorage
    },
  ]
})`

ts文件中使用
`import { useStore } from '@/store/index'
import pinia from './../store/pinia';

const store = useStore(pinia)
function getStore1() {
  return store
}

export {
  getStore1
}`
vue组件中使用 ts文件里的函数。
如果这样写，pinia可以正常使用，持久化存储失效。

----------------------------------------------------------------------------------------------------------
最后，我发现，如果在pinia实例文件中，将创建pinia的代码用函数包裹导出，持久化存储会正常使用。
`import { createPinia } from 'pinia'
import piniaPluginPersistedstate from 'pinia-plugin-persistedstate'

export default function () {
  const pinia = createPinia()
  pinia.use(piniaPluginPersistedstate)
  return pinia
}`

这样感觉怪怪的，有没有更合适的方法？？？

### Reproduction

-

### System Info

```Shell
没有异常输出
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by prazdevs** [comment]
Hi, i need a proper reproduction repository or stackblitz to test it and see what's wrong (no copy paste of code in the issue). Thanks you :)

**Comment by zskssg** [comment]
> Hi, i need a proper reproduction repository or stackblitz to test it and see what's wrong (no copy paste of code in the issue). Thanks you :)
I created a new warehouse where pinia cannot be persisted properly.

[basic-demo](https://github.com/zskssg/basic-demo)

这是相关代码目录
![image](https://github.com/prazdevs/pinia-plugin-persistedstate/assets/50895817/4870df8f-d74a-4be6-b966-87eafd8f7cfb)

**Comment by Userzhizhong** [comment]
I met same problem, It seems trigger the hook of persist

**Comment by zskssg** [comment]
@Userzhizhong 不要在函数外调用 useStore() 方法。将存储实例传入函数或者在函数内部调用 useStore() 方法。这样就可以正常工作。Do not call the useStore() method outside of a function. Pass the storage instance into the function or call the useStore() method inside the function. So it works.

**Comment by MZ-Dlovely** [comment]
maybe you can see #217 about [why plugin dont work](https://github.com/prazdevs/pinia-plugin-persistedstate/issues/217#issuecomment-1630227592)

**Comment by three-shui** [comment]
> @Userzhizhong 不要在函数外调用 useStore() 方法。将存储实例传入函数或者在函数内部调用 useStore() 方法。这样就可以正常工作。Do not call the useStore() method outside of a function. Pass the storage instance into the function or call the useStore() method inside the function. So it works.

我在自定义指令的时候也遇到了这种情况，在函数内部调用 useUserSrote() 方法之后持久化确实正常工作了
```
import { useUserSrote } from '@/stores/modules/user';
import pinia from '@/stores'
// const userStore = useUserSrote(pinia)  //pinia持久化失败

export const isHasButton = (app: any) => {
  const userStore = useUserSrote(pinia)  //pinia持久化成功
  app.directive('has', {
    mounted(el: any, options: any) {
      if (!userStore.buttons.includes(options.value)) {
        el.remove()
      }
    },
  })
}
```
