### ISSUE TITLE
persist pinia orm

### ISSUE THREAD

**Issue by treeindark** [prazdevs/pinia-plugin-persistedstate#233]
### Clear and concise description of the problem

after refresh  dataStore is not rehydrate from storage
dataStore is persisted :
dataRepo.all()->[]

but data are persisted in localstorage... (tested with db-storage too)

### Suggested solution

I ask for help !

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by prazdevs** [comment]
We gonna need more context, explanation, reproduction ??
I have 0 idea what you're asking for.
