### ISSUE TITLE
如何在代码中动态指定持久化到哪个storage中？

### ISSUE THREAD

**Issue by cavellpotter** [prazdevs/pinia-plugin-persistedstate#234]
### Describe the bug

如何在代码中动态指定持久化到哪个storage中？

### Reproduction

11

### System Info

```Shell
11
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by prazdevs** [comment]
As it is, I do not see a proper solution that would work all the time. Maybe doable with a custom storage ?

**Comment by MZ-Dlovely** [comment]
> As it is, I do not see a proper solution that would work all the time. Maybe doable with a custom storage ?

maybe we can try to receive a reactify variable to achieve dynamic settings.

**Comment by prazdevs** [comment]
As for now this cannot be achieved in a "clean" way, maybe this can be considered for an eventual v4, but that would require running a function to return the storage everytime the persistence is called, and giving access to lots of things from this function.

Closing this for now but i'll consider it if v4 ever sees the light 🙏
