### ISSUE TITLE
[Nuxt@3.7.0] `[vite-node] [ERR_LOAD_URL] pinia-plugin-persistedstate`

### ISSUE THREAD

**Issue by telmoenmartins** [prazdevs/pinia-plugin-persistedstate#236]
### Describe the bug

With a simple setup of pinia and pinia persisted state on nuxt3 this error appears, any ideal why?

### Reproduction

https://stackblitz.com/edit/nuxt-starter-crtmzw?file=nuxt.config.ts

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
    Memory: 18.21 GB / 31.89 GB
  Binaries:
    Node: 18.16.1 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (116.0.1938.69)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by prazdevs** [comment]
Ah shit, that's annoying.
Problem appears on Nuxt@3.7.0+

Could this be related to vite@4.4 🤔 

I'll try to look into that.

**Comment by prazdevs** [comment]
Okay here's a workaround, add this to `nuxt.config.ts`:

```ts
export default defineNuxtConfig({
  modules: ['@pinia/nuxt', '@pinia-plugin-persistedstate/nuxt'],
  build: {
    transpile: ['pinia-plugin-persistedstate'],
  },
});

```

**Comment by schalkneethling** [comment]
> Okay here's a workaround, add this to `nuxt.config.ts`:
> 
> ```ts
> export default defineNuxtConfig({
>   modules: ['@pinia/nuxt', '@pinia-plugin-persistedstate/nuxt'],
>   build: {
>     transpile: ['pinia-plugin-persistedstate'],
>   },
> });
> ```

This works for me. Thanks, @prazdevs

**Comment by prazdevs** [comment]
Could you try again with 
```json
"@pinia-plugin-persistedstate/nuxt": "^1.1.1",
"@pinia/nuxt": "^0.4.11",
"nuxt": "^3.7.3"
```
I have it working locally (it worked with 3.7.0 too tho). Does it work locally ?

**Comment by telmoenmartins** [comment]
> Could you try again with
> 
> ```json
> "@pinia-plugin-persistedstate/nuxt": "^1.1.1",
> "@pinia/nuxt": "^0.4.11",
> "nuxt": "^3.7.3"
> ```
> 
> I have it working locally (it worked with 3.7.0 too tho). Does it work locally ?

No luck, only working with the transpile option for now

**Comment by prazdevs** [comment]
I'll try to see if i can add transpilation to the module itself and it works, so there's no need to add it afterwards.

**Comment by sunupf** [comment]
Hi, I try the workaround, it's works. but somehow the state is not persist. I check my cookies it's empty. and when I reload the state refreshed.

It's only me or it's also happened to you guys?

**Comment by prazdevs** [comment]
Everything seems to be working fine with `nuxt@3.8.2` without having to transpile 👍 
feel free to reopen is issue somehow reappears

**Comment by kevinlonigro** [comment]
> ```ts
> build: {
>     transpile: ['pinia-plugin-persistedstate'],
>   },
> ```

Just encountered the issue with following packages, the build transpile option fixes it:

- "nuxt": "^3.9.0",
- "@pinia/nuxt": "^0.5.1",
- "@pinia-plugin-persistedstate/nuxt": "^1.2.0",

**Comment by prazdevs** [comment]
thanks for the headsup, i kinda want to do a new module version and make it cleaner, but i have lots of stuff on the plate, and personal/health issues, so it has to wait.

as long as there is a workaround and it can work, it's ok ^_^

**Comment by SheikhElMoctarG** [comment]
> ```ts
> build: {
>     transpile: ['pinia-plugin-persistedstate'],
>   },
> ```

It's working ❤️

**Comment by ergs22** [comment]
> Okay here's a workaround, add this to `nuxt.config.ts`:
> 
> ```ts
> export default defineNuxtConfig({
>   modules: ['@pinia/nuxt', '@pinia-plugin-persistedstate/nuxt'],
>   build: {
>     transpile: ['pinia-plugin-persistedstate'],
>   },
> });
> ```

THANKSS. 13/07/2024 still working

**Comment by thylaakari** [comment]
> Okay here's a workaround, add this to `nuxt.config.ts`:
> 
> ```ts
> export default defineNuxtConfig({
>   modules: ['@pinia/nuxt', '@pinia-plugin-persistedstate/nuxt'],
>   build: {
>     transpile: ['pinia-plugin-persistedstate'],
>   },
> });
> ```

doesn't work

**Comment by BaldFabi** [comment]
Have a look into https://github.com/vuejs/pinia/issues/2822. Try to run `npm i pinia --force`

**Comment by agracia-foticos** [comment]
I try transpile, change to '@pinia-plugin-persistedstate/nuxt', but throws 

`[nuxt] [request error] [unhandled] [500] obj.hasOwnProperty is not a function`
