### ISSUE TITLE
我开启了 strict 但是使用 defineStore 时，依然返回any

### ISSUE THREAD

**Issue by tetap** [prazdevs/pinia-plugin-persistedstate#242]
### Describe the bug

I turned on strict but still returned any when using defineStore.
This is my tsconfig.json
`

    "baseUrl": "./",
    "target": "esnext",
    "useDefineForClassFields": true,
    "module": "esnext",
    "moduleResolution": "node",
    "strict": true,
    "jsx": "preserve",
    "sourceMap": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "strictPropertyInitialization": false,
    "lib": ["esnext", "dom"],
    "skipLibCheck": true,
`

### Reproduction

not

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
    Memory: 10.90 GB / 23.94 GB
  Binaries:
    Node: 16.20.2 - D:\node\node.EXE
    Yarn: 1.22.19 - D:\node\node_global\yarn.CMD
    npm: 8.19.4 - D:\node\npm.CMD
    pnpm: 8.7.4 - D:\node\node_global\pnpm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (117.0.2045.31)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by tetap** [comment]
useUserInfoStore(pinia?: Pinia | null | undefined, hot?: any): any

**Comment by tetap** [comment]
![image](https://github.com/prazdevs/pinia-plugin-persistedstate/assets/57606461/dbace555-ae31-4c60-bd72-f0147daaa11a)

![image](https://github.com/prazdevs/pinia-plugin-persistedstate/assets/57606461/b26f1452-2702-48eb-afdb-2f44567966e4)

**Comment by prazdevs** [comment]
Hi, I hardly see what this has to do with the plugin.
Also, without a reproduction repo I cannot consider the issue.

Pleasee provide a reproduction repo/stackblitz and reopen the issue :)
