### ISSUE TITLE
多个store数据持久化到同一个key下支持吗？

### ISSUE THREAD

**Issue by Luolei1992** [prazdevs/pinia-plugin-persistedstate#243]
### Clear and concise description of the problem

对多个store文件进行持久化操作，会在本地存储里新增多个locaStorage，多个key，希望把多个key整合到一个里面
![image](https://github.com/prazdevs/pinia-plugin-persistedstate/assets/23149226/e64523ea-8a02-44d8-9491-59cc7910df37)

### Suggested solution

类似vuex的modules，结合vuex-persistedstate来实现多模块，集成到一个key
![image](https://github.com/prazdevs/pinia-plugin-persistedstate/assets/23149226/80e3bf1b-0b11-4e09-a1e8-796f456789d0)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by XF-air** [comment]
这个你找到了方法么？

**Comment by prazdevs** [comment]
Hi, this goes against the "modular" aspect of Pinia, and isolating stores. 
However, I guess this might be doable with a hacky custom Storage option, which would read/set a single key of the storage.
