### ISSUE TITLE
Nuxt 3 setup-store not persisting data

### ISSUE THREAD

**Issue by chris-si** [prazdevs/pinia-plugin-persistedstate#244]
### Describe the bug

Hi,

I just tried to switch to a setup-store with ``` { persist: true }``` as the third parameter like mentioned in the docs.
While the core pinia functions work fine, the persistence doesn't work anymore and no cookies are created.

And while I just prepared a little reproduction on StackBlitz I found out that the persistence for the option-store doesn't seem to work either!?

Maybe I have a major mistake in the code but it worked with kind of that configuration (option-store) before.

### Reproduction

https://stackblitz.com/edit/nuxt-starter-xscaak?file=app.vue

### System Info

```Shell
System:
    OS: macOS 13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Memory: 3.00 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.1 - ~/.nvm/versions/node/v18.16.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.16.1/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.1/bin/npm
    pnpm: 8.6.7 - ~/.nvm/versions/node/v18.16.1/bin/pnpm
  Browsers:
    Chrome: 116.0.5845.187
    Safari: 16.6
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by prazdevs** [comment]
Hi, I looked into it (and into some depths of pinia) and it looks like subcription (`$subscribe`) is not triggered when the state is not exposed.

if you add `_counter` to the return of the setup store it will work. This probably has to do with what triggers subscription in the case of setup stores.

Also you could _technically_ do without even using the plugin by doing this if you are using nuxt : 

```ts
import { defineStore } from 'pinia';

export const useSetupStore = defineStore('setup', () => {
  const _counter = useCookie<number>('setup', { default: () => 0 });

  const counter = computed(() => _counter.value);

  function increment() {
    _counter.value++;
  }

  return {
    counter,
    increment,
  };
});
```

So maybe i should warn about it somewhere and see 🤔 It's not Nuxt specific tho.

**Comment by chris-si** [comment]
While I think it's not the 'nicest' workaround to either expose the internal variables or use the useCookie syntax, it'll do for now with the workarounds you described. Anyway thanks for your quick response and your help! 🙂
