### ISSUE TITLE
Support use with Composable Pinia stores

### ISSUE THREAD

**Issue by jasonwmatteson** [prazdevs/pinia-plugin-persistedstate#245]
### Clear and concise description of the problem

From the documentation, this seems to not support usage with Composable Pinia stores.

### Suggested solution

Would be great to have documentation on how - or simply the ability - to use this library within Composable Pinia stores.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by prazdevs** [comment]
What do you mean by "composable pinia store" ? 🤔  Setup stores ? We support them already (with maybe some limitation due to pinia #244 )

**Comment by jasonwmatteson** [comment]
Yes, sry...setup stores.  I am trying to use these through Nuxt btw.

**Comment by jasonwmatteson** [comment]
And to further explain what I am trying to do: I am using Nuxt and using setup Pinia stores.  I would like them all to be persisted in localStorage (IndexedDb would be better, but doesn't look like this supports that).

Reason I need this is to be able to set a store variable and then use it in a new window.

**Comment by prazdevs** [comment]
https://prazdevs.github.io/pinia-plugin-persistedstate/frameworks/nuxt-3.html

**Comment by mrleblanc101** [comment]
@prazdevs This does not really answer the question.
Setup store doesn't export an object, but a function.
Here is an exemple:
```
export const useCounterStore = defineStore('counter', () => {
  const count = ref(0)
  const name = ref('Eduardo')
  const doubleCount = computed(() => count.value * 2)
  function increment() {
    count.value++
  }

  return { count, name, doubleCount, increment }
});
```

**Comment by Martacus** [comment]
Is setup syntax still an option in de docs? I cannot seem to find it.
