### ISSUE TITLE
Is navigator.storage.persist() supported?

### ISSUE THREAD

**Issue by hellmediadev** [prazdevs/pinia-plugin-persistedstate#246]
### Describe the bug

This is a question - not a bug. Is there a way to use `navigator.storage.persist()`?
https://developer.mozilla.org/en-US/docs/Web/API/StorageManager/persist

By calling this function the store can be made more resistant - e.g. against browser data deletion. 
Some browsers will open a Permission Dialog. 

### Reproduction

https://developer.mozilla.org/en-US/docs/Web/API/StorageManager/persist

### System Info

```Shell
latest Pinia and pinia-plugin-persistedstate
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by prazdevs** [comment]
Hi, there is no plan to support it at the moment, also StorageManager involves lots of async operation incompatible with pinia's way of mutating things :)
