### ISSUE TITLE
持久化状态可以自定义时间

### ISSUE THREAD

**Issue by zouyun572657111** [prazdevs/pinia-plugin-persistedstate#247]
### Clear and concise description of the problem

持久化的时间可以自定义设定 根据设定的时间选择是否失效  默认一直持久

### Suggested solution

存取到本地缓存中加一个时间戳

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by prazdevs** [comment]
Hi, the option was asked in #21 and we didnt consider it. It is the responsibility of the storage and not the plugin. 

You can use the `storage` option and create one that will expire when you want it to :)
