### ISSUE TITLE
update to @pinia/nuxt@0.5.1

### ISSUE THREAD

**Issue by Kiansa** [prazdevs/pinia-plugin-persistedstate#249]
### Describe the bug

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: nuxt-ultra@undefined
npm ERR! Found: @pinia/nuxt@0.5.1
npm ERR! node_modules/@pinia/nuxt
npm ERR!   dev @pinia/nuxt@"^0.5.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @pinia/nuxt@"^0.4.4" from @pinia-plugin-persistedstate/nuxt@1.1.2
npm ERR! node_modules/@pinia-plugin-persistedstate/nuxt
npm ERR!   dev @pinia-plugin-persistedstate/nuxt@"^1.1.2" from the root project

### Reproduction

NA

### System Info

```Shell
NA
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jasonhibbs** [comment]
My short-term workaround (to ensure my deploys continue) is to install & pin the requested version.

```sh
yarn add @pinia/nuxt@0.4.4
```

**Comment by jasonhibbs** [comment]
My short-term workaround (to ensure my deploys continue) is to install & pin the requested version.

```sh
yarn add @pinia/nuxt@0.4.4
```

**Comment by prazdevs** [comment]
Should be fixed now. Sorry, both sick and really busy these days. 
Hope this works now 😌

**Comment by lmq352489099** [comment]
I had the same problem. I tried to go down
