### ISSUE TITLE
Opt-in/out persistent cookies

### ISSUE THREAD

**Issue by jasonhibbs** [prazdevs/pinia-plugin-persistedstate#252]
### Clear and concise description of the problem

1. I want to use persistent cookies after a user opts-in, so that the user has control of their cookie usage.
2. I want to stop using persistent cookies after a user opts-out, so that the user has control of their cookie usage.

### Suggested solution

I don’t think I can provide technical insight – being able to enable/disable persistent cookies like updating any state would let me achieve the above.

### Alternative

There is a similar question in #185, where a custom serialiser is proposed. I may pursue this initially.

### Additional context

In my ideal scenario, once a user acts on a store, they are prompted to save their preference and enable persistent cookies.

More broadly, this relates to compliance with various cookie laws.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by prazdevs** [comment]
I get the idea. As stated in various other issues, it is sort of out of the scope of the plugin. The plugin is just an interface between Pinia and whatever storage you use (cookies in this case).

I'd say you may want a custom storage implementation, that checks is user agreed before writing it, ignoring it or storing somewhere else in case they dont. 🤔
