### ISSUE TITLE
[core] Watch localstorage for changes from other tabs

### ISSUE THREAD

**Issue by rudolfbyker** [prazdevs/pinia-plugin-persistedstate#254]
### Clear and concise description of the problem

`pinia-plugin-persistedstate` is ensuring that when something changes in Pinia, it is written to `localstorage`. But when another tab running the same web app changes something in `localstorage`, it is not detected by `pinia-plugin-persistedstate`. (Remember that `localstorage` is shared over all tabs that are running the same web app.)

### Suggested solution

- Use any kind of messaging between tabs to say to all other tabs: "Update Pinia from localstorage now" whenever we make a change in localstorage. The https://www.npmjs.com/package/broadcast-channel package makes this easy.
- Alternatively, add to the `pinia-plugin-persistedstate` documentation how to set up [pinia-shared-state](https://github.com/wobsoriano/pinia-shared-state) in such as way as to play nicely with `pinia-plugin-persistedstate` to achieve the same effect.

### Alternative

I'm currently using [pinia-shared-state](https://github.com/wobsoriano/pinia-shared-state) to work around this problem. It sends a [Broadcast](https://developer.mozilla.org/en-US/docs/Web/API/Broadcast_Channel_API) to update the pinia values in other tabs. It also has an option for using `localstorage` instead of `Broadcast` to do the updates. The made me think that, if we could just listen to the `localstorage` updates like they do in `pinia-shared-state`, we would not need `pinia-shared-state` for the stores that are already using `pinia-plugin-persistedstate` with `localstorage`.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by prazdevs** [comment]
That's interesting, I'm just curious about performance impact of pushing this as a base feature when it can be added with another plugin. My take would be to make sure it works well with other plugins more than adding it in persistedstate 🤔

**Comment by rijenkii** [comment]
Alternatively you can just use the [storage event](https://developer.mozilla.org/en-US/docs/Web/API/Window/storage_event) to listen for changes in localstorage from other tabs.

**Comment by AuroraTea** [comment]
We may consider doing so at present.

```js
const store = useStore()
window.onstorage = () => {
  store.$hydrate()
}
```

Of course, I also believe that having it as an optional configuration is essential, as it can help avoid having to write this externally for each store.

**Comment by EgeOnder** [comment]
Is there anyone working on this issue? It would be super cool to have this as a built-in feature.

**Comment by AuroraTea** [comment]
> Is there anyone working on this issue? It would be super cool to have this as a built-in feature.

Me.

Currently, progress is stuck at watching of cookies.

**Comment by Hiram-Wong** [comment]
I tried [pinia-shared-state](https://github.com/wobsoriano/pinia-shared-state), but I had a few problems with it
1.use native type data loss after refreshing
2.use localstorage type data sometime wirte data missing
3.use idb type keep reporting errors.

**Comment by luwenhegithub** [comment]
vueuse的useLocalStorage函数可以实现监听LocalStorage里值的变化，不知有没有参考价值。

**Comment by luwenhegithub** [comment]
这个功能其实挺重要的

**Comment by prazdevs** [comment]
Because of the nature of the plugin and its ability to have custom storage (and there being agnostic of any side effect it can have), it's out of the scope of the plugin.

While local and session storages are easily watched through events, it gets trickier with cookies, let alone any form of custom storage implementation.

I also don't think its the resort of this plugin to synchronize pinia state between tabs (hence why pinia-shared-state is interesting).

I may look into making both plugin work well together if i get some time.

Closing this for now.
