### ISSUE TITLE
How do I get persisted state as a cookie in my Nuxt 3 server

### ISSUE THREAD

**Issue by Kilo0110** [prazdevs/pinia-plugin-persistedstate#255]
I am creating a store and persisting it as a cookie using `persistedState.cookiesWithOptions`. I want to be able to get that state on the server but I have 0 idea on how to go about it. From the issues (both open and closed) as well as the documentation, it is my assumption that this should be doable but I don't know how to. I don't even know the key name it is being saved in Nuxt's useCookie composable.
Below is the code for the store I am trying to persist

``` credentials.ts
import { defineStore } from 'pinia';

export const useCredentialStore = defineStore(
  'credentialStore',
  () => {
    const credentials: Ref<{ email: string; password: string }> = ref({
      email: '',
      password: '',
    });

    const updateCredentials = (
      updatedEmail: string,
      updatedPassword: string
    ) => {
      credentials.value.email = updatedEmail;
      credentials.value.password = updatedPassword;
    };

    return { credentials, updateCredentials };
  },
  {
    persist: {
      storage: persistedState.cookiesWithOptions({
        sameSite: 'strict',
        httpOnly: true,
        maxAge: 365 * 24,
      }),
    },
  }
);

```
On the client, when I try to call the store via `useCookie("credentialStore")` I get `undefined`. Please how do I figure it out?

```
Dependencies:
nuxt: ^3.7.0,
@pinia-plugin-persistedstate/nuxt: ^1.1.1,
```

**Comment by amihhs** [comment]
At present, it seems that there is a certain problem. If it is in the store, even if a state has a default value, if the change has not been triggered (because the setItem of the storage has not been triggered), it will not take effect.

**Comment by Kilo0110** [comment]
> At present, it seems that there is a certain problem. If it is in the store, even if a state has a default value, if the change has not been triggered (because the setItem of the storage has not been triggered), it will not take effect.

I am not exactly sure how what you mean is connected to my issue. As for the issue that I opened, I have fixed the issue and I'll be closing the issue now.

**Comment by Kilo0110** [comment]
Update: I have found out a way to get the credential store. I failed to initialise the `key` field for the persist option which would have given a name for the cookie like so
`{
    persist: {
      storage: persistedState.cookiesWithOptions({
        sameSite: 'strict',
        httpOnly: true,
        maxAge: 365 * 24,
      }),
      key: "credentials"
    },
  }`

I am closing the issue now.
