### ISSUE TITLE
Cookie warning on Nuxt 3 when I set persist to `true`

### ISSUE THREAD

**Issue by doctor-entropy** [prazdevs/pinia-plugin-persistedstate#261]
`Cookie “AuthStore” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite`

I get this error when I set persist to true inside the store file. It doesn't cause any issues other than a warning message.

Could someone please shed some light on this. I am not sure what the warning is about.

**Comment by prazdevs** [comment]
In Nuxt, the plugin relise on `useCookie` (https://nuxt.com/docs/api/composables/use-cookie) and does not set specific `sameSite` cookie option. 
You can fix this by passing the options to the cookie like this : 
```ts
  persist: {
    storage: persistedState.cookiesWithOptions({
      sameSite: 'lax'
    }),
  },
```

**Comment by haexhub** [comment]
sorry for being annoying, but could you please elaborate on this a little? how do I use this with a setup store?
```
export const useMyStore = defineStore("myStore", () => {
  const someState = ref("don't care")
 
  const someFunction = () => {}  

  return {
    someState,
    someFunction
  }
}, {
  persist: ?????
})
```
