### ISSUE TITLE
Persistance not working on latest Nuxt 3 project

### ISSUE THREAD

**Issue by naseefpv** [prazdevs/pinia-plugin-persistedstate#263]
### Describe the bug

Installed a latest nuxt 3 project and installed pinia & pinia-plugin-persistedstate and created a store with **persist: true** option with the help of [https://prazdevs.github.io/pinia-plugin-persistedstate/frameworks/nuxt-3.html](url). Store is working fine but cannot see cookie created at the Cookies tab.
For reference

**Packages:** 
```
"devDependencies": {
    "@nuxt/devtools": "latest",
    "@pinia-plugin-persistedstate/nuxt": "^1.2.0",
    "nuxt": "^3.8.2",
    "vue": "^3.3.10",
    "vue-router": "^4.2.5"
  },
  "dependencies": {
    "@pinia/nuxt": "^0.5.1",
    "pinia": "^2.1.7"
  }
```

**Store**
```
import { defineStore } from 'pinia'

export const useStore = defineStore('main', {
  state: () => {
    return {
      someState: 'hello pinia',
    }
  },
  persist: true,
})
```
**App.vue**
```
<template>
  <div>
    {{store.someState}}
  </div>
</template>

<script setup>
const store = useStore()
</script>
```

### Reproduction

.

### System Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
    Memory: 2.48 GB / 15.49 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
    bun: 1.0.16 - ~/.bun/bin/bun
  Browsers:
    Brave Browser: 99.1.36.116
    Chrome: 119.0.6045.123
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by maximilliangeorge** [comment]
This plugin also suddenly stopped working for me… Unclear when and why… I've updated a few things, including Nuxt itself.

**Comment by prazdevs** [comment]
I just tried with latest nuxt, pinia and plugin and it's working perfectly fine 🤔 
If you have an issue, please provide a proper reproduction (stackblitz or repo) so i can investigate.

Keep in mind persistence happen only on changes. It won't store data in storage as the server starts :)

**Comment by naseefpv** [comment]
> Keep in mind persistence happen only on changes. It won't store data in storage as the server starts :)

Sorry for the late update. It's working fine. I didn't know that the persist only stores data in cookie after any changes.
Thank you for your clarification.
