### ISSUE TITLE
I use persistence in Vue3 but it doesn't work

### ISSUE THREAD

**Issue by Yorlg** [prazdevs/pinia-plugin-persistedstate#266]
### Describe the bug

The usage method is more stable, but I don't know why persistence doesn't work

![image](https://github.com/prazdevs/pinia-plugin-persistedstate/assets/44600060/16dd7545-454f-44b5-a35c-12f6ffb4417d)
![image](https://github.com/prazdevs/pinia-plugin-persistedstate/assets/44600060/b975d465-3443-48a9-9a04-66e5dfe7c4c1)

### Reproduction

 "pinia": "^2.1.7",  "pinia-plugin-persistedstate": "^3.2.0",  "vue": "^3.3.11", "typescript": "^5.2.2", "vite": "^5.0.8",

### System Info

```Shell
System:
    OS: Windows 11 10.0.22621
    CPU: (6) x64 Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
    Memory: 15.22 GB / 39.93 GB
  Binaries:
    Node: 16.15.0 - D:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - D:\Program Files\nodejs\yarn.CMD
    npm: 8.5.5 - D:\Program Files\nodejs\npm.CMD
    pnpm: 8.6.7 - D:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (120.0.2210.91)
    Internet Explorer: 11.0.22621.1
```

### Used Package Manager

npm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zwying0814** [comment]
same problem

**Comment by devilmark84** [comment]
I see that you need to edit the state to make it save.

**Comment by Yorlg** [comment]
> I see that you need to edit the state to make it save.

What does it mean.

**Comment by Yorlg** [comment]
![image](https://github.com/prazdevs/pinia-plugin-persistedstate/assets/44600060/4cc71057-84a8-4ddb-8098-64de08956310)

Pinia has not been fully loaded yet, causing it to be unreachable during routing. Therefore, I placed the userStore in the routing guard to use persistence.
