### ISSUE TITLE
[core] only hydrate values present in `paths`

### ISSUE THREAD

**Issue by conor-odro** [prazdevs/pinia-plugin-persistedstate#268]
### Clear and concise description of the problem

I'm unsure if it's an intended feature of this plugin or an overlooked "bug", but recently I encountered an issue where I was persisting an entire store to localStorage by accident in a Production app. To remedy this I added the `paths` option to only persist the values I required, however users who already had the entire store in their localStorage (including stale values) are finding the Pinia store being fully hydrated by whats in localStorage rather than just the values present in `paths`.

### Suggested solution

```diff
function hydrateStore(
  store: Store,
-  { storage, serializer, key, debug }: Persistence,
+ { storage, serializer, key, paths, debug }: Persistence,
) {
  try {
    const fromStorage = storage?.getItem(key)
-   if (fromStorage)
-     store.$patch(serializer?.deserialize(fromStorage))
+   if (fromStorage){
+     const deserialisedStorage = serializer?.deserialize(fromStorage);
+     const hydratedObject = Array.isArray(paths) ? pick(deserialisedStorage, paths) : deserialisedStorage;
+     store.$patch(hydratedObject)
+   }
  }
  catch (e) {
    if (debug)
      console.error('[pinia-plugin-persistedstate]', e)
  }
}
```

If you agree with the above solution I'm more than happy to put a PR in for it. Alternatively if this is an intended feature of the plugin then we could add another option to the `Persistence` interface to toggle my new feature on/off as I think other people may also find this useful. 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by havok2063** [comment]
I second this issue, and would like to see the PR for this merged in soon, if possible.  My case is I have `paths` set to persist only certain parameters, but other store variables I need to pass between routes that I don't want persisted, as they regularly update, get persisted since the entire store is persisted.  This PR or implementation of https://github.com/prazdevs/pinia-plugin-persistedstate/issues/109 I think would fix my issue.  @prazdevs

**Comment by prazdevs** [comment]
working on it for v4

**Comment by havok2063** [comment]
Awesome!  That's great to hear.  Do you have a rough idea of when v4 might be released?

**Comment by prazdevs** [comment]
I dont know, it also requires rewriting a lot of doc, but i might release as beta before docs, i'll see.
It will introduce some breaking changes as well so this also needs to be documented. 

I hope to release it during September

**Comment by prazdevs** [comment]
this is now default behaviour in v4
