### ISSUE TITLE
Calling $persist within the store file.

### ISSUE THREAD

**Issue by KarelVendla** [prazdevs/pinia-plugin-persistedstate#270]
### Describe the bug

Is it possible to call $persist within the file?
I have this piece of code

`    if (router.currentRoute.value.query.session_uuid) {
      sessionId.value = router.currentRoute.value.query.session_uuid as string
      router.replace({
        query: {
          ...router.currentRoute.value.query,
          session_uuid: undefined
        }
      })
    }`
    
When the store is loaded within a composable and this value is being set it is overwritten by the cookie's value later.

### Reproduction

Create a store, create a composable. call the store in a composable and try to use the same if statement in your store to set a value.

### System Info

```Shell
nuxt
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by prazdevs** [comment]
I hardly see what you try to achieve, could you provide a proper reproduction with steps ?
