### ISSUE TITLE
How to write pina composite code so that the object inside the store has multiple properties

### ISSUE THREAD

**Issue by dong-lufei** [prazdevs/pinia-plugin-persistedstate#271]
```
export const useUserStore = defineStore( "user", () => {
    // 用户信息
    const userState = reactive({
	    userInfo: {
		    username: "",
		    nickname: "",
	    },
	    token: "",
    })
    // 设置用户信息
    const setUserInfo = (userInfo) => {
	    userState.userInfo = userInfo
    }
    
    // 设置 token
    const setToken = (token) => {
	    userState.token = token
    }
    
    return { userState, setToken, setUserInfo }
  },
  {
    // persist: true, // 整个 Store 配置为持久化，默认 localStorage
    persist:{ paths: ['userState.userInfo.username', 'userState.token'] },
  }
)
```
This is what's stored in browser storage
```
{
    "userState": {
        "userInfo": {
            "username": "teacher_D"
        },
        "token": "2022-10-31T22:04:06.255+08:00"
    }
}
```
I want to store it like this, how do I write pinia code, I don't want to write it as an option, I want to write it as a composition?
```
{
  "userInfo": {
      "username": "teacher_D"
  },
  "token": "2022-10-31T22:04:06.255+08:00"
}
```

**Comment by prazdevs** [comment]
Hi, because `userState` is a reactive object, it is exposed as a key of the whole store. We just use the whole store that pinia creates from the composition as an object and pick paths from it. 
With the current plugin, this is not possible out-of-the-box, but you could try to write a custom storage that removes/flattens objects 🤔

**Comment by dong-lufei** [comment]
beforeRestore and afterRestore don't seem to work, maybe I don't know how to use them
But it seems to work if I use serializer
```
serializer: {
	serialize: state => JSON.stringify(state['userState']),
	deserialize: parseState => ({ userState: JSON.parse(parseState)})
},
```

**Comment by prazdevs** [comment]
beforeRestore and afterRestore are hooks, they are meant to trigger side effects, but not to interact with the storage or the store.

yes serializer should work :)
