### ISSUE TITLE
When I quote pinia-plugin-persistedstate, following the official website method, the page is blank，what's wrong?   The below is code

### ISSUE THREAD

**Issue by 18217219485** [prazdevs/pinia-plugin-persistedstate#273]
### Describe the bug

import { createPinia } from 'pinia'
import piniaPluginPersistedstate from 'pinia-plugin-persistedstate'

const pinia = createPinia();
pinia.use(piniaPluginPersistedstate)

export default pinia

### Reproduction

what

### System Info

```Shell
"pinia": "^2.1.7",
 "pinia-plugin-persistedstate": "2.4.0",
 "vue": "^3.4.15",
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by prazdevs** [comment]
Hi, i do not really understand the issue, could you provide a proper reproduction repo?

Also you are not using the latest version. The latest is `3.2.1`
