### ISSUE TITLE
组件外使用代persist的pinia store ，无法持久化

### ISSUE THREAD

**Issue by jingjingshenye** [prazdevs/pinia-plugin-persistedstate#276]
### Describe the bug

组件外使用代persist的pinia store ，无法持久化

### Reproduction

组件外使用代persist的pinia store ，无法持久化

### System Info

```Shell
组件外使用代persist的pinia store ，无法持久化
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by prazdevs** [comment]
Hi, I need a reproduction repo to investigate. But the persistence outside of components should work because subscription is made in detached mode.

**Comment by Zyunchao** [comment]
我遇到了同样的问题，在组件外使用 pinia store，无法持久化，放到 App.vue 中可以正常持久化。需要的话请见仓库 https://github.com/Zyunchao/vue3-base-admin ，见 router 模块。  @prazdevs 

![WeChat476fb74d4075f82f5cea8c0464466c1a](https://github.com/prazdevs/pinia-plugin-persistedstate/assets/37761144/f9232880-f472-49a6-9f67-3dd548a3aa3f)

**Comment by Zyunchao** [comment]
模块文件：https://github.com/Zyunchao/vue3-base-admin/blob/master/src/router/frontEnd.ts
