### ISSUE TITLE
How to handle this warning? Inconsistent rendering between server and client

### ISSUE THREAD

**Issue by bbhxwl** [prazdevs/pinia-plugin-persistedstate#278]
![image](https://github.com/prazdevs/pinia-plugin-persistedstate/assets/26525599/87f223f5-cea8-4fe6-8308-b55388a35982)

**Comment by prazdevs** [comment]
Hi, to investigate i need a proper reproduction repo.
However this looks like you are using client-side only storages (like localStorage), or the cookie isnt passed properly, or a value is calculated before.

**Comment by bbhxwl** [comment]
> Hi, to investigate i need a proper reproduction repo. However this looks like you are using client-side only storages (like localStorage), or the cookie isnt passed properly, or a value is calculated before.

What I mean is, if I make changes on the server, will I make them twice?

**Comment by prazdevs** [comment]
> > Hi, to investigate i need a proper reproduction repo. However this looks like you are using client-side only storages (like localStorage), or the cookie isnt passed properly, or a value is calculated before.
> 
> What I mean is, if I make changes on the server, will I make them twice?

What happens is data used to generate HTML for the page and sent to the client. Then when it arrives to the client, and JS is hydrated, it is changed (maybe by pinia/storage) and no longer matches what was originally sent by the server, therefore the hydration mismatch.
In other words, if you have SSR/Universal rendering enabled but use localStorage, server generates HTML with the default pinia values, before sending it to the client where it is hydrated with data from the updated pinia (coming from localStorage) and it may not be the default values.

Hope this makes sense, see more here 
https://nuxt.com/docs/guide/concepts/rendering#universal-rendering
