### ISSUE TITLE
reactive([1])   Unable to deserialize properly

### ISSUE THREAD

**Issue by 1514599514** [prazdevs/pinia-plugin-persistedstate#279]
### Describe the bug

`reactive([1])` Defined state
Unable to deserialize properly

Plugin version: "pinia-plugin-persistedstate": "^3.2.1"

Store Code
![image](https://github.com/prazdevs/pinia-plugin-persistedstate/assets/73267079/8f76c44d-dcbc-4715-bdd2-a175b91f4644)

calling code
![image](https://github.com/prazdevs/pinia-plugin-persistedstate/assets/73267079/3da9fdf6-a466-4156-90b8-175004547a8a)

Continuously refresh the page five times
![image](https://github.com/prazdevs/pinia-plugin-persistedstate/assets/73267079/b44360e6-ff7c-4800-9e1a-805c3b28c068)

### Reproduction

a

### System Info

```Shell
a
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by 1514599514** [comment]
I have conducted a simple search on the issue but did not find any relevant issues
From machine translation

简单搜索过issue, 没找到相关问题.

来自机器翻译

**Comment by prazdevs** [comment]
This is most likely related to https://github.com/vuejs/pinia/issues/2410 
You must use `ref` with `Array` types. Also I'd advocate against using  `reactive` at all :)
