### ISSUE TITLE
Save to store after X seconds of no further changes.

### ISSUE THREAD

**Issue by gijsbertpieterbrouwer** [prazdevs/pinia-plugin-persistedstate#280]
### Clear and concise description of the problem

Hi, and Thanx for this great code!

I use pinia for software with many mutations, right now I would want 2 things:

>  Store to dynamic path to store to listitem-1 and a seperate storage path for listitem-2

> Only store to storage after X seconds of inactivity of the path (to avoid many storage moments)

### Suggested solution

A configuration property to allow for deferred storage (only store the last known value)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by prazdevs** [comment]
Hi, I think this is out of scape of the package. It is meant to be basic and sync a storage with the store, adding a debounce would add a lot of complexity and unstability to the code atm.
 Maybe the debounce belongs before the data hits the store. You can also look into plugins like https://github.com/posva/pinia-plugin-debounce
