### ISSUE TITLE
nuxt bug   Cannot read properties of undefined (reading 'sessionStorage')

### ISSUE THREAD

**Issue by bbhxwl** [prazdevs/pinia-plugin-persistedstate#285]
nuxt bug   Cannot read properties of undefined (reading 'sessionStorage')
![image](https://github.com/prazdevs/pinia-plugin-persistedstate/assets/26525599/0dc254a2-cbe4-4edf-98fe-b1997f702db2)

**Comment by prazdevs** [comment]
Please provide a [proper reproduction](https://antfu.me/posts/why-reproductions-are-required).
