### ISSUE TITLE
Automatically set `Vary: Cookie` response header in Nuxt SSR

### ISSUE THREAD

**Issue by rudolfbyker** [prazdevs/pinia-plugin-persistedstate#286]
### Clear and concise description of the problem

As far as I understand, if we use have a cookie that influences the page contents (e.g., a `theme` cookie), then we should also set a `Vary: Cookie` response header. This is what the [cookie storage](https://prazdevs.github.io/pinia-plugin-persistedstate/frameworks/nuxt-3.html#cookieswithoptions) does.

### Suggested solution

Do you think it's within scope of `@pinia-plugin-persistedstate/nuxt` to automatically set the `Vary: Cookie` header when cookie storage is used?

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by prazdevs** [comment]
Just read that now and very sorry for the long delay.

I don't think it can be included on the scope of the plugin/module to interact with request/response headers. If a clean solution can be found, I could consider it ?

**Comment by rudolfbyker** [comment]
Maybe this should be part of `@pinia-plugin-persistedstate/nuxt` but not `pinia-plugin-persistedstate`. Then the clean solution is as simple as this:

```ts
// app/server/middleware/varyCookie.global.ts
export default defineEventHandler((event) => {
  event.node.res.setHeader("Vary", "Cookie");
});
```

**Comment by prazdevs** [comment]
Doing so would mean any request passing through nitro has content depending on cookie, which is not necessarily true. I think this is down to userland to set this or not, but this maybe could be documented 🤔
