### ISSUE TITLE
pinia.use(piniaPersist) in a separate file, causing local storage to fail

### ISSUE THREAD

**Issue by Gasang-Pon** [prazdevs/pinia-plugin-persistedstate#287]
### Describe the bug

**pinia.ts**
![image](https://github.com/prazdevs/pinia-plugin-persistedstate/assets/57746158/a4bd0b04-af9e-456b-8f25-c002aa8c32de)

**main.ts**
![image](https://github.com/prazdevs/pinia-plugin-persistedstate/assets/57746158/24c73758-633b-4910-b0b3-e7132b361644)

The actual test found a problem. You cannot create a separate file, separate createPinia, and then import it into main.js. If pinia.use(piniaPersist) is used in a separate file, the local storage will fail;

### Reproduction

Create a demo

### System Info

```Shell
Browsers
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by wicgee** [comment]
This plug-in what the heck, support pinia so rubbish, but also said that they are pinia plug-ins, fuck, can not last at all, might as well use my vueuse

**Comment by prazdevs** [comment]
Please provide a [proper reproduction](https://antfu.me/posts/why-reproductions-are-required).

**Comment by Gasang-Pon** [comment]
Sorry, could you please create a new project for testing based on my screenshot.
