### ISSUE TITLE
Type safe persist paths

### ISSUE THREAD

**Issue by biesbjerg** [prazdevs/pinia-plugin-persistedstate#292]
### Clear and concise description of the problem

Would be nice to make `paths` be type safe to prevent errors.

```ts
export const usePlayerStore = defineStore("player", () => {
  return {
    keyA: true,
    keyB: true,
    keyC: {
      keyC1: true,
    },
  };
}, {
  persist: {
    paths: ["keyA", "keyb"] // oops, keyB is mis-spelled
  },
});
```

### Suggested solution

You can do this today:

```ts
type FlattenKeys<
  T extends Record<string, unknown>,
  Key = keyof T,
> = Key extends string
  ? T[Key] extends Record<string, unknown>
    ? `${Key}.${FlattenKeys<T[Key]>}`
    : `${Key}`
  : never;

type StateKeys = FlattenKeys<ReturnType<typeof storeFn>>;

function storeFn() {
  return {
    keyA: true,
    keyB: true,
    keyC: {
      keyC1: true,
    },
  };
}

export const usePlayerStore = defineStore("player", storeFn, {
  persist: {
    paths: ["keyA", "keyb", "keyC.keyC1"] satisfies StateKeys[], // Will complain that `keyb` does not exist
  },
});
```

### Alternative

It would be great to have this built-in to Pinia so you wouldn't have to separate the storeFn by it self to be able to get the `ReturnType`.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by prazdevs** [comment]
This is planned someday when i get some time, maybe for v4, as i already made a package for it (see https://github.com/prazdevs/deep-pick-omit)

I'm just overworked and can't spend much time onthe project atm.

**Comment by biesbjerg** [comment]
No worries — thank you for a great plugin! 😊

**Comment by prazdevs** [comment]
Closing this for now as it's soon coming in v4. Current API is type inference but not forced (you get autocompletion for possible values, but no error if using potentially invalid values).
