### ISSUE TITLE
The type of map print in console.log (typeof this.userMap) is object

### ISSUE THREAD

**Issue by xuddgita** [prazdevs/pinia-plugin-persistedstate#295]
### Describe the bug

import { defineStore } from "pinia";
import User from "@/mode/User";
import UserSimple from "@/mode/UserSimple";

export interface State {
  user: User | null;
  userMap: Map<string, UserSimple>;
}

export const useUserStore = defineStore('user_store',{
  state() {
	 return {
		 user: null,
		 userMap: new Map(),
		 count: 0
	 }
  },
  persist: true,
  getters: {},
  actions: {
    setUser(user: User): void {
		this.user = JSON.parse(JSON.stringify(user));
    },
    setCount(): void {
      this.count++;
    },
    storeUser(id: string, user: UserSimple): void {
      console.log(typeof this.userMap)
      this.userMap.set(id, user);
    },
    getUser(): User | null {
      return this.user;
    },
  },
});
The type of map print in console.log (typeof this.userMap) is object

### Reproduction

..

### System Info

```Shell
...
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by prazdevs** [comment]
Please provide a [proper reproduction](https://antfu.me/posts/why-reproductions-are-required).

**Comment by liruisen** [comment]
I encountered the same problem, but after testing it found that it was a data type problem, not a problem with the project. Map and Set will be treated as `{}` when performing JSON.stringify, which is a flaw in js.
