### ISSUE TITLE
Persist for "composition api" style

### ISSUE THREAD

**Issue by a0s** [prazdevs/pinia-plugin-persistedstate#296]
### Describe the bug

Hello! Could you pls provide example how to add persist here?:

```typescript
import { defineStore } from 'pinia'
import { computed, ref } from 'vue'

export const useDebugStore = defineStore('debug', () => {
  const _enabled = ref(false)

  const enabled = computed({
    get: () => _enabled.value,
    set: (value) => {
      _enabled.value = value
    }
  })

  return { enabled, _enabled }
})
```

PS. This plugin looks great and mature (more that 31 versions in past). Vue's composition api also is not something new. Hope i just missed it.

### Reproduction

Example attached

### System Info

```Shell
System:
    OS: macOS 14.4.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 31.72 GB / 96.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.19.1 - /opt/homebrew/opt/node@18/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 10.2.4 - /opt/homebrew/opt/node@18/bin/npm
    bun: 1.0.13 - ~/Library/Application Support/reflex/bun/bin/bun
  Browsers:
    Brave Browser: 123.1.64.113
    Safari: 17.4.1
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by prazdevs** [comment]
Hi you should be fine just using 
```
import { defineStore } from 'pinia'
import { computed, ref } from 'vue'

export const useDebugStore = defineStore('debug', () => {
  const _enabled = ref(false)

  const enabled = computed({
    get: () => _enabled.value,
    set: (value) => {
      _enabled.value = value
    }
  })

  return { enabled, _enabled }
}, {
persist: true
})```

Keep in mind that only ref are translated to state, and the plugin uses subscriptions to mutations (only watching state) for persistence. That means the ref value has to change for a mutation to be triggered and state to be persisted
