### ISSUE TITLE
when to persist and when to recover

### ISSUE THREAD

**Issue by hickiy** [prazdevs/pinia-plugin-persistedstate#300]
### Clear and concise description of the problem

when I use the plugin,  I don‘t know when to persist and when to recover，I need to sure what tiem it  can use

but now , when I referesh the browser,  state persistance is happen after  the reloaded, this is not usefull to me

### Suggested solution

I think  state persistance shoud happen at the event of before unload  and state recover shoud happen after the opportunity of pinia instance created,  and clarify the lifetime in document is best, thanks!

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by prazdevs** [comment]
The behaviour is bound to pinia's. That means: 

- State is saved only after a mutation happens
- Rehydration happens whenever Pinia (and its plugins) is initiated within the app

It will be more documented in the v4 docus. thanks for pointing that out
