### ISSUE TITLE
How to Securely store an object in local storage without storing It as plain object?

### ISSUE THREAD

**Issue by anurag-gautam-maersk** [prazdevs/pinia-plugin-persistedstate#301]
### Clear and concise description of the problem

I want to avoid storing a sensitive object in plain object in the browser's local storage. Is there a way to encrypt the object before saving it to local storage and decrypt it when retrieving it? What are the best practices for securely handling local storage data in this manner?

### Suggested solution

Encryption is enabled based on user preference 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by prazdevs** [comment]
Hi, you _could_ use a custom storage which still saves to localStorage but encrypt/decrypt on set/get, however, i'd still highly discourage you to store any sensitive data on a client device, no matter how encrypted it is :)

**Comment by anurag-gautam-maersk** [comment]
@prazdevs Yes, I agree that sensitive data should not be stored in client storage, but right now we are using `persist: true,`. in store, which is storing all store data on localhost. I would need to store only some properties that I don't want to store, like plane objects. Is there any way I can do some operation before storing and getting from Store.

Thank you in advance.

**Comment by prazdevs** [comment]
There are some examples in #60 :)

**Comment by anurag-gautam-maersk** [comment]
Thank you, @prazdevs for your help.

**Comment by prazdevs** [comment]
closing this as resolved :)
