### ISSUE TITLE
Sync with redis

### ISSUE THREAD

**Issue by martinszeltins** [prazdevs/pinia-plugin-persistedstate#303]
### Describe the bug

It would be really nice to be able to store the pinia state in Redis. I don't understand the limitation of [Storage must be synchronous](https://prazdevs.github.io/pinia-plugin-persistedstate/guide/limitations.html#storage-must-be-synchronous). Why can't we simply trigger a Redis save and load on $subscribe?

### Reproduction

n/a

### System Info

```Shell
n/a
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by prazdevs** [comment]
Hi mutations in Pinia are synchronous, and this plugin uses the `$subscribe` API to react to mutations and save the state. You can still make async calls in a sync function, but you may experience unexpected behaviours, that's why it's not recommended. 

See https://pinia.vuejs.org/core-concepts/state.html#Subscribing-to-the-state

The other way to implement async behavious with Pinia is actions.

**Comment by martinszeltins** [comment]
> Hi mutations in Pinia are synchronous, and this plugin uses the `$subscribe` API to react to mutations and save the state. You can still make async calls in a sync function, but you may experience unexpected behaviours, that's why it's not recommended.
> 
> See [pinia.vuejs.org/core-concepts/state.html#Subscribing-to-the-state](https://pinia.vuejs.org/core-concepts/state.html#Subscribing-to-the-state)
> 
> The other way to implement async behavious with Pinia is actions.

What are potential problems that can occur when making async calls on $subscribe?

**Comment by prazdevs** [comment]
Async calls are not awaited, if two mutations happen successively, the second call may resolve before the first one, resulting in outdated data replacing latest data.

**Comment by martinszeltins** [comment]
> Async calls are not awaited, if two mutations happen successively, the second call may resolve before the first one, resulting in outdated data replacing latest data.

Perhaps this can be solved using timestamps?

````
Last Synced Mutation Time: 2024-05-27T19:34:49 

Mutation: user=john; timestamp=2024-05-27T19:34:49

// Rejected because timestamp is < last synced time
Mutation: user=joh; timestamp=2024-05-27T19:30:49
````

**Comment by prazdevs** [comment]
That could be a workaround for you, but this would be out of scope of the plugin, as we dont support async behaviours and side effects :)
