### ISSUE TITLE
default storage to persistedState.localStorage

### ISSUE THREAD

**Issue by u007** [prazdevs/pinia-plugin-persistedstate#304]
### Clear and concise description of the problem

by default persists: true -> using sessionStorage,
upon refresh, its gone

### Suggested solution

suggest default storage to persistedState.localStorage

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by u007** [comment]
hi. nice
but i realised using cookies store does not work, my store become empty

**Comment by GreyXor** [comment]
> Hi, the default with Nuxt is actually `cookies` as it is an SSR friendly solution. `localStorage` and `sessionStorage` are client-only which may end up in hydration mismatches and unexpected behaviours with Nuxt's default SSR setting :)

Really ? but doc says that default is localStorage : https://prazdevs.github.io/pinia-plugin-persistedstate/guide/config.html#storage

**Comment by prazdevs** [comment]
Not for Nuxt https://prazdevs.github.io/pinia-plugin-persistedstate/frameworks/nuxt-3.html#choosing-a-storage :)

**Comment by u007** [comment]
do you have a vike plugin?

**Comment by prazdevs** [comment]
We only give a plain vue/pinia plugin that is eventually configurable for any framework, or the nuxt module. No plan to support other frameworks atm.
