### ISSUE TITLE
Does not work properly in vue3

### ISSUE THREAD

**Issue by hubeishuaige** [prazdevs/pinia-plugin-persistedstate#305]
### Describe the bug

It is normal in vue3 local project development, but after executing the yarn build packaging and publishing command, this plug-in does not work, and there is no error prompt, as if there is no one

### Reproduction

It is normal in vue3 local project development, but after executing the yarn build packaging and publishing command, this plug-in does not work, and there is no error prompt, as if there is no one
### System Info

```Shell
{
  "name": "robot-bee-admin",
  "version": "0.0.0",
  "private": true,
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "@element-plus/icons-vue": "^2.3.1",
    "axios": "^1.7.2",
    "element-plus": "^2.7.3",
    "nprogress": "^0.2.0",
    "pinia": "^2.1.7",
    "pinia-plugin-persistedstate": "^3.2.1",
    "sass": "^1.77.2",
    "vue": "^3.4.21",
    "vue-router": "^4.3.0"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^5.0.4",
    "vite": "^5.2.8"
  }
}
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by prazdevs** [comment]
Hi please provide a proper reproduction so I can help :)

**Comment by hubeishuaige** [comment]
![image](https://github.com/prazdevs/pinia-plugin-persistedstate/assets/21007762/0f62bcd8-b7a3-46fe-9a99-cf5572f30c0c)
![image](https://github.com/prazdevs/pinia-plugin-persistedstate/assets/21007762/6945209a-a8c1-45c5-abc7-997a334058d8)

**Comment by Dherlou** [comment]
Same problem here. Simple (new) VueJS v3 app using pinia for managing the stores (which just contain a few strings in my case), which works fine by itself.

Then I tried to add this extension and followed the [getting started guide](https://prazdevs.github.io/pinia-plugin-persistedstate/guide/), but no matter what I configure, this extension acts as if it isn't there. Nothing is persisted/loaded, hooks are not called and no debug info is logged. When I try to $persist()/$hydrate() manually, the app tells me that those functions are not defined.

My guess is that the extension is not loaded at all (at least in the way the documentation shows)?

**Comment by lynxionxs** [comment]
Same issue.  Made a barebones Vite+Vue+Pinia app. Then chose ```localStorage``` as storage in the store, but nothing is set in the localStorage.  Calling actions to mutate state also sets nothing in localStorage.

**Comment by Nemure231** [comment]
can confirm, in newest vue3 vite, i only use simple code inside pinia like this, 
`
{
    persist: {
        storage: localStorage,
        paths: ['use-my-fetch-crane']
    }
}`
and its only return empty object like this, i have lot of state in pinia anyway: 

<img width="495" alt="Capture" src="https://github.com/prazdevs/pinia-plugin-persistedstate/assets/49015080/4b685beb-8673-4de7-b229-23c077e593ce">

**Comment by VladiStep** [comment]
> can confirm, in newest vue3 vite, i only use simple code inside pinia like this, ` { persist: { storage: localStorage, paths: ['use-my-fetch-crane'] } }` i have lot of ref() state in pinia, and its only saved empty object like this in localStorage:
> 
> <img alt="Capture" width="495" src="https://private-user-images.githubusercontent.com/49015080/346451476-4b685beb-8673-4de7-b229-23c077e593ce.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyNDAzNTcsIm5iZiI6MTcyMTI0MDA1NywicGF0aCI6Ii80OTAxNTA4MC8zNDY0NTE0NzYtNGI2ODViZWItODY3My00ZGU3LWIyMjktMjNjMDc3ZTU5M2NlLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDE4MTQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5ZDU1NjBlYWYxMDlkZTRiNjE1M2JlNzlhYTAyZjgwYjdmZDI5MzNmYTExZTZjZjc3ZDc3NGVhNDEzZTkwZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y6K23UtP1cdUD92PQdeaLgFn8GigpdAR7_oaj1QFEsw">

Same
