### ISSUE TITLE
Typescript error when defining global options

### ISSUE THREAD

**Issue by Agusdeluca96** [prazdevs/pinia-plugin-persistedstate#306]
### Describe the bug

When trying to set global configuration options via `piniaPluginPersistedstate`, the next typescript error get shown:

![Screenshot 2024-06-04 at 17 28 57](https://github.com/prazdevs/pinia-plugin-persistedstate/assets/18120708/3d204968-2a6c-4c6d-8d32-7b278440db6e)

### Reproduction
https://stackblitz.com/edit/pinia-plugin-persistedstate-ts-error-global-options

### System Info

```Shell
System:
    OS: macOS 14.2.1
    CPU: (11) arm64 Apple M3 Pro
    Memory: 64.17 MB / 18.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 19.8.1 - ~/.nvm/versions/node/v19.8.1/bin/node
    npm: 9.5.1 - ~/.nvm/versions/node/v19.8.1/bin/npm
    pnpm: 8.14.1 - /opt/homebrew/bin/pnpm
  Browsers:
    Brave Browser: 125.1.66.113
    Safari: 17.2.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by prazdevs** [comment]
Please provide a proper reproduction (repo/stackblitz) so I can investigate

**Comment by Agusdeluca96** [comment]
Here is a stackblitz with reproduction (also editing original message to add it): https://stackblitz.com/edit/pinia-plugin-persistedstate-ts-error-global-options

**Comment by prazdevs** [comment]
If you want to pass global options, you must use the plugin factory as such 
```ts
import { createApp } from 'vue';
import { createPinia } from 'pinia';
import { createPersistedState } from 'pinia-plugin-persistedstate';
import './style.css';
import App from './App.vue';

const app = createApp(App);

const pinia = createPinia();
pinia.use(
  createPersistedState({
    key: (id) => `__skeleton__${id}`,
  })
);

app.use(pinia);
app.mount('#app');
```

**Comment by Agusdeluca96** [comment]
My bad, it was pretty clear on de doc! Thank you Sacha!
