### ISSUE TITLE
How to import this library through CDN?

### ISSUE THREAD

**Issue by qianjiachun** [prazdevs/pinia-plugin-persistedstate#310]
I imported pinia by using CDN. I also want to import pinia-plugin-persistedstate, but I don't know how to use it.

**Comment by chengazhen** [comment]
checkout the link https://www.jsdelivr.com/package/npm/pinia-plugin-persistedstate

<img width="921" alt="image" src="https://github.com/user-attachments/assets/41c01c0d-e788-4d13-9d6e-861acaef6d62">

**Comment by qianjiachun** [comment]
tks
