### ISSUE TITLE
Nuxt3使用pinia-plugin-persistedstate/nuxt不生效

### ISSUE THREAD

**Issue by zy598586050** [prazdevs/pinia-plugin-persistedstate#311]
### Describe the bug

nuxt.config.ts中配置如下
```
modules: [
  '@pinia/nuxt',
  '@pinia-plugin-persistedstate/nuxt'
]
```
plugins下pinia.client.ts配置如下
```
import piniaPluginPersistedstate from 'pinia-plugin-persistedstate'
export default defineNuxtPlugin(({ $pinia }) => {
    // @ts-ignore
    $pinia.use(piniaPluginPersistedstate)
})
```
最后在store里配置了，但就是不生效，不知道为什么？？？？？？？
```
import { defineStore } from 'pinia';

interface STATE {
    locale: string;
}

export const useAppStore = defineStore('appStore', {
    state: (): STATE => ({
        locale: 'en',
    actions: {},
    persist: {
        storage: persistedState.localStorage,
        paths: ['locale']
    }
})
```

### Reproduction

[pinia-plugin-persistedstate](https://github.com/zy598586050/persistedstate-bug-demo)

### System Info

```Shell
"@nuxtjs/i18n": "^8.0.0",
"@pinia-plugin-persistedstate/nuxt": "^1.2.0",
"@pinia/nuxt": "^0.5.1",
"nuxt": "^3.12.2",
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by prazdevs** [comment]
Hi to investigate i need a proper reproduction repo/stackblitz.

However, if you use the Nuxt module, you do not need the `pinia.client.ts` plugin as the module already injects the plugin into pinia

**Comment by zy598586050** [comment]
https://github.com/zy598586050/persistedstate-bug-demo

Hello, the above is the smallest unit I reproduced, and it still cannot run without plugins

**Comment by zy598586050** [comment]
Hello,I have already submitted the demo. Could you please help me take a look
Thank you

**Comment by prazdevs** [comment]
Hi, i looked into it and your lockfile seems broken/weird, i deleted it then `npm install` and it worked fine.

**Comment by zy598586050** [comment]
![image](https://github.com/prazdevs/pinia-plugin-persistedstate/assets/17879725/d91265db-f736-4be8-849b-04193acca3b5)

Thank you very much for your answer, but the local storage still hasn't seen it

**Comment by prazdevs** [comment]
Values are only stored in storage when changed (we subscribe to pinia mutation events)

**Comment by zy598586050** [comment]
Thank you.
