### ISSUE TITLE
Nuxt3 'persist' does not exist in type 'DefineStoreOptions'

### ISSUE THREAD

**Issue by zlayine** [prazdevs/pinia-plugin-persistedstate#312]
### Describe the bug

using pinia plugin persistedstate returns this error for me whenever I use persist inside the store and it breaks the whole TS support in pinia

Error:
`Object literal may only specify known properties, and 'persist' does not exist in type 'DefineStoreOptions<"ui", { navTheme: ThemeType; }, {}, { setNavTheme(theme: ThemeType): void; }>'.ts(2353)`

this is my store 

```javascript
import { defineStore } from 'pinia';
import { ThemeType } from '~/types/enum';

export const useUiStore = defineStore({
    id: 'ui',
    state: () => ({
        navTheme: ThemeType.LIGHT,
    }),
    persist: {
        paths: ['navTheme'],
    },
    actions: {
        setNavTheme(theme: ThemeType) {
            this.navTheme = theme;
        },
    },
});
```

my nuxt.config.ts
```
 modules: [
        ...
        '@pinia/nuxt',
        '@pinia-plugin-persistedstate/nuxt',
        ...
]
```
### Reproduction

pinia-plugin-persistedstate

### System Info

```Shell
"@pinia/nuxt": "^0.5.1",
"nuxt": "3.12.2",
"@pinia-plugin-persistedstate/nuxt": "^1.2.0",
"typescript": "^5.3.3",
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by damevin** [comment]
Have you found any solution for this ? 🙏

**Comment by zlayine** [comment]
> Have you found any solution for this ? 🙏

Yes, I have added to tsconfig.json

```
"include": [
        ".nuxt/**/*.ts"
    ],
    ```

**Comment by JessicaSachs** [comment]
Make sure to re-run the Nuxt typegen if you installed via `nuxi`

**Comment by oom-** [comment]
> Make sure to re-run the Nuxt typegen if you installed via `nuxi`
Correct, this fixed the issue for me, here is the command:  `nuxt generate`
