### ISSUE TITLE
Hydration completed but contains mismatches.

### ISSUE THREAD

**Issue by uu-space** [prazdevs/pinia-plugin-persistedstate#313]
### Describe the bug

nuxt3 + pinia + pinia-plugin-persistedstate

Nuxt 3.12.2 with Nitro 2.9.6

Setting
``` js
persist: {
  storage: persistedState.localStorage,
}
```
Error info： _Hydration completed but contains mismatches._
![BFE57BF4FB5FDDBEAF5BAC5CA7076619](https://github.com/prazdevs/pinia-plugin-persistedstate/assets/131173052/67ba870f-8d13-47a6-b40a-e924c8dd6ca7)

Setting ssr:false fixes the problem, but obviously not what I want
Are there any other solutions?

``` js
// nuxt.config.ts
export default defineNuxtConfig({
  // ssr: false,
  devtools: { enabled: true },
  modules: [
    "@nuxtjs/tailwindcss",
    "arco-design-nuxt-module",
    "@pinia/nuxt",
    "@pinia-plugin-persistedstate/nuxt",
  ],
  build: {
    transpile: ["pinia-plugin-persistedstate"],
  },
  css: ["~/assets/css/tailwind.css", "~/assets/css/fonts.css"],
});
```

### Reproduction

Example attached

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i5-12400F       
    Memory: 6.91 GB / 15.84 GB
  Binaries:
    Node: 20.11.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.1.1 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Spartan (44.19041.3570.0), Chromium (126.0.2592.68)
    Internet Explorer: 11.0.19041.3570
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by dearfad** [comment]
Same problem, the answer ?
