### ISSUE TITLE
can not work normally

### ISSUE THREAD

**Issue by wengshuang** [prazdevs/pinia-plugin-persistedstate#314]
<img width="470" alt="image" src="https://github.com/prazdevs/pinia-plugin-persistedstate/assets/80451560/f2e87608-e665-40ff-8a2d-a0435b52ac05">
<img width="661" alt="image" src="https://github.com/prazdevs/pinia-plugin-persistedstate/assets/80451560/cadcad55-f0cd-4184-80a4-c4868a9139be">
<img width="509" alt="image" src="https://github.com/prazdevs/pinia-plugin-persistedstate/assets/80451560/71148b7b-dc4d-4691-a8ce-6eee16b3201d">

i can't find key 'main'  in sessionStorage  or localStorage

**Comment by wengshuang** [comment]
<img width="558" alt="image" src="https://github.com/prazdevs/pinia-plugin-persistedstate/assets/80451560/f408342f-af3d-422f-a153-b8e6a98080d7">

**Comment by chengazhen** [comment]
我想你应该先设置变量吧，尝试修改一下

**Comment by prazdevs** [comment]
As said above, persistence happens only when a mutation happens. 

I could also only look at a proper reproduction repo if an issue was to be.
