### ISSUE TITLE
Update cookiesWithOptions

### ISSUE THREAD

**Issue by alecaceres** [prazdevs/pinia-plugin-persistedstate#315]
### Clear and concise description of the problem

As a developer using this plugin I want to be able to update `cookiesWithOptions` after the cookie has been set so that we can give some room for conditionals.

For example, for a "remember me" feature, we could start with:
```js
persist: {
  key: STORAGE_KEY,
  storage: persistedState.cookiesWithOptions({
    sameSite: "strict",
  }),
}
```

but then, based on user's preference, we may want to set the option `maxAge` to, let's say, `60 * 60 * 24 * 30`

### Suggested solution

I have managed to change the `maxAge` attribute by creating and running an action like this:

```js
const options = {
  sameSite: 'strict',
  maxAge: this.keepSignedIn ? 60 * 60 * 24 * 30 : undefined,
};
const authCookie = useCookie(STORAGE_KEY, options);
authCookie.value = this.$state;
```

For this to be effective though, I had to run it from a `beforeRestore` hook
```js
beforeRestore: (ctx) => {
  ctx.store.updateCookies()
}
```

something like this:
```js
const store = useStore()
store.persistedState.options = {...}
// or
store.updateCookiesOptions({...})
```
should work

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by prazdevs** [comment]
I get the idea, but this has been discussed already in some other issue , and having options depending on state and changing within the lifetime of the store isnt considerable at the moment. It would implies lots of potential side effects and seems out of the scope of the plugin.
