### ISSUE TITLE
why i can't import in nuxt3 

### ISSUE THREAD

**Issue by Golong-me** [prazdevs/pinia-plugin-persistedstate#317]
### Describe the bug

config
```
export default defineNuxtConfig({
    modules: [
        '@pinia/nuxt', 
        '@pinia-plugin-persistedstate/nuxt',
    ],
})
```

![1](https://github.com/prazdevs/pinia-plugin-persistedstate/assets/72813193/1e14aef3-2b3e-46fd-be12-b424ad165097)

### Reproduction

see describe

### System Info

```Shell
"dependencies": {
    "nuxt": "^3.12.2",
    "pinia": "^2.1.7",
    "vue": "latest"
  }, 

"devDependencies": {
    "@element-plus/nuxt": "^1.0.9",
    "@pinia-plugin-persistedstate/nuxt": "^1.2.1",
    "@pinia/nuxt": "^0.5.1",
    "element-plus": "^2.7.6",
    "sass": "^1.77.6"
  }
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by prazdevs** [comment]
these imports are auto-imports from Nuxt and imported from `#imports`  .

also, if you need further investigation please provide a proper reproduction repo 🫡

**Comment by Golong-me** [comment]
i fix it 
you neet add this code in nuxt
```
export default defineNuxtConfig({
  modules: ['@pinia/nuxt', '@pinia-plugin-persistedstate/nuxt'],
  build: {
    transpile: ['pinia-plugin-persistedstate'],
  },
});

```
