### ISSUE TITLE
It's not clear from the docs that Nuxt 3 uses cookies as the default storage State

### ISSUE THREAD

**Issue by udit99** [prazdevs/pinia-plugin-persistedstate#319]
### Clear and concise description of the problem

The main docs of the plugin state that the default storage medium is localStorage but actually on Nuxt that is not true: It uses cookies there.

### Suggested solution

We add a (" *Except Nuxt") caveat to the main docs with a link to this: https://prazdevs.github.io/pinia-plugin-persistedstate/frameworks/nuxt-3.html#choosing-a-storage

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by prazdevs** [comment]
Planned in v4 to be clearer in the docs and have more links to either plain vue or nuxt usage 🫡
