### ISSUE TITLE
Can you add local storage such as indexDB? If you can, that would be great

### ISSUE THREAD

**Issue by yangcheng0111** [prazdevs/pinia-plugin-persistedstate#320]
### Clear and concise description of the problem

我想要在storage配置中可以使用indexDB等更大的本地存储

### Suggested solution

我想要在storage配置中可以使用indexDB等更大的本地存储

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by zhaohuanlei** [comment]
希望添加indexDB支持

**Comment by prazdevs** [comment]
Hi, IndexedDB is asynchronous and offers no possibility for sync behaviours. So it's out of the scope of the plugin.

You will need to use actions and handle the logic on your own to use IndexedDB 😞
