### ISSUE TITLE
Persist multiple stores using pinia-plugin-persistedstate in nuxt3

### ISSUE THREAD

**Issue by Tinajose1996** [prazdevs/pinia-plugin-persistedstate#321]
### Describe the bug

As per nuxt3 doc, we can have multiple stores. How can we persist all this stores in single key in localstorage. i can only save the stores with separate keys. How can i solve this case

### Reproduction

NO

### System Info

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i5-1240P
    Memory: 4.27 GB / 15.73 GB
  Binaries:
    Node: 20.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.8.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by prazdevs** [comment]
This is not possible out of the box, and not planned to be supported to fir the "modular"  and isolated philosophy of pinia.

However this should be achievable with a custom storage/serializer combo.
