### ISSUE TITLE
How to make persist work with composition api + typescript?

### ISSUE THREAD

**Issue by shizzic** [prazdevs/pinia-plugin-persistedstate#326]
I found this example:
```JS
import { defineStore } from 'pinia'

export const useSettingsStore = defineStore(
  'settings',
  () => {
    const locale: string = 'RU'
    return { locale }
  },
  {
    persist: true
  }
)
```
But i don't see settings in localstorage. What am i doing wrong?

**Comment by prazdevs** [comment]
There is no proper reproduction, but i can already tell that it's normal nothing is persisted:

With setup stores, only `ref` are considered like `state` (and `computed` are like `getters`). Since the plugin saves `ref`s on mutation, this is why.
