### ISSUE TITLE
[nuxt] use in middleware with redirects

### ISSUE THREAD

**Issue by chendaozhun** [prazdevs/pinia-plugin-persistedstate#328]
### Are you using Nuxt?

- [ ] Check this box if you encountered the issue using Nuxt and the included module.

### Describe the bug

A composable that requires access to the Nuxt instance was called outside of a plugin, Nuxt hook, Nuxt middleware, or Vue setup function. This is probably not a Nuxt bug

https://stackblitz.com/edit/nuxt-starter-nrfxlc?file=README.md

### Reproduction

Mac OS

### System Info

```Shell
Mac OS
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by PDieE** [comment]
same mistake

**Comment by prazdevs** [comment]
Ok thank you for the very clean repro, i will try to look into it and get better cookie parsing/writing to see what happens when i get some time 😌

**Comment by prazdevs** [comment]
hopefully should work better in 4.0.2

**Comment by chendaozhun** [comment]
I have verified，thanks!!
