### ISSUE TITLE
Docs / ReadMe needs updating to avoid downloading the wrong plugin

### ISSUE THREAD

**Issue by BenJackGill** [prazdevs/pinia-plugin-persistedstate#33]
At the moment your docs say "Install with your favourite package manager (pnpm, npm, yarn)."

But because of many similar named packages it's easy to download the wrong one.

For example, these are all wrong, but have almost identical names. There are many more than these 3 examples:

- https://www.npmjs.com/package/pinia-plugin-persistedstate-2
- https://www.npmjs.com/package/pinia-plugin-persist
- https://www.npmjs.com/package/pinia-persistedstate

To stop people downloading the wrong plugin I suggest you add links to the correct packages on your read me page instead of letting people search for the correct one.

For example: https://www.npmjs.com/package/pinia-plugin-persistedstate

Or just add the correct download command directly on the docs `npm i pinia-plugin-persistedstate`.

Thanks for such a great plugin. This is just my 2 cents to make things easier :)

**Comment by prazdevs** [comment]
That's actually true, I'll do this later today, thanks for the consideration! :)
