### ISSUE TITLE
Nuxt3 my persist sets different storage modes and fails

### ISSUE THREAD

**Issue by liaow-ww** [prazdevs/pinia-plugin-persistedstate#331]
### Are you using Nuxt?

- [X] Check this box if you encountered the issue using Nuxt and the included module.

### Describe the bug

"@pinia-plugin-persistedstate/nuxt": "1.2.1",
   "pinia": "2.2.0",
    "nuxt": "3.9.3",
    "vue": "3.4.3"

Recently, my localStorage and sessionStorage settings for storage failed, which had been working fine before.They all are set to localStorage

this is my config:

persist: [
    {
      paths: ['ip', 'langs'],
      storage: persistedState.localStorage
    },
    {
      paths: ['dialogType'],
      storage: persistedState.sessionStorage
    },
    {
      paths: ['sortType', 'cookiePolicy'],
      storage: persistedState.cookiesWithOptions({ expires: new Date(new Date().getTime() + 365 * 24 * 60 * 60 * 1000) })
    }
  ]

### Reproduction

https://stackblitz.com/edit/nuxt-starter-gsr2f4?file=store%2Fapp.ts

### System Info

```Shell
Win
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by prazdevs** [comment]
Hi can you please try with the latest nuxt module included in the base package v4 ?

https://prazdevs.github.io/pinia-plugin-persistedstate/frameworks/nuxt.html

**Comment by liaow-ww** [comment]
> Hi can you please try with the latest nuxt module included in the base package v4 ?
> 
> https://prazdevs.github.io/pinia-plugin-persistedstate/frameworks/nuxt.html

thanks your reply, i solved this issues,  it may be because the latest version of pinia-plugin-persistedstate renamed the paths to pick, i fixed it and now it works.

**Comment by prazdevs** [comment]
This is probably due to cache ? I remade the docs from scratch to match v4. Sadly they are english only, this is maybe why you get 404 if you try to look for Chinese docs.

I will put a message to look for contributors willing to help translate the docs 🫡 

Closing this as fixed!

**Comment by liaow-ww** [comment]
> This is probably due to cache ? I remade the docs from scratch to match v4. Sadly they are english only, this is maybe why you get 404 if you try to look for Chinese docs.
> 
> I will put a message to look for contributors willing to help translate the docs 🫡
> 
> Closing this as fixed!

yes, Chinese docs is 404, thank for your reply again~  but i think that issues is not due to cache,  this is because the parameter paths was renamed to pick, which caused it to fail.

**Comment by prazdevs** [comment]
Oh yes, i meant cache for the docs, not the plugin :)

It has been documented in the docs that `paths` is now `pick` because you can also exclude/omit paths in v4 🎉
