### ISSUE TITLE
falsy values not persisted when using pick

### ISSUE THREAD

**Issue by JimCronqvist** [prazdevs/pinia-plugin-persistedstate#333]
### Are you using Nuxt?

- [ ] Check this box if you encountered the issue using Nuxt and the included module.

### Describe the bug

Falsy values are not persisted when using pick, but rather filtered away.

Relevant configuration:

`persist: { pick: ['selectedIndex'] }`

If the value for `selectedIndex` is `0`, the selectedIndex would not be persisted.

From what I can see, this is caused by this line below which filters away falsy values.
https://github.com/prazdevs/deep-pick-omit/blob/f71e364a33fd2eb1ce8c0e71b2788f4abe8cee67/src/index.ts#L29

Is it possible to retain those values instead? (probably doesn't matter, but Vuex did keep those and made the upgrade unexpected)

Happy to create a PR in that library for the actual change if it helps, but I wanted to check first unless this was intended behavior.

Thanks for all your work on the plugin!

### Reproduction

n/a

### System Info

```Shell
n/a
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by prazdevs** [comment]
That's not really intended, check should be indeed more precise and only check for undefined, not falsy values. Feel free to open an issue / PR on the upstream repo. Just gotta make sure everything still works as expected 🫡

**Comment by dixhuit** [comment]
Any particular reason why OP's PR can't be merged?

**Comment by sev060** [comment]
I'm having this problem too. Are you planning on fixing it soon?
