### ISSUE TITLE
Documentation: Add notice that cookie size is limited to 4096 bytes

### ISSUE THREAD

**Issue by Wafje** [prazdevs/pinia-plugin-persistedstate#341]
### Clear and concise description of the problem

Using Nuxt, [pinia-plugin-persistedstate](https://github.com/prazdevs/pinia-plugin-persistedstate) defaults to Cookies.
As cookie size is limited to 4096 bytes; when the store contains to much information, no cookie will be set.

### Suggested solution

Add notice to documentation about this limitation

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Wafje** [comment]
This one scratched my head for a couple of hours.

**Comment by Jao8** [comment]
That would be great! I lost a lot of time trying to understand why a specific store wasn't persisting, and if it hadn't been for this issue, I would still be pursuing it.
