### ISSUE TITLE
Pinia persists state by setting all state data in cookies, with the option to use a specific key.

### ISSUE THREAD

**Issue by manafatech** [prazdevs/pinia-plugin-persistedstate#342]
### Are you using Nuxt?

- [x] Check this box if you encountered the issue using Nuxt and the included module.

### Describe the bug

We are encountering an issue where, when the user sets a specific key like `auth` in `defineStore` with the persist option the browser stores the entire state in cookies. Please address this issue.

```
export const useAuthStore = defineStore('auth', {
  state: () => {
    return {
        token: null,
        userName:  "",
        isAuthenticate: "",
    }
  },
  persist: {
    key: 'auth',
    paths: [
      'token',
    ],
    debug: true,
  },
})

```

![Screenshot from 2024-10-10 15-41-36](https://github.com/user-attachments/assets/31e68afb-fc31-474e-9db3-5228b5d10b46)

### Reproduction

no

### System Info

```Shell
Operating System

Ubuntu 24.04.1 LTS

nuxt version
3.12.4

node version
v20.16.0

npm version
10.8.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by prazdevs** [comment]
Hi, please provide a proper reproduction at first. Also please refer to the documentation as `paths` does not exist anymore and has been replaced by `pick` and `omit`.
