### ISSUE TITLE
An error is reported when using a plug-in in Vite

### ISSUE THREAD

**Issue by 4uansi** [prazdevs/pinia-plugin-persistedstate#344]
### Are you using Nuxt?

- [ ] Check this box if you encountered the issue using Nuxt and the included module.

### Describe the bug

✘ [ERROR] Could not resolve "destr"

    node_modules/pinia-plugin-persistedstate/dist/index.js:2:22:
      2 │ import { destr } from "destr";
        ╵                       ~~~~~~~

  You can mark the path "destr" as external to exclude it from the bundle, which will remove this
  error and leave the unresolved path in the bundle.

✘ [ERROR] Could not resolve "deep-pick-omit"

    node_modules/pinia-plugin-persistedstate/dist/index.js:5:47:
      5 │ import { deepOmitUnsafe, deepPickUnsafe } from "deep-pick-omit";
        ╵                                                ~~~~~~~~~~~~~~~~

  You can mark the path "deep-pick-omit" as external to exclude it from the bundle, which will
  remove this error and leave the unresolved path in the bundle.

### Reproduction

import {createPinia} from 'pinia' import piniaPluginPersistedstate from 'pinia-plugin-persistedstate'  const store = createPinia() store.use(     piniaPluginPersistedstate )  export default store

### System Info

```Shell
mac
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by prazdevs** [comment]
Please provide a proper reproduction repository or stackblitz. Otherwise issues won't be investigated/fixed. Ty

**Comment by 4uansi** [comment]
Here's my code:https://github.com/4uansi/test.git

**Comment by aaronchen233** [comment]
加个.npmrc内容是shamefully-hoist=true就行了
