### ISSUE TITLE
An error is reported when using a plug-in in the UniApp framework

### ISSUE THREAD

**Issue by 4uansi** [prazdevs/pinia-plugin-persistedstate#345]
### Are you using Nuxt?

- [ ] Check this box if you encountered the issue using Nuxt and the included module.

### Describe the bug

<img width="834" alt="image" src="https://github.com/user-attachments/assets/ca10f4d2-6763-4cb8-a0ec-3b8d1c39c919">

### Reproduction

This is the project address：https://github.com/4uansi/test.git

### System Info

```Shell
MACOS
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by prazdevs** [comment]
I cannot access the repo, is it public ? 🤔

**Comment by aaronchen233** [comment]
用的是pnpm吧，加个.npmrc内容是shamefully-hoist=true就行了

**Comment by 4uansi** [comment]
> 用的是pnpm吧，加个.npmrc内容是shamefully-hoist=true就行了

是的，成功解决啦，谢谢

**Comment by prazdevs** [comment]
great closing this 🎉
