### ISSUE TITLE
I can't recreate the "References do not persist" issue

### ISSUE THREAD

**Issue by BenJackGill** [prazdevs/pinia-plugin-persistedstate#35]
I am trying to recreate the [References do not persist](https://github.com/prazdevs/pinia-plugin-persistedstate#references-do-not-persist) issue to better understand it.

So I made this real world scenario with the object stored in state and then assigned to a const.

**`src/store/test.ts`**
```ts
import { defineStore } from 'pinia';

interface Test {
  1: string;
  2: string;
}

export const useTestStore = defineStore('test', {
  state: () => {
    return {
      test: {} as Test,
    };
  },
  actions: {
    setTest(test: Test) {
      this.test = test;
    },
  },
  persist: true,
});
```

**`src/components/SomeComponent.vue`**
```Vue
<template>
  <div>Test Component</div>
</template>

<script setup lang="ts">
import { useTestStore } from 'src/store/test';
const testStore = useTestStore();
testStore.setTest({
  1: 'one',
  2: 'two',
});
const b = testStore.test;
console.log(testStore.test === b); // always returns true, even after page refresh
</script>
```
From the issue description, I thought the `console.log()` would return `false` after page refresh. But it always returns `true`. So it seems the issue is not actually a problem at all?

So I can understand this better, are you able to give a code example of the "References do not persist" issue when using the Pinia store? The code example in the docs doesn't involve the Pinia store at all so I'm not sure how it applies to this Pinia plugin.

**Comment by prazdevs** [comment]
It's a very specific issue, and I dont see it happening a lot. But the thing is having a state variable referencing another one. When deserialized, they lose the "passed as reference" javascript part.

```
const a = { prop1: 'a' }
const b = { a }
```
if you change `a.prop1`, `b.a.prop1` will also be changed since it's an object, so passed as reference.
Let's say you save both a and b as pinia state. The reactivity will keep this reference, keeping the same interaction by changing `a.prop1`.
But the serialization/deserialization process that happens during persistence breaks this reference as it recreates both `a` and `b` from their values at storage time instead of their references (in case they were).
Does that make more sense ?

**Comment by BenJackGill** [comment]
I think I understand it conceptually, but I can't reproduce it in code.

Can you show a working example using a Pinia store?

Here is my second attempt based on your reply:

**`src/store/test.ts`**
```ts
import { defineStore } from 'pinia';

export const useTestStore = defineStore('test', {
  state: () => {
    return {
      a: { prop1: 'a' },
      b: {},
    };
  },
  persist: true,
});
```
**`src/components/SomeComponent.vue`**
```Vue
<template>
  <div>Some Component</div>
</template>

<script setup lang="ts">
import { useTestStore } from 'src/store/test';
const testStore = useTestStore();
testStore.b = testStore.a;
testStore.a.prop1 = 'c';
console.log(testStore.a); // Returns {prop1: 'c'}, even after page refresh
console.log(testStore.b); // Returns {prop1: 'c'}, even after page refresh
</script>
```

**Comment by BenJackGill** [comment]
Figured it out!

**`src/store/test.ts`**
```ts
import { defineStore } from 'pinia';

export const useTestStore = defineStore('test', {
  state: () => {
    return {
      a: { prop1: 'a' },
      b: {},
    };
  },
  //persist: true,
});
```
**`src/components/SomeComponent.vue`**
```
<template>
  <div>{{ testStore.a }}</div>
  <div>{{ testStore.b }}</div>
  <button @click="handleUpdate1">Update 1</button>
  <button @click="handleUpdate2">Update 2</button>
</template>

<script setup lang="ts">
import { useTestStore } from 'src/store/test';
const testStore = useTestStore();
const handleUpdate1 = () => {
  testStore.b = testStore.a;
  testStore.a.prop1 = 'c';
};
const handleUpdate2 = () => {
  testStore.a.prop1 = 'd';
};
</script>
```
In this example first clicking Update 1 will make both `testStore.a` and `testStore.a` show as `{prop1: 'c'}`. At this moment the references are linked.

Then click Update 2. Both `testStore.a` and `testStore.a` will show as `{prop1: 'd'}` because the references are linked.

But try it again, and this time refresh the page before clicking Update 2 button. The page refresh breaks the reactivity and now `testStore.a` shows `{prop1: 'c'}` while `testStore.a` shows `{prop1: 'd'}`. This is because the reference between the objects was broken during page refresh (due to serialization).

And FYI for anyone else reading later on, there is another persist state method using a watch like so: 
```ts
watch(pinia.state, (state) => {
  localStorage.setItem('state', JSON.stringify(state)
}, { deep: true })
```

This also has the exact same issue because `JSON.stringify(state)` also breaks the reactivity.

**Comment by prazdevs** [comment]
There are actually lots of ways to store a Pinia state into an external storage. I could also recommend using VueUse's functions directly in the Pinia state declaration.
The idea of the plugin is to replicate `vuex-persistedstate` with a consistent and easy to use API.
Closing this now. Feel free to reopen if you need more infos :)
