### ISSUE TITLE
Plugin not compatible with Vue 3.5.12

### ISSUE THREAD

**Issue by antoci-alin** [prazdevs/pinia-plugin-persistedstate#351]
### Are you using Nuxt?

- [x] Check this box if you encountered the issue using Nuxt and the included module.

### Describe the bug

`npm install pinia`

**Results:**
npm error code ERESOLVE
npm error ERESOLVE could not resolve
npm error
npm error While resolving: my-edenred@4.0.0
npm error Found: vue@3.5.12
npm error node_modules/vue
npm error   peer vue@"^3.3.4" from @nuxt/vite-builder@3.13.2
npm error   node_modules/@nuxt/vite-builder
npm error     @nuxt/vite-builder@"3.13.2" from nuxt@3.13.2
npm error     node_modules/nuxt
npm error       nuxt@"^3.13.0" from the root project
npm error   peer vue@"^2.6.14 || ^3.3.0" from pinia@2.2.4
npm error   node_modules/@pinia/nuxt/node_modules/pinia
npm error     pinia@"^2.2.3" from @pinia/nuxt@0.5.5
npm error     node_modules/@pinia/nuxt
npm error       @pinia/nuxt@"^0.5.5" from the root project
npm error   13 more (vue-demi, @primevue/core, @unhead/vue, ...)
npm error
npm error Could not resolve dependency:
npm error pinia@"*" from the root project
npm error
npm error Conflicting peer dependency: vue@2.6.14
npm error node_modules/vue
npm error   peer vue@">= 2.5 < 2.7" from @vue/composition-api@1.7.2
npm error   node_modules/@vue/composition-api
npm error     peerOptional @vue/composition-api@"^1.4.0" from pinia@2.2.4
npm error     node_modules/pinia
npm error       pinia@"*" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.

### Reproduction

npm install pinia

### System Info

```Shell
System:
    OS: macOS 15.0.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 83.88 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.18.0 - ~/.nvm/versions/node/v20.18.0/bin/node
    npm: 10.8.2 - ~/.nvm/versions/node/v20.18.0/bin/npm
  Browsers:
    Chrome: 130.0.6723.70
    Safari: 18.0.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by prazdevs** [comment]
Please provide a proper reproduction. Also the error you sent does not even mention the plugin, so I have absolutely 0 idea what the problem is/could be.

**Comment by Sngt25** [comment]
Add this to the package.json.

`"overrides": {
  "vue": "latest"
}`

[https://pinia.vuejs.org/ssr/nuxt.html](url)
