### ISSUE TITLE
Current version of Nuxt plugin not compatible with @pinia/nuxt 0.7.0

### ISSUE THREAD

**Issue by Belphemur** [prazdevs/pinia-plugin-persistedstate#354]
### Are you using Nuxt?

- [X] Check this box if you encountered the issue using Nuxt and the included module.

### Describe the bug

When using pnpm as package manager I had the @pinia/nuxt plugin version updated to `0.7.0`.

When that happened I started to get error like:
`vueDemi2.effectScope is not a function`.

When going down the rabbit hole, I found the issue `pinia-plugin-persistedstate/nuxt` is put to be compatible only with version `0.5.0` of @pinia/nuxt .

Could you update the `pinia-plugin-persistedstate/nuxt` to be based on `@pinia/nuxt 0.7.0` ?

### Reproduction

Using pnpm install conflicting version of plugins. Make a prod build of the application, encounter the error.

### System Info

```Shell
System:
    OS: macOS 14.7
    CPU: (10) arm64 Apple M1 Max
    Memory: 77.59 MB / 64.00 GB
    Shell: 3.7.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 22.11.0 - ~/.local/share/nvm/v22.11.0/bin/node
    Yarn: 1.22.21 - /opt/homebrew/bin/yarn
    npm: 10.9.0 - ~/.local/share/nvm/v22.11.0/bin/npm
    pnpm: 9.12.3 - ~/.local/share/nvm/v22.11.0/bin/pnpm
    bun: 1.1.21 - /opt/homebrew/bin/bun
  Browsers:
    Chrome: 130.0.6723.92
    Safari: 18.0.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by prazdevs** [comment]
While this is not a valid reproduction (please read the issue and related articles), this seems to not be an issue with the plugin. I just tried and have 4.1.2 working with `@pinia/nuxt@0.7.0`, so maybe your lockfile is borked and there is some version dupe.

I'd happily investigate a proper reproduction (repo/stackblitz) so I can have the same error because I dont have it on my side.

**Comment by Sngt25** [comment]
If you're using npm, add this to the package.json.
`
"overrides": {
  "vue": "latest"
}
`

[https://github.com/prazdevs/pinia-plugin-persistedstate/issues/354](url)

**Comment by phuongduyphan** [comment]
I also encounter the same issue

**Comment by thylaakari** [comment]
I have same issue
