### ISSUE TITLE
bump @pinia/nuxt version for "@pinia-plugin-persistedstate/nuxt module project

### ISSUE THREAD

**Issue by cedric-legallo** [prazdevs/pinia-plugin-persistedstate#358]
### Clear and concise description of the problem

The "@pinia-plugin-persistedstate" is correctly depending on : 
`"peerDependencies": {
    "@pinia/nuxt": ">=0.5.0",
    "pinia": ">=2.0.0"
  },`

But the The "@pinia-plugin-persistedstate/nuxt" module is depending on : 
` "peerDependencies": {
    "@pinia/nuxt": "^0.5.0"
  },`

So we can't upgrade our project to @pinia/nuxt to 0.6.1 (or 0.7.0)

(I did not read the contributing guide, it is currently a 404)

### Suggested solution

update peerDependencies in the nuxt module sources and release a new patch

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by prazdevs** [comment]
Hi the `@pinia-plugin-persistedstate/nuxt` package is deprecated, the Nuxt module is now integrated in the `pinia-plugin-persistedstate` base package, see here https://prazdevs.github.io/pinia-plugin-persistedstate/frameworks/nuxt.html

**Comment by cedric-legallo** [comment]
Thanks for the very quick answer
