### ISSUE TITLE
Argument of type 'void' is not assignable to parameter of type 'PiniaPlugin'

### ISSUE THREAD

**Issue by fkdp06** [prazdevs/pinia-plugin-persistedstate#362]
### Are you using Nuxt?

- [ ] Check this box if you encountered the issue using Nuxt and the included module.

### Describe the bug

In Vue-TS project the following give an error:
``` ts
import { createPinia } from 'pinia';
import createPersistedState from 'pinia-plugin-persistedstate'
const pinia = createPinia();
pinia.use(createPersistedState({ storage: sessionStorage })); // Compile Error
app.use(pinia);
```

Error:
```
Argument of type 'void' is not assignable to parameter of type 'PiniaPlugin'.ts(2345)
```

I was using the following docs: https://prazdevs.github.io/pinia-plugin-persistedstate/guide/advanced.html#global-persistence-options

![image](https://github.com/user-attachments/assets/434dae35-3672-40e6-8985-8bb07b183235)

### Reproduction

https://codesandbox.io/p/devbox/c2nvhp?file=%2Fsrc%2Fmain.ts

### System Info

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (4) x64 Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz
    Memory: 13.19 GB / 23.92 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.2.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.1.3 - ~\AppData\Local\pnpm\pnpm.CMD
  Browsers:
    Edge: Chromium (130.0.2849.56)
    Internet Explorer: 11.0.22621.3527
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by prazdevs** [comment]
Hi, the default export is an already configured plugin, if you want to create one, you want to use the named export:

```ts 
import { createApp } from "vue";
import { createPinia } from "pinia";
import { createPersistedState } from "pinia-plugin-persistedstate";
import "./style.css";
import App from "./App.vue";

const app = createApp(App);

// Init Pinia

const pinia = createPinia();
pinia.use(createPersistedState({ storage: sessionStorage }));
app.use(pinia);

app.mount("#app");
```
also i recommend grouping imports at the top

**Comment by fkdp06** [comment]
Thanks
