### ISSUE TITLE
packaging failed.

### ISSUE THREAD

**Issue by moxunjingmu** [prazdevs/pinia-plugin-persistedstate#44]
Hello, I used your project in the vue3 project, but the packaging failed.
Terminal say 'Cannot find module 'nuxt3/dist/app/composables/cookie' or its cor
3 import { CookieOptions, CookieRef } from 'nuxt3/dist/app/composables/cookie';'
I found that this project didn't delete' CreateNuxtPersistent State' when I didn't use it.So I deleted it manually.Then my project is packed normally.

**Comment by prazdevs** [comment]
woops, realised what was wrong. since we don't really need the types from nuxt-cookie, I stubbed the part we use to keep the 0 dependency.
v1.5.1 should not have the issue. sorry for the inconvenience
