### ISSUE TITLE
Does this plugin works with Pinia < v1?

### ISSUE THREAD

**Issue by romain130492** [prazdevs/pinia-plugin-persistedstate#47]
## Description

* I'm wondering if this plugin works with Pinia < v1?
* I could not find any cases in the documentation,

Thank you

**Comment by prazdevs** [comment]
Hi, it wasnt meant to work with Pinia v1. (actually this plugin was created because there was no plugin compatible with v2 at the time). It is not properly explained in the documentation but stated in the `peerDependencies` with `"pinia": ">=2.0.0"`

**Comment by romain130492** [comment]
i see, do you know any plugin that could work with pinia < v1 @prazdevs ?
thank you

**Comment by prazdevs** [comment]
I never used pinia<1  as they were not considered stable, and I would definitely not recommend using it for this reason.
My guess if you want something that works is to look into older pinia documentation, and take inspiration from this plugin to create a local plugin and persist data in your project.
