### ISSUE TITLE
BUG not support Cyrillic words 

### ISSUE THREAD

**Issue by andysay** [prazdevs/pinia-plugin-persistedstate#49]
<img width="411" alt="Снимок экрана 2022-03-19 в 21 25 15" src="https://user-images.githubusercontent.com/5610952/159133832-ec7c8ed0-d949-4c17-a88b-247133a22f2e.png">

if data have Cyrillic words return this ^

**Comment by prazdevs** [comment]
Can you provide a repo to reproduce ?  According to what i'm seeing, are you using Nuxt ?  Or cookie storage ?

**Comment by andysay** [comment]
i'm using nuxt with cookie 
```

export const useAuth = defineStore({
  id: "auth",
  state: (): AppState => ({
    user: null,
    token: null

  }),
  persist: true,
  getters: {
    authenticated: ({ user }) => user !== null,
    userData() {
      return this.user
    }
  },
actions: {
    async login(email, password) {

      try {
        let q = await axios.post("/api/auth", {
          strategy: "local",
          email: email,
          password: password,
        });
        console.log(q.data.data.user)
        this.user = q.data.data.user
        this.token = q.data.data.accessToken
        return q
      } catch (error) {
        return error
        // this.$toast.error(`Error`, { position: "top" });
      }

    },
```

in q.data.data.user have Cyrillic word like "fistname : "Ваня" will return that error if will be "firstname: "Vano" will be fine

**Comment by prazdevs** [comment]
Hi, this error originates from `cookie-es` (underlying implementation of cookies used in Nuxt) checking the value before serializing.

It will match the value with the following RegExp `/^[\u0009\u0020-\u007e\u0080-\u00ff]+$/` ([source](https://github.com/unjs/cookie-es/blob/main/src/index.ts#L21)).
And obviously raise the error `'argument val is invalid'` that you are reading in the console ([source](https://github.com/unjs/cookie-es/blob/main/src/index.ts#L89))

You should seek encoding these values before serialization.

**Comment by andysay** [comment]
let test = encodeURIComponent(JSON.stringify(array))
        console.log(decodeURIComponent(test))
will be ok!

**Comment by prazdevs** [comment]
@andysay you can use the Serialier option to "augment" the JSON.parse/stringify :)
