### ISSUE TITLE
how to make state as an initialize value?

### ISSUE THREAD

**Issue by MikeAndDove** [prazdevs/pinia-plugin-persistedstate#51]
hello,i want to know how to make persist state as default.
now, i must do something change in state,that can be effected in local or session storage

**Comment by prazdevs** [comment]
hi, currently there is no proper way to force the state to be persisted even without being modified. There is no proper use for it as initial state will always be rehydrated if there is no persisted state. If you have a proper use case for it though, i can always look to implement it

**Comment by prazdevs** [comment]
closing this for now, feel free to reopen if you have a good usecase and implementation for this. :)

**Comment by cdmoro** [comment]
Hello there, to persist the state when the app first loads, I use `store.$dispatch({})` inside `onMounted` hook in `App.vue` file. The empty dispatch call doesn't modify the state and triggers the function to persist the state. Hope that helps.

**Comment by BeardedBear** [comment]
Hi all !

after having had the case on my side, I fell here, I could try the trick of @cdmoro but `$dispatch` not available, I used that, and it works correctly ! 

`onMounted(() => store.$patch(store.$state));`

hoping that it helps people :)
