### ISSUE TITLE
Non primitive types are not persisted

### ISSUE THREAD

**Issue by mwangaben** [prazdevs/pinia-plugin-persistedstate#54]
Kindly assist how do i persist this kindly of data using  this package

     `{
    "first_name": "Benedict",
    "last_name": "Mwanga",
    "email": "mwangab@gmail.com",
    "slug": "6ce2cd243f96554fc0f40a25c46e8dd0"
}`

**Comment by N0tExisting** [comment]
This is what the `serializer` option is for.

**Comment by prazdevs** [comment]
Hi :)
Any primitive type, and object containing primitive values will be serialized/deserialized properly. To work with non primitive types (such as `Date`), you can use the `hooks` (`beforeRestore` and `afterRestore`) or a customer `serializer` as suggested! :) 

This is documented here [pinia-plugin-persistedstate#references-do-not-persist](https://github.com/prazdevs/pinia-plugin-persistedstate#references-do-not-persist)

closing this

**Comment by SkaveRat** [comment]
In case anyone else lands here via google, the above link is now located here:

https://prazdevs.github.io/pinia-plugin-persistedstate/guide/limitations#non-primitive-types-are-not-persisted
