### ISSUE TITLE
How should I do with encryption libraries but choosing sessionStorage?

### ISSUE THREAD

**Issue by dpadula** [prazdevs/pinia-plugin-persistedstate#60]
I mean: How do I tell the storage to use sessionStorage and keep the three encryption methods? Can you help me with this please? Thanks in advance.

import { store } from 'quasar/wrappers'
import { createPinia } from 'pinia'
import { createPersistedState } from 'pinia-plugin-persistedstate'
import piniaPluginPersistedstate from 'pinia-plugin-persistedstate'
import SecureLS from "secure-ls";
const ls = new SecureLS({ isCompression: false });

/*
 * If not building with SSR mode, you can
 * directly export the Store instantiation;
 *
 * The function below can be async too; either use
 * async/await or return a Promise which resolves
 * with the Store instance.
 */

export default store((/* { ssrContext } */) => {
  const pinia = createPinia()

  // You can add Pinia plugins here
  pinia.use(createPersistedState({
    storage: {
      getItem: (key) => ls.get(key),
      setItem: (key, value) => ls.set(key, value),
      removeItem: (key) => ls.remove(key)
    }
  }))

  return pinia
})

**Comment by prazdevs** [comment]
If you want to use secure-ls, you can do it that way : 

```ts
const pinia = createPinia().use(createPersistedState({
  storage: {
    getItem: (key) => {
      return (new SecureLS({ isCompression: false })).get(key)
    },
    setItem: (key, value) => {
      (new SecureLS({ isCompression: false })).set(key, value)
    }
  }
}))
```

Just remember that secure-ls is based on localStorage, so you may want to create your own storagelike with a encryption only lib and sessionStorage instead of using secure-ls

**Comment by dpadula** [comment]
Thank you very much @prazdevs.

**Comment by prazdevs** [comment]
Closing this for now, feel free to reopen/open another issue if you have a question/problem. :)

**Comment by wlsdn93** [comment]
```js
persist: {
        storage: sessionStorage,
        serializer: {
            deserialize: (value) => {
                try {
                    const jsonStringData = decrypt(value)
                    return JSON.parse(jsonStringData)
                } catch (err) {
                    sessionStorage.clear()
                    logout()
                }
            },
            serialize: (value) => {
                const data = JSON.stringify(value)
                return encrypt(data)
            },
        },
    },
```

Here's an example code that demonstrates how to perform encryption and decryption with sessionStorage
