### ISSUE TITLE
Nuxt 3 with multiple composables does not persist

### ISSUE THREAD

**Issue by rowanfuchs** [prazdevs/pinia-plugin-persistedstate#63]
I've tried multiple solutions but I cannot seem to get my state persisted within Nuxt 3, here is an example with the pinia Options store. The same occurs when I use the Composition Api:

https://github.com/rowanfuchs/nuxt3-pinia-persist

Is there something I'm doing wrong? what can I do different to make sure the state is persisted.

**Comment by prazdevs** [comment]
Hi, in the given repo, you are not defining stores properly.

If you want to use options API like in https://github.com/rowanfuchs/nuxt3-pinia-persist , the `persist` option should be at the same level as other options (`state`, `actions`...).

```ts
import { defineStore } from "pinia";

export const useAuthStore = defineStore("auth", {
    state: () => {
        return {
            authenticated: false
        };
    },
    getters: {
        getAuthenticated: (state) => state.authenticated
    },
    actions: {
        setAuthenticated: async function (payload) {
            this.authenticated = payload
        }
    },
    persist: true,
});
```

**Comment by rowanfuchs** [comment]
Thank you for taking the time to correct my mistake 😊. I will leave the repository up as a reference for others.
