### ISSUE TITLE
How can i use Cookies options?

### ISSUE THREAD

**Issue by xucxichcao** [prazdevs/pinia-plugin-persistedstate#67]
I want to set maxAge for the persisted state using Pinia in Nuxt 3. However, TypeScript keeps telling me that this is not assignable.

![ảnh](https://user-images.githubusercontent.com/73663860/169278001-764e7622-54ab-4c78-9d90-319a2f347551.png)

**Comment by prazdevs** [comment]
Hi @xucxichcao , I made a PR for it. It would allow you to pass `CookieOptions` to the `FactoryOptions` like this :

```ts
import { createNuxtPersistedState } from 'pinia-plugin-persistedstate'

export default defineNuxtPlugin(nuxtApp => {
  nuxtApp.$pinia.use(createNuxtPersistedState(useCookie, { cookieOptions: { maxAge: 3600 } }))
})
```

**Comment by xucxichcao** [comment]
Hi @prazdevs, I made a PR for the new bug. I'm unsure if this is my Nuxt3's problem or not. This is the first time I have made a PR so I don't know if I'm doing it properly, TIA.
