### ISSUE TITLE
More right configure in example

### ISSUE THREAD

**Issue by chris-zhu** [prazdevs/pinia-plugin-persistedstate#69]
Thank you for your very nice library firstly.

I have some problems about usage, can you share more right configure about `presist`?
Just `{presist: true}` in example, maybe somebody want to custom this option, and debug example project in local env.

Finally, thanks for the detailed documentation

**Comment by prazdevs** [comment]
Hi, there are some examples of configuration in the docs:

```ts
import { defineStore } from 'pinia'

export const useStore = defineStore('main', {
  state: () => {
    return {
      someState: 'hello pinia',
      nested: {
        data: 'nested pinia',
      },
    }
  },
  persist: {
    key: 'store-key',
    storage: window.sessionStorage,
    paths: ['nested.data'],
    beforeRestore: context => {
      console.log('Before hydration...')
    },
    afterRestore: context => {
      console.log('After hydration...')
    },
  },
})
```

I'm still in the process of writing proper docs for it. Does that answer your question ?

**Comment by chris-zhu** [comment]
> 

Thanks your reply.
I meet some trouble in Nuxt3. I test use example config with docs, but it can't resolve. So i hope to improve the example.

As for my trouble: 
<img width="659" alt="image" src="https://user-images.githubusercontent.com/42139754/169638007-2fd6a4bb-8ba3-4478-ad4c-002fcf0da3c4.png">

I can't see any cache in my cookies about this store, but other store was fine. (I test `setup` & `configure` pinia options, but they were unsuccessful )

**Comment by Stiropor** [comment]
Same problem here, not working with Nuxt3 anymore. It worked fine on Friday, after that it's not setting the cookie anymore. I've tried loading plugin as client also, no difference. Maybe something has changed in Nuxt about cookies?

**Comment by prazdevs** [comment]
Can you provide a proper reproduction repo? It still works fine on my side.

**Comment by Stiropor** [comment]
I'm defining the plugin as per documentation, this is my store. This code set the cookie few days ago but doesn't anymore.
```js
import { defineStore } from 'pinia'

export const useCartStore = defineStore({
	id: 'cart-store',
	persist: {
		paths: ['uuid'],
	},
	state: () => ({
		uuid: null,
	}),

	actions: {
		updateCart (payload) {
			this.uuid = payload.uuid
		}
	}
})

```
I cannot give full repo right now, but will try to make it in following days.
