### ISSUE TITLE
Local storage needs encryption

### ISSUE THREAD

**Issue by liuchihanxiang** [prazdevs/pinia-plugin-persistedstate#75]
Local storage needs encryption. I hope to provide two hook functions,

I need to encrypt before saving

I need to decrypt before taking values

**Comment by prazdevs** [comment]
Hi, if you need to encrypt you can define a new Storage that implements it, or you can also use the Serializer option.

Here's an example using secure-ls : https://github.com/prazdevs/pinia-plugin-persistedstate/issues/60

**Comment by prazdevs** [comment]
closing this for now, feel free to reopen if you need more info :)
