### ISSUE TITLE
[core] support conditional storage

### ISSUE THREAD

**Issue by wxhccc** [prazdevs/pinia-plugin-persistedstate#76]
Sometimes we need to use a path to determine whether another path needs to be persisted, so I suggest to expanding the `options.paths`

```
type CheckStateProp = (store: PiniaPluginContext['store']) => boolean
type PropPath = string | [string, CheckStateProp]


...
// when use
paths: ['a', ['b', (store) => store.a === true]]
```

if `a` is true, `b` will persisted, otherwise not persisted `b`

**Comment by wxhccc** [comment]
it's all right. but I don't think it is good way. for example:

```
persist: [
{
  path: 'a',
  beforeRestore: () => {},
  afterRestore: () => {},
  serializer: {
    serialize: JSON.stringify,
    deserialize: JSON.parse,
  }
},
{
  path: 'b',
  persist: (store) => store.a === true,
  beforeRestore: () => {},
  afterRestore: () => {},
  serializer: {
    serialize: JSON.stringify,
    deserialize: JSON.parse,
  }
}
]
```
i need to pass other properties in every item.
[zhuzhengshou](https://github.com/zhuzhengshou) want to to separate state values to localstorage and sessionstorage at  the same time when state change.

**Comment by wxhccc** [comment]
it's all right. but I don't think it is good way. for example:

```
persist: [
{
  path: 'a',
  beforeRestore: () => {},
  afterRestore: () => {},
  serializer: {
    serialize: JSON.stringify,
    deserialize: JSON.parse,
  }
},
{
  path: 'b',
  persist: (store) => store.a === true,
  beforeRestore: () => {},
  afterRestore: () => {},
  serializer: {
    serialize: JSON.stringify,
    deserialize: JSON.parse,
  }
}
]
```
i need to pass other properties in every item.
[zhuzhengshou](https://github.com/zhuzhengshou) want to to separate state values to localstorage and sessionstorage at  the same time when state change.

**Comment by prazdevs** [comment]
hmm i see what you mean, i kinda saw a good opportunity as both feature ideas are linked to per-path config

**Comment by prazdevs** [comment]
ok i may have an exampls that could help you?

```ts
    persist: {
      serializer: {
        deserialize: JSON.parse,
        serialize: (state) => {
          const { a, b } = state
          const toStore = a ? { a, b } : { a }
          return JSON.stringify(toStore)
        }
      }
    },
```

You can use the serializer to define conditions for elements to be persisted or not. I think that's the best way to do it without adding "too much" to the plugin :) 

Let me know if that helped

**Comment by wxhccc** [comment]
> ok i may have an exampls that could help you?
> 
> ```ts
>     persist: {
>       serializer: {
>         deserialize: JSON.parse,
>         serialize: (state) => {
>           const { a, b } = state
>           const toStore = a ? { a, b } : { a }
>           return JSON.stringify(toStore)
>         }
>       }
>     },
> ```
> 
> You can use the serializer to define conditions for elements to be persisted or not. I think that's the best way to do it without adding "too much" to the plugin :)
> 
> Let me know if that helped

yes, it works. but if i need to use custom serializer to do some complex questions, I prefer write a local pinia plugin to do this.

**Comment by prazdevs** [comment]
You can always define an external function that returns the state to store from the current state, and have concerns separated this way.

**Comment by prazdevs** [comment]
Closing this as it has a workaround, and probably won't see an implementation in the current situation. Feel free to propose new stuff :)
