### ISSUE TITLE
lose the intellisense for the actions method, typescript will report an error

### ISSUE THREAD

**Issue by Kento97** [prazdevs/pinia-plugin-persistedstate#78]
## Computer environment：
- win10
- node: v14.19.0
- vue: 3.2.36
- pinia : 2.0.14
- pinia-plugin-persistedstate : 1.6.1
- typescript:4.7.3
- vite : 2.9.9
-  IDE : vscode / webstorm
### adding the persist option in defineStore will lose the intellisense for the actions method, typescript will report an error
![image](https://user-images.githubusercontent.com/55472948/174477046-21e5b9db-e813-4439-842d-b9d8fe0fa732.png)
![image](https://user-images.githubusercontent.com/55472948/174477097-1931d23c-4371-4fd8-a330-10e5e216dcbb.png)

**Comment by prazdevs** [comment]
`enabled: true` isnt a valid option for the plugin 🤔  

I couldn't reproduce the loss of intellisense for actions either ☹️
