### ISSUE TITLE
Encrypting the Nuxt cookie?

### ISSUE THREAD

**Issue by scalemaildev** [prazdevs/pinia-plugin-persistedstate#81]
I'm using Nuxt3 and I have some persistent data I need to protect. Nuxt3's useCookie by itself doesn't have an option for encryption so I'm wondering if this plugin could take care of that? I also dont see anything in the docs about using secure or sameSite with the cookie.

Thanks.

**Comment by prazdevs** [comment]
Hello :) 

You can use the cookie options from https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/src/types.ts#L80 , the factory takes the same options nuxt's useCookie does to configure cookies (sameSite, maxAge, secure...)

If you wish to encrypt, you can use the `serializer` option to encrypt while serializing :)

**Comment by scalemaildev** [comment]
Here's some code for anyone else looking to set cookie options:

```
import { createNuxtPersistedState } from 'pinia-plugin-persistedstate';
import { defineNuxtPlugin, useCookie } from '#app';

export default defineNuxtPlugin(nuxtApp => {
    nuxtApp.$pinia.use(createNuxtPersistedState(useCookie, {
        cookieOptions: {
            secure: true,
            sameSite: 'strict'
        }
    }))
})
```

And I know you can add ```serializer``` as well but I haven't really found a module I like for encryption. I used to use the module https://www.npmjs.com/package/nuxt-vuex-localstorage which encrypted everything for me and I'm looking for something similar to use here.
