### ISSUE TITLE
Unable to persist state ^1.6.1

### ISSUE THREAD

**Issue by ASoldo** [prazdevs/pinia-plugin-persistedstate#85]
HI, I have created fresh Nuxt 3 project with these dependencies. 
`"devDependencies": {
    "@nuxt/content": "^2.0.1",
    "nuxt": "3.0.0-rc.4",
    "tailwindcss": "^3.1.6"
  },
  "dependencies": {
    "@heroicons/vue": "^1.0.6",
    "@nuxt/types": "^2.15.8",
    "@nuxt/typescript-build": "^2.1.0",
    "@pinia/nuxt": "^0.2.0",
    "pinia": "^2.0.15",
    "pinia-plugin-persistedstate": "^1.6.1"
  }` 

**this is a plugin that I have followed by .md instructions for Nuxt.** 
`import { createNuxtPersistedState } from 'pinia-plugin-persistedstate'
import { defineNuxtPlugin, useCookie } from '#app'
export default defineNuxtPlugin(nuxtApp => {
  nuxtApp.$pinia.use(createNuxtPersistedState(useCookie))
})` 

**this is my nuxt.config.ts**
`  modules: ['@pinia/nuxt',  '@nuxt/content'],
    plugins: [
    {src: '~/plugins/pinia-persisted.client.ts', mode: 'client'}
    ]` 

**this is my state/index.ts**
`import { defineStore } from 'pinia'
export const useFiltersStore = defineStore('my-store', () => {
  const counter = ref<number>(0);
  return {
    counter
  }
},{
  persist: true
})` 

Can you point out if I made some mistake or if I am missing something? I have no errors with pinia, state is working as expected just I am unable to have persisted state for 'my-state'.

Thank you!

**Comment by ASoldo** [comment]
[https://github.com/ASoldo/nuxt-app ](url) this is my repo, you can see files and structure that I use. It is a fresh Nuxt3 installation with pinia. I have tried also pinia-plugin-persistedstate-2 but not luck either.

**Comment by prazdevs** [comment]
Okay i fiddled around and found out that `nuxtApp.$pinia` returns undefined while `nuxtApp.pinia` contains the pinia instance. which is a bit weird to say the least. I am having some issues with nuxt on the repo example as well. I will look into it if i get some time this weekend, to make it clear on how to have the plugin work fine with nuxt. (also considering nuxt is not yet in a "stable" state)

**Comment by ASoldo** [comment]
AAA JUUU! It works! You saved me a lot of trouble. Thank you so much!
