### ISSUE TITLE
Persistence does not work

### ISSUE THREAD

**Issue by iBobik** [prazdevs/pinia-plugin-persistedstate#86]
Just added it to official Pinia demo, but persistence does not work:
https://stackblitz.com/edit/github-j3zitf?file=src/stores/cart.js

**Comment by prazdevs** [comment]
Hi, it works, but only if you install the plugin, otherwise Pinia will never know 🤔 

See https://github.com/prazdevs/pinia-plugin-persistedstate#%EF%B8%8F-installing

tl;dr : `pinia.use(createPersistedState())` 

I can only recommend using typescript, because ts engine would've thrown errors.

**Comment by iBobik** [comment]
You mean missing ()? I have copied it from your README. And I use TS in my project, no error.

Honza Pobořil
💬Signal

**Comment by prazdevs** [comment]
Idk the stackblitz you gave for reproduction is in pure JS 🙃 

In the `main.js` file you have: 
```js
import { createPinia } from 'pinia'
import { createApp } from 'vue'
import App from './App.vue'

createApp(App).use(createPinia()).mount('#app')
```

But you should have something like
```js
import { createPinia } from 'pinia'
import { createApp } from 'vue'
import { createPersistedState } from 'pinia-plugin-persistedstate' 
import App from './App.vue'

createApp(App)
  .use(createPinia().use(createPersistedState()))  // this line injects the plugin into Pinia
  .mount('#app')
```

**Comment by ivan0525** [comment]
> Idk the stackblitz you gave for reproduction is in pure JS 🙃
> 
> In the `main.js` file you have:
> 
> ```js
> import { createPinia } from 'pinia'
> import { createApp } from 'vue'
> import App from './App.vue'
> 
> createApp(App).use(createPinia()).mount('#app')
> ```
> 
> But you should have something like
> 
> ```js
> import { createPinia } from 'pinia'
> import { createApp } from 'vue'
> import { createPersistedState } from 'pinia-plugin-persistedstate' 
> import App from './App.vue'
> 
> createApp(App)
>   .use(createPinia().use(createPersistedState()))  // this line injects the plugin into Pinia
>   .mount('#app')
> ```

In your official documentation said：

```ts
import { createPinia } from 'pinia'
import piniaPluginPersistedstate from 'pinia-plugin-persistedstate'

const pinia = createPinia()
pinia.use(piniaPluginPersistedstate)
```

But neither of these ways worked for me.

**Comment by lxdora** [comment]
same issue. maybe it's because you used store in your router, put the store inside guards
