### ISSUE TITLE
Manually sync store

### ISSUE THREAD

**Issue by furkan-guvenc** [prazdevs/pinia-plugin-persistedstate#87]
### Clear and concise description of the problem

I want to sync pinia state with local storage every time when a tab is opened. There is a [visibility web API](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API) that I can use. But I need a method to sync local storage

### Suggested solution

In [plugin.ts](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/src/plugin.ts#L38), state is restored with this code

```ts
beforeRestore?.(context)

try {
  const fromStorage = storage.getItem(key)
  if (fromStorage) store.$patch(serializer.deserialize(fromStorage))
} catch (_error) {}

afterRestore?.(context)
```

We can make it a function and export it. So local storage or session storage can be restored manually

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by prazdevs** [comment]
Hi, while i see the motivation behind this idea, I wonder if you had an example of implementation. Like where can this be exported/imported from ? 🤔

**Comment by furkan-guvenc** [comment]
I was thinking, you may have an idea for it. I will think about it

**Comment by prazdevs** [comment]
Closing this since V2 is now released with the $hydrate method! 🎉

**Comment by furkan-guvenc** [comment]
Congratulations 🥇
