### ISSUE TITLE
useCookie nuxt options

### ISSUE THREAD

**Issue by stephenjason89** [prazdevs/pinia-plugin-persistedstate#88]
### Describe the bug

Can't set an expires or maxAge option in cookie
I need to set expires or maxAge to be able to persist after user has closed the browser.

By default it treats it as a session cookie("non-persistent-cookie") and clears upon browser exit.

<img width="737" alt="image" src="https://user-images.githubusercontent.com/3810177/180386840-a727a4ec-e1c0-442a-9b77-c4e3dfc452b5.png">

Passing this doesn't work
<img width="762" alt="image" src="https://user-images.githubusercontent.com/3810177/180386995-a53f421f-7516-4ad9-974a-b9a88ac10573.png">

````{ expires: 365, secure: true }````
### Reproduction

use it in nuxt useCookie

### System Info

```Shell
Microsoft Edge
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by prazdevs** [comment]
Hi, the documentation for that isnt really complete yet, but the NuxtFactoryOptions have a cookieOptions property so  you want to configure it that way

```ts
createNuxtPersistedState(useCookie, { 
  cookieOptions: { 
    expires: 60 * 60 * 24 * 30, 
    maxAge: 60 * 60 * 24 * 30,
  },
})
```

**Comment by stephenjason89** [comment]
Hello @prazdevs It's not working. Cookie stopped being set after i placed that option.
Now Cookie doesn't store anything.

**Comment by stephenjason89** [comment]
Hey @prazdevs 
Everything is working now. Expires should be a date object and not number of seconds, which explains the error i am getting.

Now, I just want to point out some type check errors which i just ts-ignore for the moment
<img width="1224" alt="image" src="https://user-images.githubusercontent.com/3810177/180652194-eb6ec9a1-5c03-4f69-975a-0db12deca9bf.png">

**Comment by prazdevs** [comment]
V2 is now released and it should be fixed!

**Comment by stephenjason89** [comment]
Thanks @prazdevs
