### ISSUE TITLE
How can i mock localStorage

### ISSUE THREAD

**Issue by mitraecp** [prazdevs/pinia-plugin-persistedstate#92]
I need help to mock localStorage on vitest, some one help?

![image](https://user-images.githubusercontent.com/75841640/181360389-ac42e7c7-27cf-46be-af0f-e3d2636b4536.png)

**Comment by prazdevs** [comment]
Hi, please consider couple things:
- Use issue templates
- At least provide slightly more context
- This is a question that has been answered in a lot of places and is a common thing
- This same repo you opened an issue on has an answer in its file

Here's how the plugin's own tests mock local storage.

```ts
beforeEach(() => {
  let state: Record<string, string> = {}
  Object.defineProperty(window, 'localStorage', {
    value: {
      getItem: vi.fn(key => state[key]),
      setItem: vi.fn((key, value) => {
        state[key] = value
      }),
      removeItem: vi.fn(key => delete state[key]),
      clear: vi.fn(() => {
        state = {}
      }),
    },
  })
})
```
