### ISSUE TITLE
nuxt3 example for 2.0?

### ISSUE THREAD

**Issue by andysay** [prazdevs/pinia-plugin-persistedstate#93]
### Clear and concise description of the problem

example was removed in 2.0

### Suggested solution

please add it. :)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by prazdevs** [comment]
Ye it was planned to make many more examples for any vue-related framework. I'll add it back asap ! :)

**Comment by prazdevs** [comment]
Nuxt 3 example is back ! 
https://github.com/prazdevs/pinia-plugin-persistedstate/tree/main/examples/nuxt-3

🎉

**Comment by kurkurzz** [comment]
The link is dead. can you update?

**Comment by prazdevs** [comment]
Hi nuxt 3 is now much easier to configure with the dedicated module https://prazdevs.github.io/pinia-plugin-persistedstate/frameworks/nuxt-3.html

**Comment by 11003** [comment]
> Nuxt 3 example is back ! https://github.com/prazdevs/pinia-plugin-persistedstate/tree/main/examples/nuxt-3
> 
> 🎉

404 - page not found

**Comment by prazdevs** [comment]
> > Nuxt 3 example is back ! https://github.com/prazdevs/pinia-plugin-persistedstate/tree/main/examples/nuxt-3
> > 🎉
> 
> 404 - page not found

This is the correct updated docs https://prazdevs.github.io/pinia-plugin-persistedstate/frameworks/nuxt.html
