### ISSUE TITLE
[core] feat: Take the value of Paths only the final layer

### ISSUE THREAD

**Issue by yucccc** [prazdevs/pinia-plugin-persistedstate#95]
### Clear and concise description of the problem

Now set the value obtained by Paths and the path is too long. I only want the data at the bottom layer. What should I do?

```
  persist: {
    paths: ['page.totalResData'],
  }
```
get

![image](https://user-images.githubusercontent.com/24189407/182032030-71aae095-663f-4850-b3b2-1f3d6839ed31.png)

But I just want to get the following format:

```
  totalResData: {
    // ...my data
  }
```

### Suggested solution

![image](https://user-images.githubusercontent.com/24189407/182032273-2db964b5-edea-46f0-ac9d-cecfebdf022e.png)

Add a parameter to make it go directly to the final level

Then I can get such data

![image](https://user-images.githubusercontent.com/24189407/182032959-2a7821f1-eec6-4dde-9088-02bf9bb7c336.png)

My English is not good, forgive me

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by prazdevs** [comment]
Mmmh I don't really understand what you are trying to achieve, can you be more explicit and give detailed examples ? thanks :)

**Comment by prazdevs** [comment]
Dont worry about english, as long as we understand what you need and can work it out 💪 

I just don't understand the "I only want the data at the bottom layer." part. Are we trying to flatten everything under "totalResData" ?

I can somehow see what is behind this with the "flatten" but flatten is usually made with Arrays and not objects ?

**Comment by yucccc** [comment]
> Mmmh I don't really understand what you are trying to achieve, can you be more explicit and give detailed examples ? thanks :)

Because our logic for saving code is multiple sets, and the logic for fetching data is unified, which means that the data fields saved between multiple platforms should be consistent, but now other platforms save data at the final level, and use this plugin to save data It is the original level data, which will cause other platforms to fetch data and report errors.

**Comment by yucccc** [comment]
> Dont worry about english, as long as we understand what you need and can work it out 💪
> 
> I just don't understand the "I only want the data at the bottom layer." part. Are we trying to flatten everything under "totalResData" ?
> 
> I can somehow see what is behind this with the "flatten" but flatten is usually made with Arrays and not objects ? 
`Flatten` parameter is just an example 
I only expect to get the final data according to the paths I set, without the original hierarchical relationship of the store

**Comment by prazdevs** [comment]
so you want ```totalResData: {
    // ...my data
  }``` to be in the storage (localstorage for instance) instand of the whole tree right ?

**Comment by yucccc** [comment]
yes !

**Comment by wxhccc** [comment]
@prazdevs 
what he need is not simple flatten。
he need such
```
paths: [{ statePath: 'page.totalResData', storagePath: 'totalResData' }]
// or
paths: [['page.totalResData', 'totalResData']]
```

**Comment by prazdevs** [comment]
given how the plugin is and how simple it has to stay, this will no be implemented.
however you can still implement this "flatten" style method in your own storage.setItem / storage.getItem
